INSERT INTO `degrees` (`id`, `name`, `created_at`, `updated_at`) VALUES
(1, 'Associate of Arts', NULL, NULL),
(2, 'Associate of Engineering or Associate in Electronics Engineering Technology', NULL, NULL),
(3, 'Associate of Science in Nursing', NULL, NULL),
(4, 'Associate of Science', NULL, NULL),
(5, 'Associate of Science in Accounting', NULL, NULL),
(6, 'Associate of Forestry', NULL, NULL),
(7, 'Associate of Technology', NULL, NULL),
(8, 'Associate of Applied Arts', NULL, NULL),
(9, 'Associate of Applied Business', NULL, NULL),
(10, 'Associate of Applied Science or Associate of Arts and Sciences', NULL, NULL),
(11, 'Associate of Arts in Teaching', NULL, NULL),
(12, 'Associate of Business Administration', NULL, NULL),
(13, 'Associate of Baccalaureate Studies', NULL, NULL),
(14, 'Associate Degree in Nursing', NULL, NULL),
(15, 'Associate of Engineering Science', NULL, NULL),
(16, 'Associate in Engineering Technology', NULL, NULL),
(17, 'Associate of Fine Arts', NULL, NULL),
(18, 'Associate of General Studies', NULL, NULL),
(19, 'Associate of Industrial Technology', NULL, NULL),
(20, 'Associate of Occupational Studies', NULL, NULL),
(21, 'Associate in Occupational Technology', NULL, NULL),
(22, 'Associate of Pre-Engineering', NULL, NULL),
(23, 'Associate of Political Science or Associate of Public Service', NULL, NULL),
(24, 'Associate in Physical Therapy', NULL, NULL),
(25, 'Bachelor of Architecture', NULL, NULL),
(26, 'Bachelor of Design', NULL, NULL),
(27, 'Bachelor of Arts', NULL, NULL),
(28, 'Bachelor of Applied Arts', NULL, NULL),
(29, 'Bachelor of Applied Arts and Science', NULL, NULL),
(30, 'Bachelor of Engineering', NULL, NULL),
(31, 'Bachelor of Technology', NULL, NULL),
(32, 'Bachelor of Engineering Technology', NULL, NULL),
(33, 'Bachelor of Business Administration', NULL, NULL),
(34, 'International Business Economics', NULL, NULL),
(35, 'Bachelor of Science in Business', NULL, NULL),
(36, 'Bachelor of Management Studies', NULL, NULL),
(37, 'Bachelor of Administrative Studies', NULL, NULL),
(38, 'Bachelor of International Business Economics', NULL, NULL),
(39, 'Bachelor of Commerce', NULL, NULL),
(40, 'Bachelor of Business', NULL, NULL),
(41, 'Bachelor of Management and Organizational Studies', NULL, NULL),
(42, 'Bachelor of Business Science', NULL, NULL),
(43, 'Bachelor of Accountancy', NULL, NULL),
(44, 'Bachelor of Comptrolling', NULL, NULL),
(45, 'Bachelor of Economics', NULL, NULL),
(46, 'Bachelor of Arts in Organizational Management', NULL, NULL),
(47, 'Bachelor of Computing', NULL, NULL),
(48, 'Bachelor of Computer Science', NULL, NULL),
(49, 'Bachelor of Science in Information Technology', NULL, NULL),
(50, 'Bachelor of Computer Applications', NULL, NULL),
(51, 'Bachelor of Applied Science in Information Technology', NULL, NULL),
(52, 'Bachelor of Business Information Systems', NULL, NULL),
(53, 'Intercalated Bachelor of Science', NULL, NULL),
(54, 'Bachelor of Medical Science', NULL, NULL),
(55, 'Bachelor of Medical Biology', NULL, NULL),
(56, 'Doctorate of Dental Surgery', NULL, NULL),
(57, 'Bachelor of Science in Nursing', NULL, NULL),
(58, 'Bachelor of Science in Public Health', NULL, NULL),
(59, 'Bachelor of Health Science', NULL, NULL),
(60, 'Bachelor of Science in Human Biology', NULL, NULL),
(61, 'Bachelor of Kinesiology', NULL, NULL),
(62, 'Bachelor of Aviation', NULL, NULL),
(63, 'Bachelor of Divinity', NULL, NULL),
(64, 'Bachelor of Theology', NULL, NULL),
(65, 'Bachelor of Religious Studies', NULL, NULL),
(66, 'Bachelor of Religious Education', NULL, NULL),
(67, 'Bachelor of Fine Arts', NULL, NULL),
(68, 'Bachelor of Film and Television', NULL, NULL),
(69, 'Bachelor of Integrated studies', NULL, NULL),
(70, 'Bachelor of Journalism', NULL, NULL),
(71, 'Bachelor of Landscape Architecture', NULL, NULL),
(72, 'Bachelor of Liberal Arts', NULL, NULL),
(73, 'Bachelor of General Studies', NULL, NULL),
(74, 'Bachelor of Applied Studies', NULL, NULL),
(75, 'Bachelor of Liberal Studies', NULL, NULL),
(76, 'Bachelor of Professional Studies', NULL, NULL),
(77, 'Bachelor of Library Science', NULL, NULL),
(78, 'Bachelor of Library and Information Science', NULL, NULL),
(79, 'Bachelor of Music', NULL, NULL),
(80, 'Bachelor of Art in Music', NULL, NULL),
(81, 'Bachelor of Music Education', NULL, NULL),
(82, 'Bachelor of Mortuary Science', NULL, NULL),
(83, 'Bachelor of Philosophy', NULL, NULL),
(84, 'Bachelor of Arts in Psychology', NULL, NULL),
(85, 'Bachelor of Science in Psychology', NULL, NULL),
(86, 'Bachelor of Science in Education', NULL, NULL),
(87, 'Bachelor of Science in Finance', NULL, NULL),
(88, 'Bachelor of Arts for Teaching', NULL, NULL),
(89, 'Bachelor of Science and/with education degree', NULL, NULL),
(90, 'Bachelor of Science in Forestry', NULL, NULL),
(91, 'Bachelor of Applied Science', NULL, NULL),
(92, 'Bachelor of Science in Law', NULL, NULL),
(93, 'Bachelor of Social Science', NULL, NULL),
(94, 'Bachelor of Arts in Social Work', NULL, NULL),
(95, 'Bachelor of Technology', NULL, NULL),
(96, 'Bachelor of Talmudic Law', NULL, NULL),
(97, 'Bachelor of Tourism Studies', NULL, NULL),
(98, 'Bachelor of Mathematics', NULL, NULL),
(99, 'Bachelor of Mathematical Sciences', NULL, NULL),
(100, 'Bachelor of Urban and Regional Planning', NULL, NULL),
(101, 'Bachelor of Public Affairs and Policy Management', NULL, NULL),
(102, 'Master of Accountancy', NULL, NULL),
(103, 'Master of Advanced Study', NULL, NULL),
(104, 'Master of Economics', NULL, NULL),
(105, 'Master of Applied Science', NULL, NULL),
(106, 'Master of Architecture', NULL, NULL),
(107, 'Master of Arts', NULL, NULL),
(108, 'Master of Arts in Teaching', NULL, NULL),
(109, 'Master of Arts in Liberal Studies', NULL, NULL),
(110, 'Master of Business Administration', NULL, NULL),
(111, 'Master of Business', NULL, NULL),
(112, 'Master of Business Informatics', NULL, NULL),
(113, 'Master of Chemistry', NULL, NULL),
(114, 'Master of City Planning', NULL, NULL),
(115, 'Master of Commerce', NULL, NULL),
(116, 'Master of Computational Finance', NULL, NULL),
(117, 'Master of Computer Applications', NULL, NULL),
(118, 'Master of Criminal Justice', NULL, NULL),
(119, 'Master in Creative Technologies', NULL, NULL),
(120, 'Master of Design', NULL, NULL),
(121, 'Master of Divinity', NULL, NULL),
(122, 'Master of Economics', NULL, NULL),
(123, 'Master of Education', NULL, NULL),
(124, 'Master of Engineering', NULL, NULL),
(125, 'Master of Engineering Management', NULL, NULL),
(126, 'Master of Enterprise', NULL, NULL),
(127, 'Master of European Law', NULL, NULL),
(128, 'Master of Finance', NULL, NULL),
(129, 'Master of Financial Economics', NULL, NULL),
(130, 'Master of Financial Engineering', NULL, NULL),
(131, 'Master of Financial Mathematics', NULL, NULL),
(132, 'Master of Fine Arts', NULL, NULL),
(133, 'Master of Health Administration', NULL, NULL),
(134, 'Master of Health Science', NULL, NULL),
(135, 'Master of Humanities', NULL, NULL),
(136, 'Master of Industrial and Labor Relations', NULL, NULL),
(137, 'Master of International Affairs', NULL, NULL),
(138, 'Master of International Business', NULL, NULL),
(139, 'Masters in International Economics', NULL, NULL),
(140, 'Master of International Studies', NULL, NULL),
(141, 'Master of Information System Management', NULL, NULL),
(142, 'Master of IT', NULL, NULL),
(143, 'Master of Jurisprudence', NULL, NULL),
(144, 'Master of Laws', NULL, NULL),
(145, 'Master of Studies in Law', NULL, NULL),
(146, 'Master of Landscape Architecture', NULL, NULL),
(147, 'Master of Letters', NULL, NULL),
(148, 'Master of Liberal Arts', NULL, NULL),
(149, 'Master of Library and Information Science', NULL, NULL),
(150, 'Master of Management', NULL, NULL),
(151, 'Master of Mathematical Finance', NULL, NULL),
(152, 'Master of Mathematics', NULL, NULL),
(153, 'Master of Medical Science', NULL, NULL),
(154, 'Master of Music', NULL, NULL),
(155, 'Master of Occupational Therapy', NULL, NULL),
(156, 'Master of Pharmacy', NULL, NULL),
(157, 'Master of Philosophy', NULL, NULL),
(158, 'Master of Physician Assistant Studies', NULL, NULL),
(159, 'Master of Physics', NULL, NULL),
(160, 'Master of Political Science', NULL, NULL),
(161, 'Master of Professional Studies', NULL, NULL),
(162, 'Master of Public Administration', NULL, NULL),
(163, 'Master of Public Affairs', NULL, NULL),
(164, 'Master of Public Health', NULL, NULL),
(165, 'Master of Public Policy', NULL, NULL),
(166, 'Master of Public Management', NULL, NULL),
(167, 'Master of Quantitative Finance', NULL, NULL),
(168, 'Master of Rabbinic Studies', NULL, NULL),
(169, 'Master of Real Estate Development', NULL, NULL),
(170, 'Master of Religious Education', NULL, NULL),
(171, 'Master of Research', NULL, NULL),
(172, 'Master of Sacred Music', NULL, NULL),
(173, 'Master of Sacred Theology', NULL, NULL),
(174, 'Master of Science', NULL, NULL),
(175, 'Master of Science in Education', NULL, NULL),
(176, 'Master of Science in Engineering', NULL, NULL),
(177, 'Master of Science in Finance', NULL, NULL),
(178, 'Master of Science in Human Resource Development', NULL, NULL),
(179, 'Master of Science in Information Systems', NULL, NULL),
(180, 'Master of Science in Information Systems Management', NULL, NULL),
(181, 'Master of Science in Information Technology', NULL, NULL),
(182, 'Master of Science in Leadership', NULL, NULL),
(183, 'Master of Science in Management', NULL, NULL),
(184, 'Master of Science in Nursing', NULL, NULL),
(185, 'Master of Science in Project Management', NULL, NULL),
(186, 'Master of Science in Supply Chain Management', NULL, NULL),
(187, 'Master of Science in Teaching', NULL, NULL),
(188, 'Master of Science in Taxation', NULL, NULL),
(189, 'Master of Social Science', NULL, NULL),
(190, 'Master of Social Work', NULL, NULL),
(191, 'Master of Studies', NULL, NULL),
(192, 'Master of Surgery', NULL, NULL),
(193, 'Master of Theological Studies', NULL, NULL),
(194, 'Master of Theology', NULL, NULL),
(195, 'Master of Urban Planning', NULL, NULL),
(196, 'Master of Veterinary Science', NULL, NULL);
