INSERT INTO `job_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES
(1, 'Nursing', NULL, NULL),
(2, 'Sales and Business Development', NULL, NULL),
(3, 'Transportation', NULL, NULL),
(4, 'Personal and Home Services', NULL, NULL),
(5, 'Law Enforcement / Security', NULL, NULL),
(6, 'IT and Network Administration', NULL, NULL),
(7, 'Customer Service', NULL, NULL),
(8, 'Healthcare', NULL, NULL),
(9, 'Supply Chain and Logistics', NULL, NULL),
(10, 'Hotel, Restaurant, Tourism Management', NULL, NULL),
(11, 'Fashion and Beauty', NULL, NULL),
(12, 'Retail', NULL, NULL),
(13, 'Skilled Trades and Manual Labor', NULL, NULL),
(14, 'Project and Product Management', NULL, NULL),
(15, 'Teaching, Training and Education', NULL, NULL),
(16, 'Office and Administrative', NULL, NULL),
(17, 'Building and Construction', NULL, NULL),
(18, 'Business Management', NULL, NULL),
(19, 'Accounting and Finance', NULL, NULL),
(20, 'Real Estate', NULL, NULL),
(21, 'Science and Research', NULL, NULL),
(22, 'Software Development and Architecture', NULL, NULL),
(23, 'Human Resources', NULL, NULL),
(24, 'Marketing and Advertising', NULL, NULL),
(25, 'Arts, Entertainment and Gaming', NULL, NULL),
(26, 'Manufacturing, Warehouse and Production', NULL, NULL),
(27, 'Healthcare Administration', NULL, NULL),
(28, 'Insurance', NULL, NULL),
(29, 'Consulting', NULL, NULL),
(30, 'Government and Social Work', NULL, NULL),
(31, 'Animal Services', NULL, NULL),
(32, 'Data Management and Administration', NULL, NULL),
(33, 'Engineering', NULL, NULL),
(34, 'Legal', NULL, NULL),
(35, 'Fitness and Wellness', NULL, NULL),
(36, 'Media and Communications', NULL, NULL),
(37, 'Quality Assurance', NULL, NULL),
(38, 'Software and Web Design', NULL, NULL),
(39, 'Non-Profit', NULL, NULL),
(40, 'Business Intelligence', NULL, NULL),
(41, 'Sports and Recreation', NULL, NULL);
