INSERT INTO `location_provinces` (`id`, `region_id`, `name`, `created_at`, `updated_at`) VALUES
('ABR', 'CAR', 'Abra', NULL, NULL),
('AGN', 'XIII', 'Agusan del Norte', NULL, NULL),
('AGS', 'XIII', 'Agusan del Sur', NULL, NULL),
('AKL', 'VI', 'Aklan', NULL, NULL),
('ALB', 'V', 'Albay', NULL, NULL),
('ANT', 'VI', 'Antique', NULL, NULL),
('APA', 'CAR', 'Apayao', NULL, NULL),
('AUR', 'III', 'Aurora', NULL, NULL),
('BAN', 'III', 'Bataan', NULL, NULL),
('BAS', 'ARMM', 'Basilan', NULL, NULL),
('BEN', 'CAR', 'Benguet', NULL, NULL),
('BIL', 'VIII', 'Biliran', NULL, NULL),
('BOH', 'VII', 'Bohol', NULL, NULL),
('BTG', 'IV-A', 'Batangas', NULL, NULL),
('BTN', 'II', 'Batanes', NULL, NULL),
('BUK', 'X', 'Bukidnon', NULL, NULL),
('BUL', 'III', 'Bulacan', NULL, NULL),
('CAG', 'II', 'Cagayan', NULL, NULL),
('CAM', 'X', 'Camiguin', NULL, NULL),
('CAN', 'V', 'Camarines Norte', NULL, NULL),
('CAP', 'VI', 'Capiz', NULL, NULL),
('CAS', 'V', 'Camarines Sur', NULL, NULL),
('CAT', 'V', 'Catanduanes', NULL, NULL),
('CAV', 'IV-A', 'Cavite', NULL, NULL),
('CEB', 'VII', 'Cebu', NULL, NULL),
('COM', 'XI', 'Compostela Valley', NULL, NULL),
('DAC', 'XI', 'Davao Occidental', NULL, NULL),
('DAO', 'XI', 'Davao Oriental', NULL, NULL),
('DAS', 'XI', 'Davao del Sur', NULL, NULL),
('DAV', 'XI', 'Davao del Norte', NULL, NULL),
('DIN', 'XIII', 'Dinagat Islands', NULL, NULL),
('EAS', 'VIII', 'Eastern Samar', NULL, NULL),
('GUI', 'VI', 'Guimaras', NULL, NULL),
('IFU', 'CAR', 'Ifugao', NULL, NULL),
('ILI', 'VI', 'Iloilo', NULL, NULL),
('ILN', 'I', 'Ilocos Norte', NULL, NULL),
('ILS', 'I', 'Ilocos Sur', NULL, NULL),
('ISA', 'II', 'Isabela', NULL, NULL),
('KAL', 'CAR', 'Kalinga', NULL, NULL),
('LAG', 'IV-A', 'Laguna', NULL, NULL),
('LAN', 'X', 'Lanao del Norte', NULL, NULL),
('LAS', 'ARMM', 'Lanao del Sur', NULL, NULL),
('LEY', 'VIII', 'Leyte', NULL, NULL),
('LUN', 'I', 'La Union', NULL, NULL),
('MAD', 'IV-B', 'Marinduque', NULL, NULL),
('MAG', 'ARMM', 'Maguindanao', NULL, NULL),
('MAS', 'V', 'Masbate', NULL, NULL),
('MDC', 'IV-B', 'Occidental Mindoro', NULL, NULL),
('MDR', 'IV-B', 'Oriental Mindoro', NULL, NULL),
('MM', 'NCR', 'Metro Manila', NULL, NULL),
('MOU', 'CAR', 'Mountain Province', NULL, NULL),
('MSC', 'X', 'Misamis Occidental', NULL, NULL),
('MSR', 'X', 'Misamis Oriental', NULL, NULL),
('NCO', 'XII', 'Cotabato', NULL, NULL),
('NEC', 'VI', 'Negros Occidental', NULL, NULL),
('NER', 'VII', 'Negros Oriental', NULL, NULL),
('NSA', 'VIII', 'Northern Samar', NULL, NULL),
('NUE', 'III', 'Nueva Ecija', NULL, NULL),
('NUV', 'II', 'Nueva Vizcaya', NULL, NULL),
('PAM', 'III', 'Pampanga', NULL, NULL),
('PAN', 'I', 'Pangasinan', NULL, NULL),
('PLW', 'IV-B', 'Palawan', NULL, NULL),
('QUE', 'IV-A', 'Quezon', NULL, NULL),
('QUI', 'II', 'Quirino', NULL, NULL),
('RIZ', 'IV-A', 'Rizal', NULL, NULL),
('ROM', 'IV-B', 'Romblon', NULL, NULL),
('SAR', 'XII', 'Sarangani', NULL, NULL),
('SCO', 'XII', 'South Cotabato', NULL, NULL),
('SIG', 'VII', 'Siquijor', NULL, NULL),
('SLE', 'VIII', 'Southern Leyte', NULL, NULL),
('SLU', 'ARMM', 'Sulu', NULL, NULL),
('SOR', 'V', 'Sorsogon', NULL, NULL),
('SUK', 'XII', 'Sultan Kudarat', NULL, NULL),
('SUN', 'XIII', 'Surigao del Norte', NULL, NULL),
('SUR', 'XIII', 'Surigao del Sur', NULL, NULL),
('TAR', 'III', 'Tarlac', NULL, NULL),
('TAW', 'ARMM', 'Tawi-tawi', NULL, NULL),
('WSA', 'VIII', 'Samar', NULL, NULL),
('ZAN', 'IX', 'Zamboanga del Norte', NULL, NULL),
('ZAS', 'IX', 'Zamboanga del Sur', NULL, NULL),
('ZMB', 'III', 'Zambales', NULL, NULL),
('ZSI', 'IX', 'Zamboanga Sibugay', NULL, NULL);
