INSERT INTO `location_cities` (`id`, `province_id`, `name`, `created_at`, `updated_at`) VALUES
(1, 'PLW', 'Aborlan', NULL, NULL),
(2, 'MDC', 'Abra de Ilog', NULL, NULL),
(3, 'BAN', 'Abucay', NULL, NULL),
(4, 'CAG', 'Abulug', NULL, NULL),
(5, 'LEY', 'Abuyog', NULL, NULL),
(6, 'ILN', 'Adams', NULL, NULL),
(7, 'QUE', 'Agdangan', NULL, NULL),
(8, 'QUI', 'Aglipay', NULL, NULL),
(9, 'PAN', 'Agno', NULL, NULL),
(10, 'BTG', 'Agoncillo', NULL, NULL),
(11, 'LUN', 'Agoo', NULL, NULL),
(12, 'PAN', 'Aguilar', NULL, NULL),
(13, 'IFU', 'Aguinaldo', NULL, NULL),
(14, 'PLW', 'Agutaya', NULL, NULL),
(15, 'ILI', 'Ajuy', NULL, NULL),
(16, 'BAS', 'Akbar', NULL, NULL),
(17, 'QUE', 'Alabat', NULL, NULL),
(18, 'SAR', 'Alabel', NULL, NULL),
(19, 'NCO', 'Alamada', NULL, NULL),
(20, 'PAN', 'Alaminos', NULL, NULL),
(21, 'LAG', 'Alaminos', NULL, NULL),
(22, 'LEY', 'Alangalang', NULL, NULL),
(23, 'BAS', 'Al-Barka', NULL, NULL),
(24, 'LEY', 'Albuera', NULL, NULL),
(25, 'BOH', 'Alburquerque', NULL, NULL),
(26, 'PAN', 'Alcala', NULL, NULL),
(27, 'CAG', 'Alcala', NULL, NULL),
(28, 'ROM', 'Alcantara', NULL, NULL),
(29, 'CEB', 'Alcantara', NULL, NULL),
(30, 'CEB', 'Alcoy', NULL, NULL),
(31, 'CEB', 'Alegria', NULL, NULL),
(32, 'SUN', 'Alegria', NULL, NULL),
(33, 'NCO', 'Aleosan', NULL, NULL),
(34, 'CAV', 'Alfonso', NULL, NULL),
(35, 'NUV', 'Alfonso Castaneda', NULL, NULL),
(36, 'IFU', 'Alfonso Lista', NULL, NULL),
(37, 'NUE', 'Aliaga', NULL, NULL),
(38, 'ISA', 'Alicia', NULL, NULL),
(39, 'BOH', 'Alicia', NULL, NULL),
(40, 'ZSI', 'Alicia', NULL, NULL),
(41, 'ILS', 'Alilem', NULL, NULL),
(42, 'ILI', 'Alimodian', NULL, NULL),
(43, 'BTG', 'Alitagtag', NULL, NULL),
(44, 'CAG', 'Allacapan', NULL, NULL),
(45, 'NSA', 'Allen', NULL, NULL),
(46, 'WSA', 'Almagro', NULL, NULL),
(47, 'BIL', 'Almeria', NULL, NULL),
(48, 'CEB', 'Aloguinsan', NULL, NULL),
(49, 'MSC', 'Aloran', NULL, NULL),
(50, 'AKL', 'Altavas', NULL, NULL),
(51, 'MSR', 'Alubijid', NULL, NULL),
(52, 'CAV', 'Amadeo', NULL, NULL),
(53, 'NUV', 'Ambaguio', NULL, NULL),
(54, 'NER', 'Amlan', NULL, NULL),
(55, 'MAG', 'Ampatuan', NULL, NULL),
(56, 'CAG', 'Amulung', NULL, NULL),
(57, 'SLE', 'Anahawan', NULL, NULL),
(58, 'TAR', 'Anao', NULL, NULL),
(59, 'PAN', 'Anda', NULL, NULL),
(60, 'BOH', 'Anda', NULL, NULL),
(61, 'ISA', 'Angadanan', NULL, NULL),
(62, 'BUL', 'Angat', NULL, NULL),
(63, 'PAM', 'Angeles', NULL, NULL),
(64, 'RIZ', 'Angono', NULL, NULL),
(65, 'ILI', 'Anilao', NULL, NULL),
(66, 'ANT', 'Anini-y', NULL, NULL),
(67, 'BOH', 'Antequera', NULL, NULL),
(68, 'NCO', 'Antipas', NULL, NULL),
(69, 'RIZ', 'Antipolo', NULL, NULL),
(70, 'PAM', 'Apalit', NULL, NULL),
(71, 'CAG', 'Aparri', NULL, NULL),
(72, 'PLW', 'Araceli', NULL, NULL),
(73, 'NCO', 'Arakan', NULL, NULL),
(74, 'PAM', 'Arayat', NULL, NULL),
(75, 'CEB', 'Argao', NULL, NULL),
(76, 'LUN', 'Aringay', NULL, NULL),
(77, 'NUV', 'Aritao', NULL, NULL),
(78, 'MAS', 'Aroroy', NULL, NULL),
(79, 'EAS', 'Arteche', NULL, NULL),
(80, 'PAN', 'Asingan', NULL, NULL),
(81, 'IFU', 'Asipulo', NULL, NULL),
(82, 'CEB', 'Asturias', NULL, NULL),
(83, 'DAV', 'Asuncion', NULL, NULL),
(84, 'QUE', 'Atimonan', NULL, NULL),
(85, 'BEN', 'Atok', NULL, NULL),
(86, 'ISA', 'Aurora', NULL, NULL),
(87, 'ZAS', 'Aurora', NULL, NULL),
(88, 'NER', 'Ayungon', NULL, NULL),
(89, 'CAS', 'Baao', NULL, NULL),
(90, 'LEY', 'Babatngon', NULL, NULL),
(91, 'ALB', 'Bacacay', NULL, NULL),
(92, 'ILN', 'Bacarra', NULL, NULL),
(93, 'BOH', 'Baclayon', NULL, NULL),
(94, 'LUN', 'Bacnotan', NULL, NULL),
(95, 'MDR', 'Baco', NULL, NULL),
(96, 'NEC', 'Bacolod', NULL, NULL),
(97, 'LAN', 'Bacolod', NULL, NULL),
(98, 'LAS', 'Bacolod-Kalawi', NULL, NULL),
(99, 'PAM', 'Bacolor', NULL, NULL),
(100, 'NER', 'Bacong', NULL, NULL),
(101, 'CAV', 'Bacoor', NULL, NULL),
(102, 'SUN', 'Bacuag', NULL, NULL),
(103, 'CEB', 'Badian', NULL, NULL),
(104, 'ILI', 'Badiangan', NULL, NULL),
(105, 'ILN', 'Badoc', NULL, NULL),
(106, 'NUV', 'Bagabag', NULL, NULL),
(107, 'BAN', 'Bagac', NULL, NULL),
(108, 'CAT', 'Bagamanoc', NULL, NULL),
(109, 'DAO', 'Baganga', NULL, NULL),
(110, 'CAG', 'Baggao', NULL, NULL),
(111, 'NEC', 'Bago', NULL, NULL),
(112, 'BEN', 'Baguio', NULL, NULL),
(113, 'LUN', 'Bagulin', NULL, NULL),
(114, 'SUK', 'Bagumbayan', NULL, NULL),
(115, 'NER', 'Bais', NULL, NULL),
(116, 'BEN', 'Bakun', NULL, NULL),
(117, 'PLW', 'Balabac', NULL, NULL),
(118, 'LAS', 'Balabagan', NULL, NULL),
(119, 'BUL', 'Balagtas', NULL, NULL),
(120, 'CEB', 'Balamban', NULL, NULL),
(121, 'BAN', 'Balanga', NULL, NULL),
(122, 'EAS', 'Balangiga', NULL, NULL),
(123, 'EAS', 'Balangkayan', NULL, NULL),
(124, 'LUN', 'Balaoan', NULL, NULL),
(125, 'ILI', 'Balasan', NULL, NULL),
(126, 'CAS', 'Balatan', NULL, NULL),
(127, 'BTG', 'Balayan', NULL, NULL),
(128, 'KAL', 'Balbalan', NULL, NULL),
(129, 'MAS', 'Baleno', NULL, NULL),
(130, 'AUR', 'Baler', NULL, NULL),
(131, 'BTG', 'Balete', NULL, NULL),
(132, 'AKL', 'Balete', NULL, NULL),
(133, 'MSC', 'Baliangao', NULL, NULL),
(134, 'ZAN', 'Baliguian', NULL, NULL),
(135, 'BOH', 'Balilihan', NULL, NULL),
(136, 'LAS', 'Balindong', NULL, NULL),
(137, 'MSR', 'Balingasag', NULL, NULL),
(138, 'MSR', 'Balingoan', NULL, NULL),
(139, 'BUL', 'Baliuag', NULL, NULL),
(140, 'CAG', 'Ballesteros', NULL, NULL),
(141, 'LAN', 'Baloi', NULL, NULL),
(142, 'MAS', 'Balud', NULL, NULL),
(143, 'PAN', 'Balungao', NULL, NULL),
(144, 'TAR', 'Bamban', NULL, NULL),
(145, 'NUV', 'Bambang', NULL, NULL),
(146, 'ILI', 'Banate', NULL, NULL),
(147, 'IFU', 'Banaue', NULL, NULL),
(148, 'DAO', 'Banaybanay', NULL, NULL),
(149, 'ILS', 'Banayoyo', NULL, NULL),
(150, 'AKL', 'Banga', NULL, NULL),
(151, 'SCO', 'Banga', NULL, NULL),
(152, 'LUN', 'Bangar', NULL, NULL),
(153, 'ABR', 'Bangued', NULL, NULL),
(154, 'ILN', 'Bangui', NULL, NULL),
(155, 'SLU', 'Banguingui', NULL, NULL),
(156, 'PAN', 'Bani', NULL, NULL),
(157, 'NCO', 'Banisilan', NULL, NULL),
(158, 'ILN', 'Banna', NULL, NULL),
(159, 'DAS', 'Bansalan', NULL, NULL),
(160, 'MDR', 'Bansud', NULL, NULL),
(161, 'ILS', 'Bantay', NULL, NULL),
(162, 'CEB', 'Bantayan', NULL, NULL),
(163, 'ROM', 'Banton', NULL, NULL),
(164, 'RIZ', 'Baras', NULL, NULL),
(165, 'CAT', 'Baras', NULL, NULL),
(166, 'ANT', 'Barbaza', NULL, NULL),
(167, 'SOR', 'Barcelona', NULL, NULL),
(168, 'CEB', 'Barili', NULL, NULL),
(169, 'MAG', 'Barira', NULL, NULL),
(170, 'MOU', 'Barlig', NULL, NULL),
(171, 'SUR', 'Barobo', NULL, NULL),
(172, 'ILI', 'Barotac Nuevo', NULL, NULL),
(173, 'ILI', 'Barotac Viejo', NULL, NULL),
(174, 'LAN', 'Baroy', NULL, NULL),
(175, 'LEY', 'Barugo', NULL, NULL),
(176, 'NER', 'Basay', NULL, NULL),
(177, 'BTN', 'Basco', NULL, NULL),
(178, 'WSA', 'Basey', NULL, NULL),
(179, 'DIN', 'Basilisa', NULL, NULL),
(180, 'PAN', 'Basista', NULL, NULL),
(181, 'CAN', 'Basud', NULL, NULL),
(182, 'ILN', 'Batac', NULL, NULL),
(183, 'ILI', 'Batad', NULL, NULL),
(184, 'AKL', 'Batan', NULL, NULL),
(185, 'BTG', 'Batangas', NULL, NULL),
(186, 'PLW', 'Bataraza', NULL, NULL),
(187, 'CAS', 'Bato', NULL, NULL),
(188, 'CAT', 'Bato', NULL, NULL),
(189, 'LEY', 'Bato', NULL, NULL),
(190, 'MAS', 'Batuan', NULL, NULL),
(191, 'BOH', 'Batuan', NULL, NULL),
(192, 'BTG', 'Bauan', NULL, NULL),
(193, 'LUN', 'Bauang', NULL, NULL),
(194, 'MOU', 'Bauko', NULL, NULL),
(195, 'BUK', 'Baungon', NULL, NULL),
(196, 'PAN', 'Bautista', NULL, NULL),
(197, 'LAG', 'Bay', NULL, NULL),
(198, 'SUR', 'Bayabas', NULL, NULL),
(199, 'PAN', 'Bayambang', NULL, NULL),
(200, 'LAS', 'Bayang', NULL, NULL),
(201, 'NER', 'Bayawan', NULL, NULL),
(202, 'LEY', 'Baybay', NULL, NULL),
(203, 'ZAS', 'Bayog', NULL, NULL),
(204, 'NUV', 'Bayombong', NULL, NULL),
(205, 'AGS', 'Bayugan', NULL, NULL),
(206, 'ANT', 'Belison', NULL, NULL),
(207, 'ISA', 'Benito Soliven', NULL, NULL),
(208, 'MOU', 'Besao', NULL, NULL),
(209, 'BOH', 'Bien Unido', NULL, NULL),
(210, 'BOH', 'Bilar', NULL, NULL),
(211, 'BIL', 'Biliran', NULL, NULL),
(212, 'NEC', 'Binalbagan', NULL, NULL),
(213, 'PAN', 'Binalonan', NULL, NULL),
(214, 'LAG', 'Biñan', NULL, NULL),
(215, 'RIZ', 'Binangonan', NULL, NULL),
(216, 'NER', 'Bindoy', NULL, NULL),
(217, 'ILI', 'Bingawan', NULL, NULL),
(218, 'LAS', 'Binidayan', NULL, NULL),
(219, 'PAN', 'Binmaley', NULL, NULL),
(220, 'MSR', 'Binuangan', NULL, NULL),
(221, 'NSA', 'Biri', NULL, NULL),
(222, 'SUR', 'Bislig', NULL, NULL),
(223, 'MAD', 'Boac', NULL, NULL),
(224, 'NSA', 'Bobon', NULL, NULL),
(225, 'BUL', 'Bocaue', NULL, NULL),
(226, 'CEB', 'Bogo', NULL, NULL),
(227, 'BEN', 'Bokod', NULL, NULL),
(228, 'PAN', 'Bolinao', NULL, NULL),
(229, 'ABR', 'Boliney', NULL, NULL),
(230, 'CEB', 'Boljoon', NULL, NULL),
(231, 'CAS', 'Bombon', NULL, NULL),
(232, 'NUE', 'Bongabon', NULL, NULL),
(233, 'MDR', 'Bongabong', NULL, NULL),
(234, 'TAW', 'Bongao', NULL, NULL),
(235, 'MSC', 'Bonifacio', NULL, NULL),
(236, 'MOU', 'Bontoc', NULL, NULL),
(237, 'SLE', 'Bontoc', NULL, NULL),
(238, 'CEB', 'Borbon', NULL, NULL),
(239, 'EAS', 'Borongan', NULL, NULL),
(240, 'DAO', 'Boston', NULL, NULL),
(241, 'ZMB', 'Botolan', NULL, NULL),
(242, 'DAV', 'Braulio E. Dujali', NULL, NULL),
(243, 'PLW', 'Brooke\'s Point', NULL, NULL),
(244, 'LAS', 'Buadiposo-Buntong', NULL, NULL),
(245, 'LAS', 'Bubong', NULL, NULL),
(246, 'ABR', 'Bucay', NULL, NULL),
(247, 'ABR', 'Bucloc', NULL, NULL),
(248, 'QUE', 'Buenavista', NULL, NULL),
(249, 'MAD', 'Buenavista', NULL, NULL),
(250, 'GUI', 'Buenavista', NULL, NULL),
(251, 'BOH', 'Buenavista', NULL, NULL),
(252, 'AGN', 'Buenavista', NULL, NULL),
(253, 'PAN', 'Bugallon', NULL, NULL),
(254, 'ANT', 'Bugasong', NULL, NULL),
(255, 'CAG', 'Buguey', NULL, NULL),
(256, 'BEN', 'Buguias', NULL, NULL),
(257, 'CAS', 'Buhi', NULL, NULL),
(258, 'CAS', 'Bula', NULL, NULL),
(259, 'BUL', 'Bulakan', NULL, NULL),
(260, 'MDR', 'Bulalacao', NULL, NULL),
(261, 'SOR', 'Bulan', NULL, NULL),
(262, 'MAG', 'Buldon', NULL, NULL),
(263, 'MAG', 'Buluan', NULL, NULL),
(264, 'SOR', 'Bulusan', NULL, NULL),
(265, 'LAS', 'Bumbaran', NULL, NULL),
(266, 'AGS', 'Bunawan', NULL, NULL),
(267, 'LEY', 'Burauen', NULL, NULL),
(268, 'QUE', 'Burdeos', NULL, NULL),
(269, 'ILN', 'Burgos', NULL, NULL),
(270, 'ILS', 'Burgos', NULL, NULL),
(271, 'LUN', 'Burgos', NULL, NULL),
(272, 'PAN', 'Burgos', NULL, NULL),
(273, 'ISA', 'Burgos', NULL, NULL),
(274, 'SUN', 'Burgos', NULL, NULL),
(275, 'AKL', 'Buruanga', NULL, NULL),
(276, 'BUL', 'Bustos', NULL, NULL),
(277, 'PLW', 'Busuanga', NULL, NULL),
(278, 'LAS', 'Butig', NULL, NULL),
(279, 'AGN', 'Butuan', NULL, NULL),
(280, 'ZSI', 'Buug', NULL, NULL),
(281, 'LUN', 'Caba', NULL, NULL),
(282, 'AGN', 'Cabadbaran', NULL, NULL),
(283, 'ISA', 'Cabagan', NULL, NULL),
(284, 'NUE', 'Cabanatuan', NULL, NULL),
(285, 'ZMB', 'Cabangan', NULL, NULL),
(286, 'BUK', 'Cabanglasan', NULL, NULL),
(287, 'QUI', 'Cabarroguis', NULL, NULL),
(288, 'ISA', 'Cabatuan', NULL, NULL),
(289, 'ILI', 'Cabatuan', NULL, NULL),
(290, 'NUE', 'Cabiao', NULL, NULL),
(291, 'BIL', 'Cabucgayan', NULL, NULL),
(292, 'ILS', 'Cabugao', NULL, NULL),
(293, 'CAS', 'Cabusao', NULL, NULL),
(294, 'LAG', 'Cabuyao', NULL, NULL),
(295, 'NEC', 'Cadiz', NULL, NULL),
(296, 'MSR', 'Cagayan de Oro', NULL, NULL),
(297, 'PLW', 'Cagayancillo', NULL, NULL),
(298, 'DIN', 'Cagdianao', NULL, NULL),
(299, 'SUR', 'Cagwait', NULL, NULL),
(300, 'BIL', 'Caibiran', NULL, NULL),
(301, 'RIZ', 'Cainta', NULL, NULL),
(302, 'ROM', 'Cajidiocan', NULL, NULL),
(303, 'CAS', 'Calabanga', NULL, NULL),
(304, 'BTG', 'Calaca', NULL, NULL),
(305, 'LAG', 'Calamba', NULL, NULL),
(306, 'MSC', 'Calamba', NULL, NULL),
(307, 'APA', 'Calanasan', NULL, NULL),
(308, 'LAS', 'Calanogas', NULL, NULL),
(309, 'MDR', 'Calapan', NULL, NULL),
(310, 'BOH', 'Calape', NULL, NULL),
(311, 'PAN', 'Calasiao', NULL, NULL),
(312, 'BTG', 'Calatagan', NULL, NULL),
(313, 'ROM', 'Calatrava', NULL, NULL),
(314, 'NEC', 'Calatrava', NULL, NULL),
(315, 'QUE', 'Calauag', NULL, NULL),
(316, 'LAG', 'Calauan', NULL, NULL),
(317, 'CAG', 'Calayan', NULL, NULL),
(318, 'WSA', 'Calbayog', NULL, NULL),
(319, 'WSA', 'Calbiga', NULL, NULL),
(320, 'ILI', 'Calinog', NULL, NULL),
(321, 'MDC', 'Calintaan', NULL, NULL),
(322, 'MM', 'Caloocan', NULL, NULL),
(323, 'LEY', 'Calubian', NULL, NULL),
(324, 'BUL', 'Calumpit', NULL, NULL),
(325, 'ANT', 'Caluya', NULL, NULL),
(326, 'CAG', 'Camalaniugan', NULL, NULL),
(327, 'ALB', 'Camalig', NULL, NULL),
(328, 'CAS', 'Camaligan', NULL, NULL),
(329, 'TAR', 'Camiling', NULL, NULL),
(330, 'CAS', 'Canaman', NULL, NULL),
(331, 'EAS', 'Can-avid', NULL, NULL),
(332, 'PAM', 'Candaba', NULL, NULL),
(333, 'ZMB', 'Candelaria', NULL, NULL),
(334, 'QUE', 'Candelaria', NULL, NULL),
(335, 'BOH', 'Candijay', NULL, NULL),
(336, 'ILS', 'Candon', NULL, NULL),
(337, 'NEC', 'Candoni', NULL, NULL),
(338, 'NER', 'Canlaon', NULL, NULL),
(339, 'SUR', 'Cantilan', NULL, NULL),
(340, 'ILS', 'Caoayan', NULL, NULL),
(341, 'CAN', 'Capalonga', NULL, NULL),
(342, 'TAR', 'Capas', NULL, NULL),
(343, 'LEY', 'Capoocan', NULL, NULL),
(344, 'NSA', 'Capul', NULL, NULL),
(345, 'DAO', 'Caraga', NULL, NULL),
(346, 'CAS', 'Caramoan', NULL, NULL),
(347, 'CAT', 'Caramoran', NULL, NULL),
(348, 'ILN', 'Carasi', NULL, NULL),
(349, 'CEB', 'Carcar', NULL, NULL),
(350, 'RIZ', 'Cardona', NULL, NULL),
(351, 'LEY', 'Carigara', NULL, NULL),
(352, 'ILI', 'Carles', NULL, NULL),
(353, 'BOH', 'Carmen', NULL, NULL),
(354, 'CEB', 'Carmen', NULL, NULL),
(355, 'DAV', 'Carmen', NULL, NULL),
(356, 'NCO', 'Carmen', NULL, NULL),
(357, 'AGN', 'Carmen', NULL, NULL),
(358, 'SUR', 'Carmen', NULL, NULL),
(359, 'CAV', 'Carmona', NULL, NULL),
(360, 'NUE', 'Carranglan', NULL, NULL),
(361, 'SUR', 'Carrascal', NULL, NULL),
(362, 'AUR', 'Casiguran', NULL, NULL),
(363, 'SOR', 'Casiguran', NULL, NULL),
(364, 'SOR', 'Castilla', NULL, NULL),
(365, 'ZMB', 'Castillejos', NULL, NULL),
(366, 'MAS', 'Cataingan', NULL, NULL),
(367, 'QUE', 'Catanauan', NULL, NULL),
(368, 'NSA', 'Catarman', NULL, NULL),
(369, 'CAM', 'Catarman', NULL, NULL),
(370, 'WSA', 'Catbalogan', NULL, NULL),
(371, 'DAO', 'Cateel', NULL, NULL),
(372, 'BOH', 'Catigbian', NULL, NULL),
(373, 'CEB', 'Catmon', NULL, NULL),
(374, 'NSA', 'Catubig', NULL, NULL),
(375, 'ISA', 'Cauayan', NULL, NULL),
(376, 'NEC', 'Cauayan', NULL, NULL),
(377, 'LAG', 'Cavinti', NULL, NULL),
(378, 'CAV', 'Cavite', NULL, NULL),
(379, 'MAS', 'Cawayan', NULL, NULL),
(380, 'CEB', 'Cebu', NULL, NULL),
(381, 'ILS', 'Cervantes', NULL, NULL),
(382, 'BOH', 'Clarin', NULL, NULL),
(383, 'MSC', 'Clarin', NULL, NULL),
(384, 'SUN', 'Claver', NULL, NULL),
(385, 'CAG', 'Claveria', NULL, NULL),
(386, 'MAS', 'Claveria', NULL, NULL),
(387, 'MSR', 'Claveria', NULL, NULL),
(388, 'SUK', 'Columbio', NULL, NULL),
(389, 'CEB', 'Compostela', NULL, NULL),
(390, 'COM', 'Compostela', NULL, NULL),
(391, 'TAR', 'Concepcion', NULL, NULL),
(392, 'ROM', 'Concepcion', NULL, NULL),
(393, 'ILI', 'Concepcion', NULL, NULL),
(394, 'MSC', 'Concepcion', NULL, NULL),
(395, 'APA', 'Conner', NULL, NULL),
(396, 'CEB', 'Consolacion', NULL, NULL),
(397, 'ROM', 'Corcuera', NULL, NULL),
(398, 'CEB', 'Cordoba', NULL, NULL),
(399, 'ISA', 'Cordon', NULL, NULL),
(400, 'BOH', 'Corella', NULL, NULL),
(401, 'PLW', 'Coron', NULL, NULL),
(402, 'BOH', 'Cortes', NULL, NULL),
(403, 'SUR', 'Cortes', NULL, NULL),
(404, 'MAG', 'Cotabato', NULL, NULL),
(405, 'CAP', 'Cuartero', NULL, NULL),
(406, 'BTG', 'Cuenca', NULL, NULL),
(407, 'BIL', 'Culaba', NULL, NULL),
(408, 'ANT', 'Culasi', NULL, NULL),
(409, 'PLW', 'Culion', NULL, NULL),
(410, 'ILN', 'Currimao', NULL, NULL),
(411, 'NUE', 'Cuyapo', NULL, NULL),
(412, 'PLW', 'Cuyo', NULL, NULL),
(413, 'CEB', 'Daanbantayan', NULL, NULL),
(414, 'CAN', 'Daet', NULL, NULL),
(415, 'LEY', 'Dagami', NULL, NULL),
(416, 'BOH', 'Dagohoy', NULL, NULL),
(417, 'ABR', 'Daguioman', NULL, NULL),
(418, 'PAN', 'Dagupan', NULL, NULL),
(419, 'CEB', 'Dalaguete', NULL, NULL),
(420, 'BUK', 'Damulog', NULL, NULL),
(421, 'BOH', 'Danao', NULL, NULL),
(422, 'CEB', 'Danao', NULL, NULL),
(423, 'BUK', 'Dangcagan', NULL, NULL),
(424, 'ABR', 'Danglas', NULL, NULL),
(425, 'CAP', 'Dao', NULL, NULL),
(426, 'SUN', 'Dapa', NULL, NULL),
(427, 'ZAN', 'Dapitan', NULL, NULL),
(428, 'ALB', 'Daraga', NULL, NULL),
(429, 'WSA', 'Daram', NULL, NULL),
(430, 'CAV', 'Dasmariñas', NULL, NULL),
(431, 'PAN', 'Dasol', NULL, NULL),
(432, 'MAG', 'Datu Abdullah Sangki', NULL, NULL),
(433, 'MAG', 'Datu Anggal Midtimbang', NULL, NULL),
(434, 'MAG', 'Datu Blah T. Sinsuat', NULL, NULL),
(435, 'MAG', 'Datu Hoffer Ampatuan', NULL, NULL),
(436, 'MAG', 'Datu Montawal', NULL, NULL),
(437, 'MAG', 'Datu Odin Sinsuat', NULL, NULL),
(438, 'MAG', 'Datu Paglas', NULL, NULL),
(439, 'MAG', 'Datu Piang', NULL, NULL),
(440, 'MAG', 'Datu Salibo', NULL, NULL),
(441, 'MAG', 'Datu Saudi-Ampatuan', NULL, NULL),
(442, 'MAG', 'Datu Unsay', NULL, NULL),
(443, 'NER', 'Dauin', NULL, NULL),
(444, 'BOH', 'Dauis', NULL, NULL),
(445, 'DAS', 'Davao', NULL, NULL),
(446, 'SUN', 'Del Carmen', NULL, NULL),
(447, 'CAS', 'Del Gallego', NULL, NULL),
(448, 'ISA', 'Delfin Albano', NULL, NULL),
(449, 'NUV', 'Diadi', NULL, NULL),
(450, 'QUI', 'Diffun', NULL, NULL),
(451, 'DAS', 'Digos', NULL, NULL),
(452, 'AUR', 'Dilasag', NULL, NULL),
(453, 'MAS', 'Dimasalang', NULL, NULL),
(454, 'ZAS', 'Dimataling', NULL, NULL),
(455, 'BOH', 'Dimiao', NULL, NULL),
(456, 'DIN', 'Dinagat', NULL, NULL),
(457, 'AUR', 'Dinalungan', NULL, NULL),
(458, 'BAN', 'Dinalupihan', NULL, NULL),
(459, 'ISA', 'Dinapigue', NULL, NULL),
(460, 'ZAS', 'Dinas', NULL, NULL),
(461, 'AUR', 'Dingalan', NULL, NULL),
(462, 'ILI', 'Dingle', NULL, NULL),
(463, 'ILN', 'Dingras', NULL, NULL),
(464, 'AUR', 'Dipaculao', NULL, NULL),
(465, 'ZSI', 'Diplahan', NULL, NULL),
(466, 'ZAN', 'Dipolog', NULL, NULL),
(467, 'LAS', 'Ditsaan-Ramain', NULL, NULL),
(468, 'ISA', 'Divilacan', NULL, NULL),
(469, 'ABR', 'Dolores', NULL, NULL),
(470, 'QUE', 'Dolores', NULL, NULL),
(471, 'EAS', 'Dolores', NULL, NULL),
(472, 'BUK', 'Don Carlos', NULL, NULL),
(473, 'DAC', 'Don Marcelino', NULL, NULL),
(474, 'MSC', 'Don Victoriano Chiongbian', NULL, NULL),
(475, 'BUL', 'Doña Remedios Trinidad', NULL, NULL),
(476, 'SOR', 'Donsol', NULL, NULL),
(477, 'ILI', 'Dueñas', NULL, NULL),
(478, 'BOH', 'Duero', NULL, NULL),
(479, 'LEY', 'Dulag', NULL, NULL),
(480, 'NER', 'Dumaguete', NULL, NULL),
(481, 'CAP', 'Dumalag', NULL, NULL),
(482, 'ZAS', 'Dumalinao', NULL, NULL),
(483, 'ILN', 'Dumalneg', NULL, NULL),
(484, 'ILI', 'Dumangas', NULL, NULL),
(485, 'CEB', 'Dumanjug', NULL, NULL),
(486, 'PLW', 'Dumaran', NULL, NULL),
(487, 'CAP', 'Dumarao', NULL, NULL),
(488, 'ZAS', 'Dumingag', NULL, NULL),
(489, 'NUV', 'Dupax del Norte', NULL, NULL),
(490, 'NUV', 'Dupax del Sur', NULL, NULL),
(491, 'ISA', 'Echague', NULL, NULL),
(492, 'PLW', 'El Nido', NULL, NULL),
(493, 'MSR', 'El Salvador', NULL, NULL),
(494, 'CAG', 'Enrile', NULL, NULL),
(495, 'NEC', 'Enrique B. Magalona', NULL, NULL),
(496, 'SIG', 'Enrique Villanueva', NULL, NULL),
(497, 'NEC', 'Escalante', NULL, NULL),
(498, 'MAS', 'Esperanza', NULL, NULL),
(499, 'SUK', 'Esperanza', NULL, NULL),
(500, 'AGS', 'Esperanza', NULL, NULL),
(501, 'ILI', 'Estancia', NULL, NULL),
(502, 'LAG', 'Famy', NULL, NULL),
(503, 'ROM', 'Ferrol', NULL, NULL),
(504, 'APA', 'Flora', NULL, NULL),
(505, 'PAM', 'Floridablanca', NULL, NULL),
(506, 'NUE', 'Gabaldon', NULL, NULL),
(507, 'CAS', 'Gainza', NULL, NULL),
(508, 'ILS', 'Galimuyod', NULL, NULL),
(509, 'NSA', 'Gamay', NULL, NULL),
(510, 'ISA', 'Gamu', NULL, NULL),
(511, 'LAS', 'Ganassi', NULL, NULL),
(512, 'WSA', 'Gandara', NULL, NULL),
(513, 'NUE', 'Gapan', NULL, NULL),
(514, 'CAS', 'Garchitorena', NULL, NULL),
(515, 'BOH', 'Garcia Hernandez', NULL, NULL),
(516, 'MAD', 'Gasan', NULL, NULL),
(517, 'CAG', 'Gattaran', NULL, NULL),
(518, 'CAV', 'General Emilio Aguinaldo', NULL, NULL),
(519, 'QUE', 'General Luna', NULL, NULL),
(520, 'SUN', 'General Luna', NULL, NULL),
(521, 'EAS', 'General MacArthur', NULL, NULL),
(522, 'NUE', 'General Mamerto Natividad', NULL, NULL),
(523, 'CAV', 'General Mariano Alvarez', NULL, NULL),
(524, 'QUE', 'General Nakar', NULL, NULL),
(525, 'MAG', 'General Salipada K. Pendatun', NULL, NULL),
(526, 'SCO', 'General Santos', NULL, NULL),
(527, 'NUE', 'General Tinio', NULL, NULL),
(528, 'CAV', 'General Trias', NULL, NULL),
(529, 'TAR', 'Gerona', NULL, NULL),
(530, 'BOH', 'Getafe', NULL, NULL),
(531, 'SUN', 'Gigaquit', NULL, NULL),
(532, 'CAT', 'Gigmoto', NULL, NULL),
(533, 'CEB', 'Ginatilan', NULL, NULL),
(534, 'MSR', 'Gingoog', NULL, NULL),
(535, 'EAS', 'Giporlos', NULL, NULL),
(536, 'MSR', 'Gitagum', NULL, NULL),
(537, 'SAR', 'Glan', NULL, NULL),
(538, 'MDR', 'Gloria', NULL, NULL),
(539, 'CAS', 'Goa', NULL, NULL),
(540, 'ZAN', 'Godod', NULL, NULL),
(541, 'CAG', 'Gonzaga', NULL, NULL),
(542, 'DAO', 'Governor Generoso', NULL, NULL),
(543, 'ILS', 'Gregorio Del Pilar', NULL, NULL),
(544, 'PAM', 'Guagua', NULL, NULL),
(545, 'SOR', 'Gubat', NULL, NULL),
(546, 'BUL', 'Guiguinto', NULL, NULL),
(547, 'NER', 'Guihulngan', NULL, NULL),
(548, 'NUE', 'Guimba', NULL, NULL),
(549, 'ILI', 'Guimbal', NULL, NULL),
(550, 'QUE', 'Guinayangan', NULL, NULL),
(551, 'BOH', 'Guindulman', NULL, NULL),
(552, 'MAG', 'Guindulungan', NULL, NULL),
(553, 'ALB', 'Guinobatan', NULL, NULL),
(554, 'CAM', 'Guinsiliban', NULL, NULL),
(555, 'ZAS', 'Guipos', NULL, NULL),
(556, 'EAS', 'Guiuan', NULL, NULL),
(557, 'QUE', 'Gumaca', NULL, NULL),
(558, 'ZAN', 'Gutalac', NULL, NULL),
(559, 'BAS', 'Hadji Mohammad Ajul', NULL, NULL),
(560, 'BAS', 'Hadji Muhtamad', NULL, NULL),
(561, 'SLU', 'Hadji Panglima Tahil', NULL, NULL),
(562, 'BUL', 'Hagonoy', NULL, NULL),
(563, 'DAS', 'Hagonoy', NULL, NULL),
(564, 'ANT', 'Hamtic', NULL, NULL),
(565, 'BAN', 'Hermosa', NULL, NULL),
(566, 'EAS', 'Hernani', NULL, NULL),
(567, 'LEY', 'Hilongos', NULL, NULL),
(568, 'NEC', 'Himamaylan', NULL, NULL),
(569, 'WSA', 'Hinabangan', NULL, NULL),
(570, 'SUR', 'Hinatuan', NULL, NULL),
(571, 'LEY', 'Hindang', NULL, NULL),
(572, 'IFU', 'Hingyon', NULL, NULL),
(573, 'NEC', 'Hinigaran', NULL, NULL),
(574, 'NEC', 'Hinoba-an', NULL, NULL),
(575, 'SLE', 'Hinunangan', NULL, NULL),
(576, 'SLE', 'Hinundayan', NULL, NULL),
(577, 'IFU', 'Hungduan', NULL, NULL),
(578, 'ZMB', 'Iba', NULL, NULL),
(579, 'BTG', 'Ibaan', NULL, NULL),
(580, 'AKL', 'Ibajay', NULL, NULL),
(581, 'ILI', 'Igbaras', NULL, NULL),
(582, 'CAG', 'Iguig', NULL, NULL),
(583, 'ISA', 'Ilagan', NULL, NULL),
(584, 'LAN', 'Iligan', NULL, NULL),
(585, 'NEC', 'Ilog', NULL, NULL),
(586, 'ILI', 'Iloilo', NULL, NULL),
(587, 'ZSI', 'Imelda', NULL, NULL),
(588, 'BUK', 'Impasugong', NULL, NULL),
(589, 'CAV', 'Imus', NULL, NULL),
(590, 'BOH', 'Inabanga', NULL, NULL),
(591, 'SLU', 'Indanan', NULL, NULL),
(592, 'CAV', 'Indang', NULL, NULL),
(593, 'PAN', 'Infanta', NULL, NULL),
(594, 'QUE', 'Infanta', NULL, NULL),
(595, 'MSR', 'Initao', NULL, NULL),
(596, 'LEY', 'Inopacan', NULL, NULL),
(597, 'ZSI', 'Ipil', NULL, NULL),
(598, 'CAS', 'Iriga', NULL, NULL),
(599, 'SOR', 'Irosin', NULL, NULL),
(600, 'LEY', 'Isabel', NULL, NULL),
(601, 'NEC', 'Isabela', NULL, NULL),
(602, 'BAS', 'Isabela', NULL, NULL),
(603, 'SUK', 'Isulan', NULL, NULL),
(604, 'BTN', 'Itbayat', NULL, NULL),
(605, 'BEN', 'Itogon', NULL, NULL),
(606, 'BTN', 'Ivana', NULL, NULL),
(607, 'CAP', 'Ivisan', NULL, NULL),
(608, 'AGN', 'Jabonga', NULL, NULL),
(609, 'NUE', 'Jaen', NULL, NULL),
(610, 'BOH', 'Jagna', NULL, NULL),
(611, 'RIZ', 'Jalajala', NULL, NULL),
(612, 'CAP', 'Jamindan', NULL, NULL),
(613, 'ILI', 'Janiuay', NULL, NULL),
(614, 'LEY', 'Jaro', NULL, NULL),
(615, 'MSR', 'Jasaan', NULL, NULL),
(616, 'LEY', 'Javier', NULL, NULL),
(617, 'WSA', 'Jiabong', NULL, NULL),
(618, 'NER', 'Jimalalud', NULL, NULL),
(619, 'MSC', 'Jimenez', NULL, NULL),
(620, 'EAS', 'Jipapad', NULL, NULL),
(621, 'SLU', 'Jolo', NULL, NULL),
(622, 'QUE', 'Jomalig', NULL, NULL),
(623, 'ISA', 'Jones', NULL, NULL),
(624, 'GUI', 'Jordan', NULL, NULL),
(625, 'DAC', 'Jose Abad Santos', NULL, NULL),
(626, 'ZAN', 'Jose Dalman', NULL, NULL),
(627, 'CAN', 'Jose Panganiban', NULL, NULL),
(628, 'ZAS', 'Josefina', NULL, NULL),
(629, 'ALB', 'Jovellar', NULL, NULL),
(630, 'SOR', 'Juban', NULL, NULL),
(631, 'LEY', 'Julita', NULL, NULL),
(632, 'NCO', 'Kabacan', NULL, NULL),
(633, 'NEC', 'Kabankalan', NULL, NULL),
(634, 'ZSI', 'Kabasalan', NULL, NULL),
(635, 'BEN', 'Kabayan', NULL, NULL),
(636, 'APA', 'Kabugao', NULL, NULL),
(637, 'MAG', 'Kabuntalan', NULL, NULL),
(638, 'BUK', 'Kadingilan', NULL, NULL),
(639, 'SUK', 'Kalamansig', NULL, NULL),
(640, 'ZAN', 'Kalawit', NULL, NULL),
(641, 'LAG', 'Kalayaan', NULL, NULL),
(642, 'PLW', 'Kalayaan', NULL, NULL),
(643, 'AKL', 'Kalibo', NULL, NULL),
(644, 'BUK', 'Kalilangan', NULL, NULL),
(645, 'SLU', 'Kalingalan Caluang', NULL, NULL),
(646, 'LEY', 'Kananga', NULL, NULL),
(647, 'LAS', 'Kapai', NULL, NULL),
(648, 'DAV', 'Kapalong', NULL, NULL),
(649, 'BEN', 'Kapangan', NULL, NULL),
(650, 'LAN', 'Kapatagan', NULL, NULL),
(651, 'LAS', 'Kapatagan', NULL, NULL),
(652, 'NUV', 'Kasibu', NULL, NULL),
(653, 'ZAN', 'Katipunan', NULL, NULL),
(654, 'LAN', 'Kauswagan', NULL, NULL),
(655, 'BIL', 'Kawayan', NULL, NULL),
(656, 'CAV', 'Kawit', NULL, NULL),
(657, 'NUV', 'Kayapa', NULL, NULL),
(658, 'SAR', 'Kiamba', NULL, NULL),
(659, 'IFU', 'Kiangan', NULL, NULL),
(660, 'BUK', 'Kibawe', NULL, NULL),
(661, 'DAS', 'Kiblawan', NULL, NULL),
(662, 'BEN', 'Kibungan', NULL, NULL),
(663, 'NCO', 'Kidapawan', NULL, NULL),
(664, 'MSR', 'Kinoguitan', NULL, NULL),
(665, 'BUK', 'Kitaotao', NULL, NULL),
(666, 'AGN', 'Kitcharao', NULL, NULL),
(667, 'LAN', 'Kolambugan', NULL, NULL),
(668, 'SCO', 'Koronadal', NULL, NULL),
(669, 'ZAS', 'Kumalarang', NULL, NULL),
(670, 'NEC', 'La Carlota', NULL, NULL),
(671, 'NEC', 'La Castellana', NULL, NULL),
(672, 'NER', 'La Libertad', NULL, NULL),
(673, 'ZAN', 'La Libertad', NULL, NULL),
(674, 'ABR', 'La Paz', NULL, NULL),
(675, 'TAR', 'La Paz', NULL, NULL),
(676, 'LEY', 'La Paz', NULL, NULL),
(677, 'AGS', 'La Paz', NULL, NULL),
(678, 'BEN', 'La Trinidad', NULL, NULL),
(679, 'COM', 'Laak', NULL, NULL),
(680, 'ZAS', 'Labangan', NULL, NULL),
(681, 'ZAN', 'Labason', NULL, NULL),
(682, 'CAN', 'Labo', NULL, NULL),
(683, 'PAN', 'Labrador', NULL, NULL),
(684, 'ABR', 'Lacub', NULL, NULL),
(685, 'ABR', 'Lagangilang', NULL, NULL),
(686, 'IFU', 'Lagawe', NULL, NULL),
(687, 'ABR', 'Lagayan', NULL, NULL),
(688, 'MSR', 'Lagonglong', NULL, NULL),
(689, 'CAS', 'Lagonoy', NULL, NULL),
(690, 'MSR', 'Laguindingan', NULL, NULL),
(691, 'SCO', 'Lake Sebu', NULL, NULL),
(692, 'ZAS', 'Lakewood', NULL, NULL),
(693, 'LAN', 'Lala', NULL, NULL),
(694, 'CAG', 'Lal-lo', NULL, NULL),
(695, 'SUK', 'Lambayong', NULL, NULL),
(696, 'ILI', 'Lambunao', NULL, NULL),
(697, 'BAS', 'Lamitan', NULL, NULL),
(698, 'IFU', 'Lamut', NULL, NULL),
(699, 'ABR', 'Langiden', NULL, NULL),
(700, 'TAW', 'Languyan', NULL, NULL),
(701, 'BUK', 'Lantapan', NULL, NULL),
(702, 'BAS', 'Lantawan', NULL, NULL),
(703, 'SUR', 'Lanuza', NULL, NULL),
(704, 'PAN', 'Laoac', NULL, NULL),
(705, 'ILN', 'Laoag', NULL, NULL),
(706, 'NSA', 'Laoang', NULL, NULL),
(707, 'NSA', 'Lapinig', NULL, NULL),
(708, 'CEB', 'Lapu-Lapu', NULL, NULL),
(709, 'ZAS', 'Lapuyan', NULL, NULL),
(710, 'SIG', 'Larena', NULL, NULL),
(711, 'NSA', 'Las Navas', NULL, NULL),
(712, 'AGN', 'Las Nieves', NULL, NULL),
(713, 'MM', 'Las Piñas', NULL, NULL),
(714, 'CAG', 'Lasam', NULL, NULL),
(715, 'ANT', 'Laua-an', NULL, NULL),
(716, 'NUE', 'Laur', NULL, NULL),
(717, 'BTG', 'Laurel', NULL, NULL),
(718, 'NSA', 'Lavezares', NULL, NULL),
(719, 'EAS', 'Lawaan', NULL, NULL),
(720, 'SIG', 'Lazi', NULL, NULL),
(721, 'SUK', 'Lebak', NULL, NULL),
(722, 'ILI', 'Leganes', NULL, NULL),
(723, 'ALB', 'Legazpi', NULL, NULL),
(724, 'BTG', 'Lemery', NULL, NULL),
(725, 'ILI', 'Lemery', NULL, NULL),
(726, 'ILI', 'Leon', NULL, NULL),
(727, 'ZAN', 'Leon B. Postigo', NULL, NULL),
(728, 'LEY', 'Leyte', NULL, NULL),
(729, 'AKL', 'Lezo', NULL, NULL),
(730, 'BTG', 'Lian', NULL, NULL),
(731, 'SUR', 'Lianga', NULL, NULL),
(732, 'AKL', 'Libacao', NULL, NULL),
(733, 'SLE', 'Libagon', NULL, NULL),
(734, 'ANT', 'Libertad', NULL, NULL),
(735, 'MSR', 'Libertad', NULL, NULL),
(736, 'DIN', 'Libjo', NULL, NULL),
(737, 'CAS', 'Libmanan', NULL, NULL),
(738, 'ALB', 'Libon', NULL, NULL),
(739, 'BUK', 'Libona', NULL, NULL),
(740, 'NCO', 'Libungan', NULL, NULL),
(741, 'NUE', 'Licab', NULL, NULL),
(742, 'ABR', 'Licuan-Baay', NULL, NULL),
(743, 'ILS', 'Lidlidda', NULL, NULL),
(744, 'ALB', 'Ligao', NULL, NULL),
(745, 'BOH', 'Lila', NULL, NULL),
(746, 'LAG', 'Liliw', NULL, NULL),
(747, 'CEB', 'Liloan', NULL, NULL),
(748, 'SLE', 'Liloan', NULL, NULL),
(749, 'ZAN', 'Liloy', NULL, NULL),
(750, 'SLE', 'Limasawa', NULL, NULL),
(751, 'BAN', 'Limay', NULL, NULL),
(752, 'LAN', 'Linamon', NULL, NULL),
(753, 'PLW', 'Linapacan', NULL, NULL),
(754, 'PAN', 'Lingayen', NULL, NULL),
(755, 'SUR', 'Lingig', NULL, NULL),
(756, 'BTG', 'Lipa', NULL, NULL),
(757, 'NUE', 'Llanera', NULL, NULL),
(758, 'EAS', 'Llorente', NULL, NULL),
(759, 'BOH', 'Loay', NULL, NULL),
(760, 'BTG', 'Lobo', NULL, NULL),
(761, 'BOH', 'Loboc', NULL, NULL),
(762, 'MDC', 'Looc', NULL, NULL),
(763, 'ROM', 'Looc', NULL, NULL),
(764, 'BOH', 'Loon', NULL, NULL),
(765, 'NSA', 'Lope de Vega', NULL, NULL),
(766, 'QUE', 'Lopez', NULL, NULL),
(767, 'MSC', 'Lopez Jaena', NULL, NULL),
(768, 'AGS', 'Loreto', NULL, NULL),
(769, 'DIN', 'Loreto', NULL, NULL),
(770, 'LAG', 'Los Baños', NULL, NULL),
(771, 'ABR', 'Luba', NULL, NULL),
(772, 'MDC', 'Lubang', NULL, NULL),
(773, 'PAM', 'Lubao', NULL, NULL),
(774, 'KAL', 'Lubuagan', NULL, NULL),
(775, 'QUE', 'Lucban', NULL, NULL),
(776, 'QUE', 'Lucena', NULL, NULL),
(777, 'MSR', 'Lugait', NULL, NULL),
(778, 'SLU', 'Lugus', NULL, NULL),
(779, 'LAG', 'Luisiana', NULL, NULL),
(780, 'LAS', 'Lumba-Bayabao', NULL, NULL),
(781, 'LAS', 'Lumbaca-Unayan', NULL, NULL),
(782, 'LAG', 'Lumban', NULL, NULL),
(783, 'LAS', 'Lumbatan', NULL, NULL),
(784, 'LAS', 'Lumbayanague', NULL, NULL),
(785, 'APA', 'Luna', NULL, NULL),
(786, 'LUN', 'Luna', NULL, NULL),
(787, 'ISA', 'Luna', NULL, NULL),
(788, 'NUE', 'Lupao', NULL, NULL),
(789, 'CAS', 'Lupi', NULL, NULL),
(790, 'DAO', 'Lupon', NULL, NULL),
(791, 'SUK', 'Lutayan', NULL, NULL),
(792, 'SLU', 'Luuk', NULL, NULL),
(793, 'SAR', 'Maasim', NULL, NULL),
(794, 'ILI', 'Maasin', NULL, NULL),
(795, 'SLE', 'Maasin', NULL, NULL),
(796, 'CAP', 'Maayon', NULL, NULL),
(797, 'PAM', 'Mabalacat', NULL, NULL),
(798, 'NER', 'Mabinay', NULL, NULL),
(799, 'PAN', 'Mabini', NULL, NULL),
(800, 'BTG', 'Mabini', NULL, NULL),
(801, 'BOH', 'Mabini', NULL, NULL),
(802, 'COM', 'Mabini', NULL, NULL),
(803, 'LAG', 'Mabitac', NULL, NULL),
(804, 'ZSI', 'Mabuhay', NULL, NULL),
(805, 'PAM', 'Macabebe', NULL, NULL),
(806, 'QUE', 'Macalelon', NULL, NULL),
(807, 'LEY', 'MacArthur', NULL, NULL),
(808, 'COM', 'Maco', NULL, NULL),
(809, 'ISA', 'Maconacon', NULL, NULL),
(810, 'SLE', 'Macrohon', NULL, NULL),
(811, 'AKL', 'Madalag', NULL, NULL),
(812, 'LAS', 'Madalum', NULL, NULL),
(813, 'LAS', 'Madamba', NULL, NULL),
(814, 'QUI', 'Maddela', NULL, NULL),
(815, 'SUR', 'Madrid', NULL, NULL),
(816, 'CEB', 'Madridejos', NULL, NULL),
(817, 'PAM', 'Magalang', NULL, NULL),
(818, 'CAV', 'Magallanes', NULL, NULL),
(819, 'SOR', 'Magallanes', NULL, NULL),
(820, 'AGN', 'Magallanes', NULL, NULL),
(821, 'CAS', 'Magarao', NULL, NULL),
(822, 'LAG', 'Magdalena', NULL, NULL),
(823, 'ROM', 'Magdiwang', NULL, NULL),
(824, 'NCO', 'Magpet', NULL, NULL),
(825, 'MDC', 'Magsaysay', NULL, NULL),
(826, 'PLW', 'Magsaysay', NULL, NULL),
(827, 'LAN', 'Magsaysay', NULL, NULL),
(828, 'MSR', 'Magsaysay', NULL, NULL),
(829, 'DAS', 'Magsaysay', NULL, NULL),
(830, 'ILS', 'Magsingal', NULL, NULL),
(831, 'LAS', 'Maguing', NULL, NULL),
(832, 'LEY', 'Mahaplag', NULL, NULL),
(833, 'BTN', 'Mahatao', NULL, NULL),
(834, 'ZAS', 'Mahayag', NULL, NULL),
(835, 'CAM', 'Mahinog', NULL, NULL),
(836, 'LAN', 'Maigo', NULL, NULL),
(837, 'SLU', 'Maimbung', NULL, NULL),
(838, 'SUN', 'Mainit', NULL, NULL),
(839, 'SAR', 'Maitum', NULL, NULL),
(840, 'LAG', 'Majayjay', NULL, NULL),
(841, 'MM', 'Makati', NULL, NULL),
(842, 'AKL', 'Makato', NULL, NULL),
(843, 'NCO', 'Makilala', NULL, NULL),
(844, 'LAS', 'Malabang', NULL, NULL),
(845, 'MM', 'Malabon', NULL, NULL),
(846, 'CEB', 'Malabuyoc', NULL, NULL),
(847, 'DAS', 'Malalag', NULL, NULL),
(848, 'ZSI', 'Malangas', NULL, NULL),
(849, 'SAR', 'Malapatan', NULL, NULL),
(850, 'PAN', 'Malasiqui', NULL, NULL),
(851, 'AKL', 'Malay', NULL, NULL),
(852, 'BUK', 'Malaybalay', NULL, NULL),
(853, 'ABR', 'Malibcong', NULL, NULL),
(854, 'ALB', 'Malilipot', NULL, NULL),
(855, 'SUN', 'Malimono', NULL, NULL),
(856, 'ALB', 'Malinao', NULL, NULL),
(857, 'AKL', 'Malinao', NULL, NULL),
(858, 'DAC', 'Malita', NULL, NULL),
(859, 'SLE', 'Malitbog', NULL, NULL),
(860, 'BUK', 'Malitbog', NULL, NULL),
(861, 'ISA', 'Mallig', NULL, NULL),
(862, 'BUL', 'Malolos', NULL, NULL),
(863, 'SAR', 'Malungon', NULL, NULL),
(864, 'BAS', 'Maluso', NULL, NULL),
(865, 'BTG', 'Malvar', NULL, NULL),
(866, 'MAG', 'Mamasapano', NULL, NULL),
(867, 'CAM', 'Mambajao', NULL, NULL),
(868, 'MDC', 'Mamburao', NULL, NULL),
(869, 'CAP', 'Mambusao', NULL, NULL),
(870, 'ABR', 'Manabo', NULL, NULL),
(871, 'PAN', 'Manaoag', NULL, NULL),
(872, 'NEC', 'Manapla', NULL, NULL),
(873, 'DAO', 'Manay', NULL, NULL),
(874, 'MM', 'Mandaluyong', NULL, NULL),
(875, 'MAS', 'Mandaon', NULL, NULL),
(876, 'CEB', 'Mandaue', NULL, NULL),
(877, 'PAN', 'Mangaldan', NULL, NULL),
(878, 'PAN', 'Mangatarem', NULL, NULL),
(879, 'MAG', 'Mangudadatu', NULL, NULL),
(880, 'MM', 'Manila', NULL, NULL),
(881, 'ALB', 'Manito', NULL, NULL),
(882, 'NER', 'Manjuyod', NULL, NULL),
(883, 'BEN', 'Mankayan', NULL, NULL),
(884, 'BUK', 'Manolo Fortich', NULL, NULL),
(885, 'MDR', 'Mansalay', NULL, NULL),
(886, 'MSR', 'Manticao', NULL, NULL),
(887, 'ZAN', 'Manukan', NULL, NULL),
(888, 'NSA', 'Mapanas', NULL, NULL),
(889, 'PAN', 'Mapandan', NULL, NULL),
(890, 'TAW', 'Mapun', NULL, NULL),
(891, 'WSA', 'Marabut', NULL, NULL),
(892, 'CAV', 'Maragondon', NULL, NULL),
(893, 'COM', 'Maragusan', NULL, NULL),
(894, 'BUK', 'Maramag', NULL, NULL),
(895, 'LAS', 'Marantao', NULL, NULL),
(896, 'LAS', 'Marawi', NULL, NULL),
(897, 'ILN', 'Marcos', NULL, NULL),
(898, 'ZAS', 'Margosatubig', NULL, NULL),
(899, 'SIG', 'Maria', NULL, NULL),
(900, 'AUR', 'Maria Aurora', NULL, NULL),
(901, 'BOH', 'Maribojoc', NULL, NULL),
(902, 'SUR', 'Marihatag', NULL, NULL),
(903, 'MM', 'Marikina', NULL, NULL),
(904, 'BUL', 'Marilao', NULL, NULL),
(905, 'BIL', 'Maripipi', NULL, NULL),
(906, 'BAN', 'Mariveles', NULL, NULL),
(907, 'LAS', 'Marogong', NULL, NULL),
(908, 'PAM', 'Masantol', NULL, NULL),
(909, 'MAS', 'Masbate', NULL, NULL),
(910, 'ZMB', 'Masinloc', NULL, NULL),
(911, 'LAS', 'Masiu', NULL, NULL),
(912, 'EAS', 'Maslog', NULL, NULL),
(913, 'BTG', 'Mataasnakahoy', NULL, NULL),
(914, 'LEY', 'Matag-ob', NULL, NULL),
(915, 'NCO', 'Matalam', NULL, NULL),
(916, 'LEY', 'Matalom', NULL, NULL),
(917, 'DAS', 'Matanao', NULL, NULL),
(918, 'MAG', 'Matanog', NULL, NULL),
(919, 'DAO', 'Mati', NULL, NULL),
(920, 'SOR', 'Matnog', NULL, NULL),
(921, 'WSA', 'Matuguinao', NULL, NULL),
(922, 'LAN', 'Matungao', NULL, NULL),
(923, 'QUE', 'Mauban', NULL, NULL),
(924, 'COM', 'Mawab', NULL, NULL),
(925, 'TAR', 'Mayantoc', NULL, NULL),
(926, 'EAS', 'Maydolong', NULL, NULL),
(927, 'LEY', 'Mayorga', NULL, NULL),
(928, 'IFU', 'Mayoyao', NULL, NULL),
(929, 'CEB', 'Medellin', NULL, NULL),
(930, 'MSR', 'Medina', NULL, NULL),
(931, 'CAV', 'Mendez', NULL, NULL),
(932, 'CAN', 'Mercedes', NULL, NULL),
(933, 'EAS', 'Mercedes', NULL, NULL),
(934, 'LEY', 'Merida', NULL, NULL),
(935, 'PAM', 'Mexico', NULL, NULL),
(936, 'BUL', 'Meycauayan', NULL, NULL),
(937, 'ILI', 'Miagao', NULL, NULL),
(938, 'ZAS', 'Midsalip', NULL, NULL),
(939, 'NCO', 'Midsayap', NULL, NULL),
(940, 'MAS', 'Milagros', NULL, NULL),
(941, 'CAS', 'Milaor', NULL, NULL),
(942, 'ILI', 'Mina', NULL, NULL),
(943, 'CAS', 'Minalabac', NULL, NULL),
(944, 'PAM', 'Minalin', NULL, NULL),
(945, 'CEB', 'Minglanilla', NULL, NULL),
(946, 'NCO', 'M\'lang', NULL, NULL),
(947, 'CEB', 'Moalboal', NULL, NULL),
(948, 'MAS', 'Mobo', NULL, NULL),
(949, 'MAD', 'Mogpog', NULL, NULL),
(950, 'NEC', 'Moises Padilla', NULL, NULL),
(951, 'ZAS', 'Molave', NULL, NULL),
(952, 'TAR', 'Moncada', NULL, NULL),
(953, 'NSA', 'Mondragon', NULL, NULL),
(954, 'COM', 'Monkayo', NULL, NULL),
(955, 'MAS', 'Monreal', NULL, NULL),
(956, 'COM', 'Montevista', NULL, NULL),
(957, 'BAN', 'Morong', NULL, NULL),
(958, 'RIZ', 'Morong', NULL, NULL),
(959, 'WSA', 'Motiong', NULL, NULL),
(960, 'QUE', 'Mulanay', NULL, NULL),
(961, 'LAS', 'Mulondo', NULL, NULL),
(962, 'LAN', 'Munai', NULL, NULL),
(963, 'NUE', 'Muñoz', NULL, NULL),
(964, 'MM', 'Muntinlupa', NULL, NULL),
(965, 'NEC', 'Murcia', NULL, NULL),
(966, 'ZAN', 'Mutia', NULL, NULL),
(967, 'MSR', 'Naawan', NULL, NULL),
(968, 'AKL', 'Nabas', NULL, NULL),
(969, 'CAS', 'Nabua', NULL, NULL),
(970, 'COM', 'Nabunturan', NULL, NULL),
(971, 'CAS', 'Naga', NULL, NULL),
(972, 'CEB', 'Naga', NULL, NULL),
(973, 'ZSI', 'Naga', NULL, NULL),
(974, 'ILS', 'Nagbukel', NULL, NULL),
(975, 'LAG', 'Nagcarlan', NULL, NULL),
(976, 'QUI', 'Nagtipunan', NULL, NULL),
(977, 'LUN', 'Naguilian', NULL, NULL),
(978, 'ISA', 'Naguilian', NULL, NULL),
(979, 'CAV', 'Naic', NULL, NULL),
(980, 'NUE', 'Nampicuan', NULL, NULL),
(981, 'PLW', 'Narra', NULL, NULL),
(982, 'ILS', 'Narvacan', NULL, NULL),
(983, 'AGN', 'Nasipit', NULL, NULL),
(984, 'BTG', 'Nasugbu', NULL, NULL),
(985, 'PAN', 'Natividad', NULL, NULL),
(986, 'MOU', 'Natonin', NULL, NULL),
(987, 'MDR', 'Naujan', NULL, NULL),
(988, 'BIL', 'Naval', NULL, NULL),
(989, 'MM', 'Navotas', NULL, NULL),
(990, 'COM', 'New Bataan', NULL, NULL),
(991, 'DAV', 'New Corella', NULL, NULL),
(992, 'ILI', 'New Lucena', NULL, NULL),
(993, 'AKL', 'New Washington', NULL, NULL),
(994, 'SCO', 'Norala', NULL, NULL),
(995, 'MAG', 'Northern Kabuntalan', NULL, NULL),
(996, 'BUL', 'Norzagaray', NULL, NULL),
(997, 'CAV', 'Noveleta', NULL, NULL),
(998, 'ILN', 'Nueva Era', NULL, NULL),
(999, 'GUI', 'Nueva Valencia', NULL, NULL),
(1000, 'AKL', 'Numancia', NULL, NULL),
(1001, 'LAN', 'Nunungan', NULL, NULL),
(1002, 'ALB', 'Oas', NULL, NULL),
(1003, 'BUL', 'Obando', NULL, NULL),
(1004, 'CAS', 'Ocampo', NULL, NULL),
(1005, 'ROM', 'Odiongan', NULL, NULL),
(1006, 'SLU', 'Old Panamao', NULL, NULL),
(1007, 'ZMB', 'Olongapo', NULL, NULL),
(1008, 'ZSI', 'Olutanga', NULL, NULL),
(1009, 'SLU', 'Omar', NULL, NULL),
(1010, 'MSR', 'Opol', NULL, NULL),
(1011, 'BAN', 'Orani', NULL, NULL),
(1012, 'EAS', 'Oras', NULL, NULL),
(1013, 'BAN', 'Orion', NULL, NULL),
(1014, 'LEY', 'Ormoc', NULL, NULL),
(1015, 'MSC', 'Oroquieta', NULL, NULL),
(1016, 'CEB', 'Oslob', NULL, NULL),
(1017, 'ILI', 'Oton', NULL, NULL),
(1018, 'MSC', 'Ozamiz', NULL, NULL),
(1019, 'DAS', 'Padada', NULL, NULL),
(1020, 'QUE', 'Padre Burgos', NULL, NULL),
(1021, 'SLE', 'Padre Burgos', NULL, NULL),
(1022, 'BTG', 'Padre Garcia', NULL, NULL),
(1023, 'LAG', 'Paete', NULL, NULL),
(1024, 'ZAS', 'Pagadian', NULL, NULL),
(1025, 'MAG', 'Pagalungan', NULL, NULL),
(1026, 'LAS', 'Pagayawan', NULL, NULL),
(1027, 'QUE', 'Pagbilao', NULL, NULL),
(1028, 'MAG', 'Paglat', NULL, NULL),
(1029, 'WSA', 'Pagsanghan', NULL, NULL),
(1030, 'LAG', 'Pagsanjan', NULL, NULL),
(1031, 'ILN', 'Pagudpud', NULL, NULL),
(1032, 'LAG', 'Pakil', NULL, NULL),
(1033, 'ISA', 'Palanan', NULL, NULL),
(1034, 'MAS', 'Palanas', NULL, NULL),
(1035, 'NSA', 'Palapag', NULL, NULL),
(1036, 'ZMB', 'Palauig', NULL, NULL),
(1037, 'NUE', 'Palayan', NULL, NULL),
(1038, 'SUK', 'Palimbang', NULL, NULL),
(1039, 'LEY', 'Palo', NULL, NULL),
(1040, 'LEY', 'Palompon', NULL, NULL),
(1041, 'MDC', 'Paluan', NULL, NULL),
(1042, 'NSA', 'Pambujan', NULL, NULL),
(1043, 'CAG', 'Pamplona', NULL, NULL),
(1044, 'CAS', 'Pamplona', NULL, NULL),
(1045, 'NER', 'Pamplona', NULL, NULL),
(1046, 'DAV', 'Panabo', NULL, NULL),
(1047, 'MSC', 'Panaon', NULL, NULL),
(1048, 'CAP', 'Panay', NULL, NULL),
(1049, 'MAG', 'Pandag', NULL, NULL),
(1050, 'SLU', 'Pandami', NULL, NULL),
(1051, 'CAT', 'Pandan', NULL, NULL),
(1052, 'ANT', 'Pandan', NULL, NULL),
(1053, 'BUL', 'Pandi', NULL, NULL),
(1054, 'CAT', 'Panganiban', NULL, NULL),
(1055, 'BUK', 'Pangantucan', NULL, NULL),
(1056, 'LAG', 'Pangil', NULL, NULL),
(1057, 'BOH', 'Panglao', NULL, NULL),
(1058, 'SLU', 'Panglima Estino', NULL, NULL),
(1059, 'TAW', 'Panglima Sugala', NULL, NULL),
(1060, 'SLU', 'Pangutaran', NULL, NULL),
(1061, 'TAR', 'Paniqui', NULL, NULL),
(1062, 'CAP', 'Panitan', NULL, NULL),
(1063, 'NUE', 'Pantabangan', NULL, NULL),
(1064, 'LAN', 'Pantao Ragat', NULL, NULL),
(1065, 'LAN', 'Pantar', NULL, NULL),
(1066, 'COM', 'Pantukan', NULL, NULL),
(1067, 'QUE', 'Panukulan', NULL, NULL),
(1068, 'ILN', 'Paoay', NULL, NULL),
(1069, 'BUL', 'Paombong', NULL, NULL),
(1070, 'CAN', 'Paracale', NULL, NULL),
(1071, 'MOU', 'Paracelis', NULL, NULL),
(1072, 'MM', 'Parañaque', NULL, NULL),
(1073, 'WSA', 'Paranas', NULL, NULL),
(1074, 'MAG', 'Parang', NULL, NULL),
(1075, 'SLU', 'Parang', NULL, NULL),
(1076, 'CAS', 'Pasacao', NULL, NULL),
(1077, 'MM', 'Pasay', NULL, NULL),
(1078, 'MM', 'Pasig', NULL, NULL),
(1079, 'KAL', 'Pasil', NULL, NULL),
(1080, 'ILI', 'Passi', NULL, NULL),
(1081, 'LEY', 'Pastrana', NULL, NULL),
(1082, 'ILN', 'Pasuquin', NULL, NULL),
(1083, 'SLU', 'Pata', NULL, NULL),
(1084, 'MM', 'Pateros', NULL, NULL),
(1085, 'SLU', 'Patikul', NULL, NULL),
(1086, 'QUE', 'Patnanungan', NULL, NULL),
(1087, 'ANT', 'Patnongon', NULL, NULL),
(1088, 'ILI', 'Pavia', NULL, NULL),
(1089, 'ZSI', 'Payao', NULL, NULL),
(1090, 'CAG', 'Peñablanca', NULL, NULL),
(1091, 'NUE', 'Peñaranda', NULL, NULL),
(1092, 'ABR', 'Peñarrubia', NULL, NULL),
(1093, 'QUE', 'Perez', NULL, NULL),
(1094, 'LAS', 'Piagapo', NULL, NULL),
(1095, 'CAG', 'Piat', NULL, NULL),
(1096, 'LAS', 'Picong', NULL, NULL),
(1097, 'ILN', 'Piddig', NULL, NULL),
(1098, 'ABR', 'Pidigan', NULL, NULL),
(1099, 'NCO', 'Pigcawayan', NULL, NULL),
(1100, 'NCO', 'Pikit', NULL, NULL),
(1101, 'LAG', 'Pila', NULL, NULL),
(1102, 'ABR', 'Pilar', NULL, NULL),
(1103, 'BAN', 'Pilar', NULL, NULL),
(1104, 'SOR', 'Pilar', NULL, NULL),
(1105, 'CAP', 'Pilar', NULL, NULL),
(1106, 'BOH', 'Pilar', NULL, NULL),
(1107, 'CEB', 'Pilar', NULL, NULL),
(1108, 'SUN', 'Pilar', NULL, NULL),
(1109, 'CAS', 'Pili', NULL, NULL),
(1110, 'RIZ', 'Pililla', NULL, NULL),
(1111, 'WSA', 'Pinabacdao', NULL, NULL),
(1112, 'MDR', 'Pinamalayan', NULL, NULL),
(1113, 'CEB', 'Pinamungajan', NULL, NULL),
(1114, 'ZAN', 'Piñan', NULL, NULL),
(1115, 'ILN', 'Pinili', NULL, NULL),
(1116, 'SLE', 'Pintuyan', NULL, NULL),
(1117, 'KAL', 'Pinukpuk', NULL, NULL),
(1118, 'ALB', 'Pio Duran', NULL, NULL),
(1119, 'MAS', 'Pio V. Corpuz', NULL, NULL),
(1120, 'QUE', 'Pitogo', NULL, NULL),
(1121, 'ZAS', 'Pitogo', NULL, NULL),
(1122, 'MAS', 'Placer', NULL, NULL),
(1123, 'SUN', 'Placer', NULL, NULL),
(1124, 'BUL', 'Plaridel', NULL, NULL),
(1125, 'QUE', 'Plaridel', NULL, NULL),
(1126, 'MSC', 'Plaridel', NULL, NULL),
(1127, 'MDR', 'Pola', NULL, NULL),
(1128, 'ZAN', 'Polanco', NULL, NULL),
(1129, 'ALB', 'Polangui', NULL, NULL),
(1130, 'QUE', 'Polillo', NULL, NULL),
(1131, 'SCO', 'Polomolok', NULL, NULL),
(1132, 'CAP', 'Pontevedra', NULL, NULL),
(1133, 'NEC', 'Pontevedra', NULL, NULL),
(1134, 'LAS', 'Poona Bayabao', NULL, NULL),
(1135, 'LAN', 'Poona Piagapo', NULL, NULL),
(1136, 'PAM', 'Porac', NULL, NULL),
(1137, 'CEB', 'Poro', NULL, NULL),
(1138, 'ILI', 'Pototan', NULL, NULL),
(1139, 'PAN', 'Pozzorubio', NULL, NULL),
(1140, 'CAS', 'Presentacion', NULL, NULL),
(1141, 'BOH', 'President Carlos P. Garcia', NULL, NULL),
(1142, 'ZAN', 'President Manuel A. Roxas', NULL, NULL),
(1143, 'SUK', 'President Quirino', NULL, NULL),
(1144, 'CAP', 'President Roxas', NULL, NULL),
(1145, 'NCO', 'President Roxas', NULL, NULL),
(1146, 'SOR', 'Prieto Diaz', NULL, NULL),
(1147, 'AGS', 'Prosperidad', NULL, NULL),
(1148, 'LAS', 'Pualas', NULL, NULL),
(1149, 'APA', 'Pudtol', NULL, NULL),
(1150, 'MDR', 'Puerto Galera', NULL, NULL),
(1151, 'PLW', 'Puerto Princesa', NULL, NULL),
(1152, 'LUN', 'Pugo', NULL, NULL),
(1153, 'BUL', 'Pulilan', NULL, NULL),
(1154, 'NEC', 'Pulupandan', NULL, NULL),
(1155, 'TAR', 'Pura', NULL, NULL),
(1156, 'MM', 'Quezon', NULL, NULL),
(1157, 'ISA', 'Quezon', NULL, NULL),
(1158, 'NUV', 'Quezon', NULL, NULL),
(1159, 'NUE', 'Quezon', NULL, NULL),
(1160, 'QUE', 'Quezon', NULL, NULL),
(1161, 'PLW', 'Quezon', NULL, NULL),
(1162, 'BUK', 'Quezon', NULL, NULL),
(1163, 'EAS', 'Quinapondan', NULL, NULL),
(1164, 'ILS', 'Quirino', NULL, NULL),
(1165, 'ISA', 'Quirino', NULL, NULL),
(1166, 'CAS', 'Ragay', NULL, NULL),
(1167, 'MAG', 'Rajah Buayan', NULL, NULL),
(1168, 'ISA', 'Ramon', NULL, NULL),
(1169, 'ZAS', 'Ramon Magsaysay', NULL, NULL),
(1170, 'TAR', 'Ramos', NULL, NULL),
(1171, 'ALB', 'Rapu-Rapu', NULL, NULL),
(1172, 'QUE', 'Real', NULL, NULL),
(1173, 'ISA', 'Reina Mercedes', NULL, NULL),
(1174, 'AGN', 'Remedios T. Romualdez', NULL, NULL),
(1175, 'KAL', 'Rizal', NULL, NULL),
(1176, 'CAG', 'Rizal', NULL, NULL),
(1177, 'NUE', 'Rizal', NULL, NULL),
(1178, 'LAG', 'Rizal', NULL, NULL),
(1179, 'MDC', 'Rizal', NULL, NULL),
(1180, 'PLW', 'Rizal', NULL, NULL),
(1181, 'ZAN', 'Rizal', NULL, NULL),
(1182, 'RIZ', 'Rodriguez', NULL, NULL),
(1183, 'ROM', 'Romblon', NULL, NULL),
(1184, 'CEB', 'Ronda', NULL, NULL),
(1185, 'PAN', 'Rosales', NULL, NULL),
(1186, 'LUN', 'Rosario', NULL, NULL),
(1187, 'BTG', 'Rosario', NULL, NULL),
(1188, 'CAV', 'Rosario', NULL, NULL),
(1189, 'NSA', 'Rosario', NULL, NULL),
(1190, 'AGS', 'Rosario', NULL, NULL),
(1191, 'ZSI', 'Roseller Lim', NULL, NULL),
(1192, 'ISA', 'Roxas', NULL, NULL),
(1193, 'MDR', 'Roxas', NULL, NULL),
(1194, 'PLW', 'Roxas', NULL, NULL),
(1195, 'CAP', 'Roxas', NULL, NULL),
(1196, 'MOU', 'Sabangan', NULL, NULL),
(1197, 'BEN', 'Sablan', NULL, NULL),
(1198, 'MDC', 'Sablayan', NULL, NULL),
(1199, 'BTN', 'Sabtang', NULL, NULL),
(1200, 'MOU', 'Sadanga', NULL, NULL),
(1201, 'MOU', 'Sagada', NULL, NULL),
(1202, 'NEC', 'Sagay', NULL, NULL),
(1203, 'CAM', 'Sagay', NULL, NULL),
(1204, 'BOH', 'Sagbayan', NULL, NULL),
(1205, 'CAS', 'Sagñay', NULL, NULL),
(1206, 'QUI', 'Saguday', NULL, NULL),
(1207, 'LAS', 'Saguiaran', NULL, NULL),
(1208, 'SLE', 'Saint Bernard', NULL, NULL),
(1209, 'MSR', 'Salay', NULL, NULL),
(1210, 'ILS', 'Salcedo', NULL, NULL),
(1211, 'EAS', 'Salcedo', NULL, NULL),
(1212, 'ABR', 'Sallapadan', NULL, NULL),
(1213, 'ZAN', 'Salug', NULL, NULL),
(1214, 'LAN', 'Salvador', NULL, NULL),
(1215, 'NEC', 'Salvador Benedicto', NULL, NULL),
(1216, 'BAN', 'Samal', NULL, NULL),
(1217, 'DAV', 'Samal', NULL, NULL),
(1218, 'CEB', 'Samboan', NULL, NULL),
(1219, 'QUE', 'Sampaloc', NULL, NULL),
(1220, 'ISA', 'San Agustin', NULL, NULL),
(1221, 'ROM', 'San Agustin', NULL, NULL),
(1222, 'SUR', 'San Agustin', NULL, NULL),
(1223, 'QUE', 'San Andres', NULL, NULL),
(1224, 'ROM', 'San Andres', NULL, NULL),
(1225, 'CAT', 'San Andres', NULL, NULL),
(1226, 'NUE', 'San Antonio', NULL, NULL),
(1227, 'ZMB', 'San Antonio', NULL, NULL),
(1228, 'QUE', 'San Antonio', NULL, NULL),
(1229, 'NSA', 'San Antonio', NULL, NULL),
(1230, 'SUN', 'San Benito', NULL, NULL),
(1231, 'PAN', 'San Carlos', NULL, NULL),
(1232, 'NEC', 'San Carlos', NULL, NULL),
(1233, 'TAR', 'San Clemente', NULL, NULL),
(1234, 'ILI', 'San Dionisio', NULL, NULL),
(1235, 'ILS', 'San Emilio', NULL, NULL),
(1236, 'ILI', 'San Enrique', NULL, NULL),
(1237, 'NEC', 'San Enrique', NULL, NULL),
(1238, 'ILS', 'San Esteban', NULL, NULL),
(1239, 'PAN', 'San Fabian', NULL, NULL),
(1240, 'ZMB', 'San Felipe', NULL, NULL),
(1241, 'LUN', 'San Fernando', NULL, NULL),
(1242, 'PAM', 'San Fernando', NULL, NULL),
(1243, 'ROM', 'San Fernando', NULL, NULL),
(1244, 'CAS', 'San Fernando', NULL, NULL),
(1245, 'MAS', 'San Fernando', NULL, NULL),
(1246, 'CEB', 'San Fernando', NULL, NULL),
(1247, 'BUK', 'San Fernando', NULL, NULL),
(1248, 'QUE', 'San Francisco', NULL, NULL),
(1249, 'CEB', 'San Francisco', NULL, NULL),
(1250, 'SLE', 'San Francisco', NULL, NULL),
(1251, 'AGS', 'San Francisco', NULL, NULL),
(1252, 'SUN', 'San Francisco', NULL, NULL),
(1253, 'LUN', 'San Gabriel', NULL, NULL),
(1254, 'ISA', 'San Guillermo', NULL, NULL),
(1255, 'ILS', 'San Ildefonso', NULL, NULL),
(1256, 'BUL', 'San Ildefonso', NULL, NULL),
(1257, 'ABR', 'San Isidro', NULL, NULL),
(1258, 'ISA', 'San Isidro', NULL, NULL),
(1259, 'NUE', 'San Isidro', NULL, NULL),
(1260, 'BOH', 'San Isidro', NULL, NULL),
(1261, 'LEY', 'San Isidro', NULL, NULL),
(1262, 'NSA', 'San Isidro', NULL, NULL),
(1263, 'DAV', 'San Isidro', NULL, NULL),
(1264, 'DAO', 'San Isidro', NULL, NULL),
(1265, 'SUN', 'San Isidro', NULL, NULL),
(1266, 'PAN', 'San Jacinto', NULL, NULL),
(1267, 'MAS', 'San Jacinto', NULL, NULL),
(1268, 'ILI', 'San Joaquin', NULL, NULL),
(1269, 'WSA', 'San Jorge', NULL, NULL),
(1270, 'NUE', 'San Jose', NULL, NULL),
(1271, 'TAR', 'San Jose', NULL, NULL),
(1272, 'BTG', 'San Jose', NULL, NULL),
(1273, 'MDC', 'San Jose', NULL, NULL),
(1274, 'ROM', 'San Jose', NULL, NULL),
(1275, 'CAS', 'San Jose', NULL, NULL),
(1276, 'ANT', 'San Jose', NULL, NULL),
(1277, 'NER', 'San Jose', NULL, NULL),
(1278, 'NSA', 'San Jose', NULL, NULL),
(1279, 'DIN', 'San Jose', NULL, NULL),
(1280, 'WSA', 'San Jose de Buan', NULL, NULL),
(1281, 'BUL', 'San Jose del Monte', NULL, NULL),
(1282, 'MM', 'San Juan', NULL, NULL),
(1283, 'ABR', 'San Juan', NULL, NULL),
(1284, 'ILS', 'San Juan', NULL, NULL),
(1285, 'LUN', 'San Juan', NULL, NULL),
(1286, 'BTG', 'San Juan', NULL, NULL),
(1287, 'SIG', 'San Juan', NULL, NULL),
(1288, 'SLE', 'San Juan', NULL, NULL),
(1289, 'EAS', 'San Julian', NULL, NULL),
(1290, 'NUE', 'San Leonardo', NULL, NULL),
(1291, 'GUI', 'San Lorenzo', NULL, NULL),
(1292, 'CAN', 'San Lorenzo Ruiz', NULL, NULL),
(1293, 'AUR', 'San Luis', NULL, NULL),
(1294, 'PAM', 'San Luis', NULL, NULL),
(1295, 'BTG', 'San Luis', NULL, NULL),
(1296, 'AGS', 'San Luis', NULL, NULL),
(1297, 'PAN', 'San Manuel', NULL, NULL),
(1298, 'ISA', 'San Manuel', NULL, NULL),
(1299, 'TAR', 'San Manuel', NULL, NULL),
(1300, 'ZMB', 'San Marcelino', NULL, NULL),
(1301, 'ISA', 'San Mariano', NULL, NULL),
(1302, 'ISA', 'San Mateo', NULL, NULL),
(1303, 'RIZ', 'San Mateo', NULL, NULL),
(1304, 'BUL', 'San Miguel', NULL, NULL),
(1305, 'CAT', 'San Miguel', NULL, NULL),
(1306, 'ILI', 'San Miguel', NULL, NULL),
(1307, 'BOH', 'San Miguel', NULL, NULL),
(1308, 'LEY', 'San Miguel', NULL, NULL),
(1309, 'ZAS', 'San Miguel', NULL, NULL),
(1310, 'SUR', 'San Miguel', NULL, NULL),
(1311, 'ZMB', 'San Narciso', NULL, NULL),
(1312, 'QUE', 'San Narciso', NULL, NULL),
(1313, 'ILN', 'San Nicolas', NULL, NULL),
(1314, 'PAN', 'San Nicolas', NULL, NULL),
(1315, 'BTG', 'San Nicolas', NULL, NULL),
(1316, 'ISA', 'San Pablo', NULL, NULL),
(1317, 'LAG', 'San Pablo', NULL, NULL),
(1318, 'ZAS', 'San Pablo', NULL, NULL),
(1319, 'BTG', 'San Pascual', NULL, NULL),
(1320, 'MAS', 'San Pascual', NULL, NULL),
(1321, 'LAG', 'San Pedro', NULL, NULL),
(1322, 'EAS', 'San Policarpo', NULL, NULL),
(1323, 'ABR', 'San Quintin', NULL, NULL),
(1324, 'PAN', 'San Quintin', NULL, NULL),
(1325, 'BUL', 'San Rafael', NULL, NULL),
(1326, 'ILI', 'San Rafael', NULL, NULL),
(1327, 'ANT', 'San Remigio', NULL, NULL),
(1328, 'CEB', 'San Remigio', NULL, NULL),
(1329, 'SLE', 'San Ricardo', NULL, NULL),
(1330, 'NSA', 'San Roque', NULL, NULL),
(1331, 'WSA', 'San Sebastian', NULL, NULL),
(1332, 'PAM', 'San Simon', NULL, NULL),
(1333, 'MDR', 'San Teodoro', NULL, NULL),
(1334, 'ILS', 'San Vicente', NULL, NULL),
(1335, 'PLW', 'San Vicente', NULL, NULL),
(1336, 'CAN', 'San Vicente', NULL, NULL),
(1337, 'NSA', 'San Vicente', NULL, NULL),
(1338, 'CAG', 'Sanchez-Mira', NULL, NULL),
(1339, 'ILS', 'Santa', NULL, NULL),
(1340, 'CAG', 'Santa Ana', NULL, NULL),
(1341, 'PAM', 'Santa Ana', NULL, NULL),
(1342, 'PAN', 'Santa Barbara', NULL, NULL),
(1343, 'ILI', 'Santa Barbara', NULL, NULL),
(1344, 'ILS', 'Santa Catalina', NULL, NULL),
(1345, 'NER', 'Santa Catalina', NULL, NULL),
(1346, 'ILS', 'Santa Cruz', NULL, NULL),
(1347, 'ZMB', 'Santa Cruz', NULL, NULL),
(1348, 'LAG', 'Santa Cruz', NULL, NULL),
(1349, 'MAD', 'Santa Cruz', NULL, NULL),
(1350, 'MDC', 'Santa Cruz', NULL, NULL),
(1351, 'DAS', 'Santa Cruz', NULL, NULL),
(1352, 'CAN', 'Santa Elena', NULL, NULL),
(1353, 'NUV', 'Santa Fe', NULL, NULL),
(1354, 'ROM', 'Santa Fe', NULL, NULL),
(1355, 'CEB', 'Santa Fe', NULL, NULL),
(1356, 'LEY', 'Santa Fe', NULL, NULL),
(1357, 'TAR', 'Santa Ignacia', NULL, NULL),
(1358, 'AGS', 'Santa Josefa', NULL, NULL),
(1359, 'ILS', 'Santa Lucia', NULL, NULL),
(1360, 'SOR', 'Santa Magdalena', NULL, NULL),
(1361, 'APA', 'Santa Marcela', NULL, NULL),
(1362, 'WSA', 'Santa Margarita', NULL, NULL),
(1363, 'ILS', 'Santa Maria', NULL, NULL),
(1364, 'PAN', 'Santa Maria', NULL, NULL),
(1365, 'ISA', 'Santa Maria', NULL, NULL),
(1366, 'BUL', 'Santa Maria', NULL, NULL),
(1367, 'LAG', 'Santa Maria', NULL, NULL),
(1368, 'ROM', 'Santa Maria', NULL, NULL),
(1369, 'DAC', 'Santa Maria', NULL, NULL),
(1370, 'SUN', 'Santa Monica', NULL, NULL),
(1371, 'CAG', 'Santa Praxedes', NULL, NULL),
(1372, 'PAM', 'Santa Rita', NULL, NULL),
(1373, 'WSA', 'Santa Rita', NULL, NULL),
(1374, 'NUE', 'Santa Rosa', NULL, NULL),
(1375, 'LAG', 'Santa Rosa', NULL, NULL),
(1376, 'CAG', 'Santa Teresita', NULL, NULL),
(1377, 'BTG', 'Santa Teresita', NULL, NULL),
(1378, 'CEB', 'Santander', NULL, NULL),
(1379, 'ILS', 'Santiago', NULL, NULL);
INSERT INTO `location_cities` (`id`, `province_id`, `name`, `created_at`, `updated_at`) VALUES
(1380, 'ISA', 'Santiago', NULL, NULL),
(1381, 'AGN', 'Santiago', NULL, NULL),
(1382, 'ILS', 'Santo Domingo', NULL, NULL),
(1383, 'NUE', 'Santo Domingo', NULL, NULL),
(1384, 'ALB', 'Santo Domingo', NULL, NULL),
(1385, 'CAG', 'Santo Niño', NULL, NULL),
(1386, 'WSA', 'Santo Niño', NULL, NULL),
(1387, 'SCO', 'Santo Niño', NULL, NULL),
(1388, 'LUN', 'Santo Tomas', NULL, NULL),
(1389, 'PAN', 'Santo Tomas', NULL, NULL),
(1390, 'ISA', 'Santo Tomas', NULL, NULL),
(1391, 'PAM', 'Santo Tomas', NULL, NULL),
(1392, 'BTG', 'Santo Tomas', NULL, NULL),
(1393, 'DAV', 'Santo Tomas', NULL, NULL),
(1394, 'LUN', 'Santol', NULL, NULL),
(1395, 'LAN', 'Sapad', NULL, NULL),
(1396, 'MSC', 'Sapang Dalaga', NULL, NULL),
(1397, 'TAW', 'Sapa-Sapa', NULL, NULL),
(1398, 'CAP', 'Sapian', NULL, NULL),
(1399, 'ILI', 'Sara', NULL, NULL),
(1400, 'DAC', 'Sarangani', NULL, NULL),
(1401, 'QUE', 'Sariaya', NULL, NULL),
(1402, 'ILN', 'Sarrat', NULL, NULL),
(1403, 'PAM', 'Sasmuan', NULL, NULL),
(1404, 'ANT', 'Sebaste', NULL, NULL),
(1405, 'SUK', 'Senator Ninoy Aquino', NULL, NULL),
(1406, 'ZAN', 'Sergio Osmeña Sr.', NULL, NULL),
(1407, 'BOH', 'Sevilla', NULL, NULL),
(1408, 'MAG', 'Shariff Aguak', NULL, NULL),
(1409, 'MAG', 'Shariff Saydona Mustapha', NULL, NULL),
(1410, 'SLU', 'Siasi', NULL, NULL),
(1411, 'NER', 'Siaton', NULL, NULL),
(1412, 'ZSI', 'Siay', NULL, NULL),
(1413, 'ZAN', 'Siayan', NULL, NULL),
(1414, 'AGS', 'Sibagat', NULL, NULL),
(1415, 'ANT', 'Sibalom', NULL, NULL),
(1416, 'CEB', 'Sibonga', NULL, NULL),
(1417, 'ZAN', 'Sibuco', NULL, NULL),
(1418, 'NER', 'Sibulan', NULL, NULL),
(1419, 'GUI', 'Sibunag', NULL, NULL),
(1420, 'ZAN', 'Sibutad', NULL, NULL),
(1421, 'TAW', 'Sibutu', NULL, NULL),
(1422, 'BOH', 'Sierra Bullones', NULL, NULL),
(1423, 'ILS', 'Sigay', NULL, NULL),
(1424, 'CAP', 'Sigma', NULL, NULL),
(1425, 'BOH', 'Sikatuna', NULL, NULL),
(1426, 'SLE', 'Silago', NULL, NULL),
(1427, 'CAV', 'Silang', NULL, NULL),
(1428, 'NEC', 'Silay', NULL, NULL),
(1429, 'NSA', 'Silvino Lobos', NULL, NULL),
(1430, 'TAW', 'Simunul', NULL, NULL),
(1431, 'MSC', 'Sinacaban', NULL, NULL),
(1432, 'ILS', 'Sinait', NULL, NULL),
(1433, 'ZAN', 'Sindangan', NULL, NULL),
(1434, 'LAG', 'Siniloan', NULL, NULL),
(1435, 'ZAN', 'Siocon', NULL, NULL),
(1436, 'NEC', 'Sipalay', NULL, NULL),
(1437, 'CAS', 'Sipocot', NULL, NULL),
(1438, 'SIG', 'Siquijor', NULL, NULL),
(1439, 'ZAN', 'Sirawai', NULL, NULL),
(1440, 'CAS', 'Siruma', NULL, NULL),
(1441, 'PAN', 'Sison', NULL, NULL),
(1442, 'SUN', 'Sison', NULL, NULL),
(1443, 'TAW', 'Sitangkai', NULL, NULL),
(1444, 'MDR', 'Socorro', NULL, NULL),
(1445, 'SUN', 'Socorro', NULL, NULL),
(1446, 'PLW', 'Sofronio Española', NULL, NULL),
(1447, 'CEB', 'Sogod', NULL, NULL),
(1448, 'SLE', 'Sogod', NULL, NULL),
(1449, 'CAG', 'Solana', NULL, NULL),
(1450, 'NUV', 'Solano', NULL, NULL),
(1451, 'ILN', 'Solsona', NULL, NULL),
(1452, 'ZAS', 'Sominot', NULL, NULL),
(1453, 'SOR', 'Sorsogon', NULL, NULL),
(1454, 'TAW', 'South Ubian', NULL, NULL),
(1455, 'MAG', 'South Upi', NULL, NULL),
(1456, 'PAN', 'Sual', NULL, NULL),
(1457, 'ZMB', 'Subic', NULL, NULL),
(1458, 'LUN', 'Sudipen', NULL, NULL),
(1459, 'MSR', 'Sugbongcogon', NULL, NULL),
(1460, 'ILS', 'Sugpon', NULL, NULL),
(1461, 'EAS', 'Sulat', NULL, NULL),
(1462, 'DAS', 'Sulop', NULL, NULL),
(1463, 'LAS', 'Sultan Dumalondong', NULL, NULL),
(1464, 'MAG', 'Sultan Kudarat', NULL, NULL),
(1465, 'MAG', 'Sultan Mastura', NULL, NULL),
(1466, 'LAN', 'Sultan Naga Dimaporo', NULL, NULL),
(1467, 'MAG', 'Sultan sa Barongis', NULL, NULL),
(1468, 'MAG', 'Sultan Sumagka', NULL, NULL),
(1469, 'BUK', 'Sumilao', NULL, NULL),
(1470, 'BAS', 'Sumisip', NULL, NULL),
(1471, 'SCO', 'Surallah', NULL, NULL),
(1472, 'SUN', 'Surigao', NULL, NULL),
(1473, 'ILS', 'Suyo', NULL, NULL),
(1474, 'BTG', 'Taal', NULL, NULL),
(1475, 'ALB', 'Tabaco', NULL, NULL),
(1476, 'LEY', 'Tabango', NULL, NULL),
(1477, 'ZAS', 'Tabina', NULL, NULL),
(1478, 'CEB', 'Tabogon', NULL, NULL),
(1479, 'LEY', 'Tabontabon', NULL, NULL),
(1480, 'BAS', 'Tabuan-Lasa', NULL, NULL),
(1481, 'CEB', 'Tabuelan', NULL, NULL),
(1482, 'KAL', 'Tabuk', NULL, NULL),
(1483, 'LEY', 'Tacloban', NULL, NULL),
(1484, 'SUK', 'Tacurong', NULL, NULL),
(1485, 'MOU', 'Tadian', NULL, NULL),
(1486, 'EAS', 'Taft', NULL, NULL),
(1487, 'SUN', 'Tagana-an', NULL, NULL),
(1488, 'WSA', 'Tagapul-an', NULL, NULL),
(1489, 'CAV', 'Tagaytay', NULL, NULL),
(1490, 'BOH', 'Tagbilaran', NULL, NULL),
(1491, 'SUR', 'Tagbina', NULL, NULL),
(1492, 'QUE', 'Tagkawayan', NULL, NULL),
(1493, 'SUR', 'Tago', NULL, NULL),
(1494, 'LAN', 'Tagoloan', NULL, NULL),
(1495, 'MSR', 'Tagoloan', NULL, NULL),
(1496, 'LAS', 'Tagoloan II', NULL, NULL),
(1497, 'ILS', 'Tagudin', NULL, NULL),
(1498, 'MM', 'Taguig', NULL, NULL),
(1499, 'DAV', 'Tagum', NULL, NULL),
(1500, 'AGS', 'Talacogon', NULL, NULL),
(1501, 'DAV', 'Talaingod', NULL, NULL),
(1502, 'BUK', 'Talakag', NULL, NULL),
(1503, 'WSA', 'Talalora', NULL, NULL),
(1504, 'NUE', 'Talavera', NULL, NULL),
(1505, 'MAG', 'Talayan', NULL, NULL),
(1506, 'BOH', 'Talibon', NULL, NULL),
(1507, 'SLU', 'Talipao', NULL, NULL),
(1508, 'BTG', 'Talisay', NULL, NULL),
(1509, 'CAN', 'Talisay', NULL, NULL),
(1510, 'NEC', 'Talisay', NULL, NULL),
(1511, 'CEB', 'Talisay', NULL, NULL),
(1512, 'MSR', 'Talisayan', NULL, NULL),
(1513, 'NUE', 'Talugtug', NULL, NULL),
(1514, 'ZSI', 'Talusan', NULL, NULL),
(1515, 'ZAS', 'Tambulig', NULL, NULL),
(1516, 'SCO', 'Tampakan', NULL, NULL),
(1517, 'LAS', 'Tamparan', NULL, NULL),
(1518, 'ZAN', 'Tampilisan', NULL, NULL),
(1519, 'BTG', 'Tanauan', NULL, NULL),
(1520, 'LEY', 'Tanauan', NULL, NULL),
(1521, 'RIZ', 'Tanay', NULL, NULL),
(1522, 'SUR', 'Tandag', NULL, NULL),
(1523, 'TAW', 'Tandubas', NULL, NULL),
(1524, 'AKL', 'Tangalan', NULL, NULL),
(1525, 'LAN', 'Tangcal', NULL, NULL),
(1526, 'MSC', 'Tangub', NULL, NULL),
(1527, 'NER', 'Tanjay', NULL, NULL),
(1528, 'SCO', 'Tantangan', NULL, NULL),
(1529, 'KAL', 'Tanudan', NULL, NULL),
(1530, 'CAV', 'Tanza', NULL, NULL),
(1531, 'CAP', 'Tapaz', NULL, NULL),
(1532, 'SLU', 'Tapul', NULL, NULL),
(1533, 'LAS', 'Taraka', NULL, NULL),
(1534, 'WSA', 'Tarangnan', NULL, NULL),
(1535, 'TAR', 'Tarlac', NULL, NULL),
(1536, 'DAO', 'Tarragona', NULL, NULL),
(1537, 'QUE', 'Tayabas', NULL, NULL),
(1538, 'NER', 'Tayasan', NULL, NULL),
(1539, 'BTG', 'Taysan', NULL, NULL),
(1540, 'RIZ', 'Taytay', NULL, NULL),
(1541, 'PLW', 'Taytay', NULL, NULL),
(1542, 'PAN', 'Tayug', NULL, NULL),
(1543, 'ABR', 'Tayum', NULL, NULL),
(1544, 'SCO', 'T\'boli', NULL, NULL),
(1545, 'RIZ', 'Teresa', NULL, NULL),
(1546, 'CAV', 'Ternate', NULL, NULL),
(1547, 'QUE', 'Tiaong', NULL, NULL),
(1548, 'ANT', 'Tibiao', NULL, NULL),
(1549, 'CAS', 'Tigaon', NULL, NULL),
(1550, 'ZAS', 'Tigbao', NULL, NULL),
(1551, 'ILI', 'Tigbauan', NULL, NULL),
(1552, 'CAS', 'Tinambac', NULL, NULL),
(1553, 'ABR', 'Tineg', NULL, NULL),
(1554, 'KAL', 'Tinglayan', NULL, NULL),
(1555, 'BTG', 'Tingloy', NULL, NULL),
(1556, 'IFU', 'Tinoc', NULL, NULL),
(1557, 'BAS', 'Tipo-Tipo', NULL, NULL),
(1558, 'ZSI', 'Titay', NULL, NULL),
(1559, 'ALB', 'Tiwi', NULL, NULL),
(1560, 'ANT', 'Tobias Fornier', NULL, NULL),
(1561, 'NEC', 'Toboso', NULL, NULL),
(1562, 'CEB', 'Toledo', NULL, NULL),
(1563, 'LEY', 'Tolosa', NULL, NULL),
(1564, 'SLE', 'Tomas Oppus', NULL, NULL),
(1565, 'MAD', 'Torrijos', NULL, NULL),
(1566, 'CAV', 'Trece Martires', NULL, NULL),
(1567, 'AGS', 'Trento', NULL, NULL),
(1568, 'BOH', 'Trinidad', NULL, NULL),
(1569, 'CAG', 'Tuao', NULL, NULL),
(1570, 'BEN', 'Tuba', NULL, NULL),
(1571, 'DIN', 'Tubajon', NULL, NULL),
(1572, 'LUN', 'Tubao', NULL, NULL),
(1573, 'LAS', 'Tubaran', NULL, NULL),
(1574, 'AGN', 'Tubay', NULL, NULL),
(1575, 'BOH', 'Tubigon', NULL, NULL),
(1576, 'BEN', 'Tublay', NULL, NULL),
(1577, 'ABR', 'Tubo', NULL, NULL),
(1578, 'LAN', 'Tubod', NULL, NULL),
(1579, 'SUN', 'Tubod', NULL, NULL),
(1580, 'ILI', 'Tubungan', NULL, NULL),
(1581, 'CEB', 'Tuburan', NULL, NULL),
(1582, 'BAS', 'Tuburan', NULL, NULL),
(1583, 'CEB', 'Tudela', NULL, NULL),
(1584, 'MSC', 'Tudela', NULL, NULL),
(1585, 'LAS', 'Tugaya', NULL, NULL),
(1586, 'CAG', 'Tuguegarao', NULL, NULL),
(1587, 'ZAS', 'Tukuran', NULL, NULL),
(1588, 'NCO', 'Tulunan', NULL, NULL),
(1589, 'ISA', 'Tumauini', NULL, NULL),
(1590, 'LEY', 'Tunga', NULL, NULL),
(1591, 'ZSI', 'Tungawan', NULL, NULL),
(1592, 'SCO', 'Tupi', NULL, NULL),
(1593, 'TAW', 'Turtle Islands', NULL, NULL),
(1594, 'BTG', 'Tuy', NULL, NULL),
(1595, 'BOH', 'Ubay', NULL, NULL),
(1596, 'PAN', 'Umingan', NULL, NULL),
(1597, 'BAS', 'Ungkaya Pukan', NULL, NULL),
(1598, 'QUE', 'Unisan', NULL, NULL),
(1599, 'MAG', 'Upi', NULL, NULL),
(1600, 'PAN', 'Urbiztondo', NULL, NULL),
(1601, 'PAN', 'Urdaneta', NULL, NULL),
(1602, 'MAS', 'Uson', NULL, NULL),
(1603, 'BTN', 'Uyugan', NULL, NULL),
(1604, 'ANT', 'Valderrama', NULL, NULL),
(1605, 'BOH', 'Valencia', NULL, NULL),
(1606, 'NER', 'Valencia', NULL, NULL),
(1607, 'BUK', 'Valencia', NULL, NULL),
(1608, 'MM', 'Valenzuela', NULL, NULL),
(1609, 'NEC', 'Valladolid', NULL, NULL),
(1610, 'NER', 'Vallehermoso', NULL, NULL),
(1611, 'AGS', 'Veruela', NULL, NULL),
(1612, 'TAR', 'Victoria', NULL, NULL),
(1613, 'LAG', 'Victoria', NULL, NULL),
(1614, 'MDR', 'Victoria', NULL, NULL),
(1615, 'NSA', 'Victoria', NULL, NULL),
(1616, 'NEC', 'Victorias', NULL, NULL),
(1617, 'CAT', 'Viga', NULL, NULL),
(1618, 'ILS', 'Vigan', NULL, NULL),
(1619, 'LEY', 'Villaba', NULL, NULL),
(1620, 'MSR', 'Villanueva', NULL, NULL),
(1621, 'WSA', 'Villareal', NULL, NULL),
(1622, 'PAN', 'Villasis', NULL, NULL),
(1623, 'NUV', 'Villaverde', NULL, NULL),
(1624, 'ABR', 'Villaviciosa', NULL, NULL),
(1625, 'ZAS', 'Vincenzo A. Sagun', NULL, NULL),
(1626, 'ILN', 'Vintar', NULL, NULL),
(1627, 'CAN', 'Vinzons', NULL, NULL),
(1628, 'CAT', 'Virac', NULL, NULL),
(1629, 'LAS', 'Wao', NULL, NULL),
(1630, 'ZAS', 'Zamboanga', NULL, NULL),
(1631, 'NER', 'Zamboanguita', NULL, NULL),
(1632, 'NUE', 'Zaragoza', NULL, NULL),
(1633, 'ILI', 'Zarraga', NULL, NULL),
(1634, 'WSA', 'Zumarraga', NULL, NULL);
