INSERT INTO `universities` (`id`, `name`, `created_at`, `updated_at`) VALUES
(1, 'Abada Colleges - Pinamalayan, Oriental Mindoro', NULL, NULL),
(2, 'ABEC Institute of Business and Technology - Legazpi City', NULL, NULL),
(3, 'ABE International College of Business and Accountancy', NULL, NULL),
(4, 'Abra Valley Colleges - Bangued, Abra', NULL, NULL),
(5, 'Abuyog Community College (ACC) - Abuyog, Leyte', NULL, NULL),
(6, 'Academia de Davao College (ADDC) - Tagum City', NULL, NULL),
(7, 'Access Computer College', NULL, NULL),
(8, 'Aces Tagum College (ATC) - Tagum City', NULL, NULL),
(9, 'ACQ College of Ministries - Davao City', NULL, NULL),
(10, 'ACLC Colleges - multiple campuses (AMA Education Systems)', NULL, NULL),
(11, 'ACSI College - Iloilo City', NULL, NULL),
(12, 'ACTS Computer College - Laguna, Quezon', NULL, NULL),
(13, 'Adamson University - Manila', NULL, NULL),
(14, 'Adventist International Institute of Advanced Studies - Silang, Cavite', NULL, NULL),
(15, 'Adventist University of the Philippines - Silang, Cavite', NULL, NULL),
(16, 'Aemilianum College - Sorsogon City', NULL, NULL),
(17, 'Aeronautical Academy of the Philippines - Canaman, Camarines Sur', NULL, NULL),
(18, 'Ago Medical and Educational Center - Bicol Christian College of Medicine - Legazpi City', NULL, NULL),
(19, 'Agro-Industrial Foundation College of the Philippines - Davao City', NULL, NULL),
(20, 'Agusan del Sur College - Bayugan City', NULL, NULL),
(21, 'AIE College', NULL, NULL),
(22, 'Airlink International Aviation School', NULL, NULL),
(23, 'Aklan Catholic College - Kalibo', NULL, NULL),
(24, 'Aklan Polytechnic College - Kalibo', NULL, NULL),
(25, 'Aklan State University', NULL, NULL),
(26, 'Aldersgate College - Nueva Vizcaya', NULL, NULL),
(27, 'Alfelor Memorial College - Del Gallego, Camarines Sur', NULL, NULL),
(28, 'Alfonso D. Tan College - Tangub City', NULL, NULL),
(29, 'Alpha Centauri Educational System - Lucena City', NULL, NULL),
(30, 'AMA Computer University', NULL, NULL),
(31, 'Amando Cope College - Tabaco City', NULL, NULL),
(32, 'Andres Bonifacio College -Dipolog', NULL, NULL),
(33, 'Angeles University Foundation', NULL, NULL),
(34, 'Apostle Business College - San Francisco, Agusan del Sur', NULL, NULL),
(35, 'Annunciation College of Bacon Sorsogon Unit, Inc.', NULL, NULL),
(36, 'Araullo University - Cabanatuan City', NULL, NULL),
(37, 'Arellano University â€“ multiple campuses', NULL, NULL),
(38, 'Arreisgado College Foundation Inc. - Tagum City', NULL, NULL),
(39, 'Asia Pacific College', NULL, NULL),
(40, 'Asian Pacific College of Advanced Studies - Balanga City, Bataan', NULL, NULL),
(41, 'Asia School of Arts and Sciences', NULL, NULL),
(42, 'Asian College, Dumaguete', NULL, NULL),
(43, 'Asian College of Technology - Cebu', NULL, NULL),
(44, 'Asian College of Technology Main Campus - P. del Rosario St., Cebu City', NULL, NULL),
(45, 'Asian College of Technology Talamban Campus - Talamban, Cebu City', NULL, NULL),
(46, 'Asian College of Technology Bulacao Campus - Bulacao, Talisay City', NULL, NULL),
(47, 'Asian College - Quezon City', NULL, NULL),
(48, 'Asian College Foundation - Butuan City', NULL, NULL),
(49, 'Asian Computer College - Calamba Campuses', NULL, NULL),
(50, 'Asian Development Foundation College - Tacloban City', NULL, NULL),
(51, 'Asian International School of Aeronautics and Technology - Davao City', NULL, NULL),
(52, 'Asian Institute for Distance Education - Makati', NULL, NULL),
(53, 'Asian Institute of Computer Studies â€“ multiple campuses', NULL, NULL),
(54, 'Asian Institute of Journalism and Communication', NULL, NULL),
(55, 'Asian Institute of Management', NULL, NULL),
(56, 'Asian Institute of Maritime Studies - Pasay', NULL, NULL),
(57, 'Asian School of Hospitality Arts', NULL, NULL),
(58, 'Asian Social Institute - Manila', NULL, NULL),
(59, 'Asian Summit College - Pasig', NULL, NULL),
(60, 'Assumption College', NULL, NULL),
(61, 'Assumption Antipolo - Antipolo, Rizal', NULL, NULL),
(62, 'Assumption Iloilo - Iloilo, Iloilo City', NULL, NULL),
(63, 'Assumption College of Davao - Davao City', NULL, NULL),
(64, 'Assumption College of Nabunturan - Nabunturan, Davao de Oro', NULL, NULL),
(65, 'Assumption College San Lorenzo - Makati', NULL, NULL),
(66, 'Ateneo de Cagayan - Xavier University - Cagayan de Oro', NULL, NULL),
(67, 'Ateneo de Davao University', NULL, NULL),
(68, 'Ateneo de Manila University', NULL, NULL),
(69, 'Ateneo de Naga University', NULL, NULL),
(70, 'Ateneo de Zamboanga University', NULL, NULL),
(71, 'Aurora Pioneers Memorial College - Aurora, Zamboanga del Sur', NULL, NULL),
(72, 'Aurora Polytechnic College - Baler, Aurora', NULL, NULL),
(73, 'Aurora State College of Technology - Baler, Aurora', NULL, NULL),
(74, 'Baao Community College - Baao, Camarines Sur', NULL, NULL),
(75, 'Bacacay Community College - Bacacay, Albay', NULL, NULL),
(76, 'Bacolod City College', NULL, NULL),
(77, 'Bago City College', NULL, NULL),
(78, 'Baguio Central University', NULL, NULL),
(79, 'Baguio College of Technology', NULL, NULL),
(80, 'Balete Community College - Balete, Aklan', NULL, NULL),
(81, 'Baliuag Polytechnic College', NULL, NULL),
(82, 'Baliuag University', NULL, NULL),
(83, 'Baptist Voice Bible College - Lucena, Quezon', NULL, NULL),
(84, 'Basilan State College - Isabela, Basilan', NULL, NULL),
(85, 'Bataan Peninsula State University â€“ multiple campuses', NULL, NULL),
(86, 'Bataan Heroes Memorial College - Balanga, Bataan', NULL, NULL),
(87, 'Bataan State College - Dinalupihan, Bataan', NULL, NULL),
(88, 'Batan Community College - Batan, Aklan', NULL, NULL),
(89, 'Batanes State College - Basco, Batanes', NULL, NULL),
(90, 'Batangas Eastern Colleges - San Juan, Batangas', NULL, NULL),
(91, 'Batangas State University â€“ multiple campuses', NULL, NULL),
(92, 'The Bearer of Light and Wisdom Colleges - Molino, Bacoor City, Cavite', NULL, NULL),
(93, 'Belen B. Francisco Foundation', NULL, NULL),
(94, 'Belen B. Francisco Foundation - Daraga â€“ main campus', NULL, NULL),
(95, 'Belen B. Francisco Foundation - Sorsogon â€“ satellite campus', NULL, NULL),
(96, 'Benguet State University', NULL, NULL),
(97, 'Bestlink College of the Philippines', NULL, NULL),
(98, 'The Bethany Christian Academy - Cabanatuan City, Inc.', NULL, NULL),
(99, 'Bicol Christian College of Medicine (Ago Medical and Educational Center) - Legazpi City', NULL, NULL),
(100, 'Bicol College - Daraga, Albay', NULL, NULL),
(101, 'Bicol Merchant Marine College - Sorsogon City', NULL, NULL),
(102, 'Bicol State College of Applied Sciences and Technology', NULL, NULL),
(103, 'Bicol University â€“ multiple campuses', NULL, NULL),
(104, 'Biliran National Agricultural College - Biliran, Biliran Province', NULL, NULL),
(105, 'Binalbagan Catholic College - Binalbagan, Negros Occidental', NULL, NULL),
(106, 'Binangonan Catholic College - Binangonan, Rizal', NULL, NULL),
(107, 'Bohol Institute of Technology â€“ multiple campuses', NULL, NULL),
(108, 'Bohol Island State University (formerly Central Visayas State College of Agriculture, Forestry and Technology) â€“ multiple campuses', NULL, NULL),
(109, 'Bohol Northeastern Education Foundation', NULL, NULL),
(110, 'Bool City Central University - Bool City, Biliran', NULL, NULL),
(111, 'Brent Hospital and Colleges Inc. - Zamboanga City', NULL, NULL),
(112, 'Brentwood International School - Naga City', NULL, NULL),
(113, 'Brokenshire College â€“ multiple campuses', NULL, NULL),
(114, 'Brookfield College - DasmariÃ±as City, Cavite Campus', NULL, NULL),
(115, 'BST Grace College - San Fernando, Camarines Sur', NULL, NULL),
(116, 'Bukidnon State University - Malaybalay City, Bukidnon', NULL, NULL),
(117, 'Bulacan Agricultural State College - San Idelfonso, Bulacan', NULL, NULL),
(118, 'Bulacan Polytechnic College', NULL, NULL),
(119, 'Bulacan State University â€“ multiple campuses', NULL, NULL),
(120, 'Cabucgayan National School of Arts and Trades - Bgy. Bunga, Cabucgayan, Biliran Province', NULL, NULL),
(121, 'Cagayan de Oro College - Carmen, Cagayan de Oro City', NULL, NULL),
(122, 'Cagayan State University â€“ multiple campuses', NULL, NULL),
(123, 'Cagayan Technical Institute School of Automotive - Tuguegarao City, Cagayan', NULL, NULL),
(124, 'Cagayan Valley Computer and Information Technology College, Inc.', NULL, NULL),
(125, 'Cainta Catholic College - Cainta, Rizal', NULL, NULL),
(126, 'Calabanga Community College - Calabanga, Camarines Sur', NULL, NULL),
(127, 'Calamba Doctors\' College - Calamba City', NULL, NULL),
(128, 'Calauag Central College - Calauag, Quezon Province', NULL, NULL),
(129, 'Calayan Educational Foundation Inc. - Lucena City', NULL, NULL),
(130, 'Camarines Norte State College', NULL, NULL),
(131, 'Camarines Norte State College - AbaÃ±o campus', NULL, NULL),
(132, 'Camarines Norte State College - Entienza campus', NULL, NULL),
(133, 'Camarines Norte State College - Daet (main campus)', NULL, NULL),
(134, 'Camarines Norte State College - Labo campus', NULL, NULL),
(135, 'Camarines Norte State College - Mercedes campus', NULL, NULL),
(136, 'Camarines Norte State College - Panganiban campus', NULL, NULL),
(137, 'Camiling Colleges - Camiling, Tarlac', NULL, NULL),
(138, 'Camo College Incorporated - Pili, Camarines Sur', NULL, NULL),
(139, 'Canossa Colleges - San Pablo City', NULL, NULL),
(140, 'CAP College Foundation', NULL, NULL),
(141, 'Capalonga College - Capalonga, Camarines Norte', NULL, NULL),
(142, 'Capitol University - Corrales Ext., Cagayan de Oro City', NULL, NULL),
(143, 'Capiz State University â€“ multiple campuses', NULL, NULL),
(144, 'Caraga State University', NULL, NULL),
(145, 'Carlos Hilado Memorial State College - Talisay City, Cebu', NULL, NULL),
(146, 'Cataingan Polytechnic Institute - Cataingan, Masbate', NULL, NULL),
(147, 'Catanduanes Colleges - Virac', NULL, NULL),
(148, 'Catanduanes Institute of Technology Foundation Inc. - Virac', NULL, NULL),
(149, 'Catanduanes State University', NULL, NULL),
(150, 'Catanduanes State University - Panganiban', NULL, NULL),
(151, 'Catanduanes State University - Virac', NULL, NULL),
(152, 'Cavite State University â€“ multiple campuses', NULL, NULL),
(153, 'Cebu Aeronautical Technical School - Salinas Drive, Lahug, Cebu City', NULL, NULL),
(154, 'Cebu Doctors\' University - Mandaue City', NULL, NULL),
(155, 'Cebu Eastern College - Cebu City', NULL, NULL),
(156, 'Cebu Institute of Medicine - Cebu City', NULL, NULL),
(157, 'Cebu Institute of Technology â€“ University - Cebu City', NULL, NULL),
(158, 'Cebu International Distance Education College - Cebu City', NULL, NULL),
(159, 'Cebu Normal University', NULL, NULL),
(160, 'Cebu Normal University - Balamban', NULL, NULL),
(161, 'Cebu Roosevelt Memorial Colleges - Bogo City, Cebu', NULL, NULL),
(162, 'Cebu Technological University (formerly Cebu State College of Science and Technology)', NULL, NULL),
(163, 'Ceguera Technological Colleges (formerly Ceguera Institute of Science and Technology)', NULL, NULL),
(164, 'Center for Industrial Technology and Enterprise (CITE) Technical Institute, Inc.', NULL, NULL),
(165, 'Central Bicol State University of Agriculture - multiple campuses', NULL, NULL),
(166, 'Central Colleges of the North - Tuguegarao City, Cagayan', NULL, NULL),
(167, 'Central Colleges of the Philippines', NULL, NULL),
(168, 'Central Luzon College of Science and Technology', NULL, NULL),
(169, 'Central Luzon Doctors\' Hospital Educational Institution', NULL, NULL),
(170, 'Central Luzon State University - Munoz City', NULL, NULL),
(171, 'Central Mindanao University', NULL, NULL),
(172, 'Central Panay College of Science and Technology - Kalibo, Aklan', NULL, NULL),
(173, 'Central Philippine Adventist College - Negros Occidental', NULL, NULL),
(174, 'Central Philippine University - Jaro, Iloilo City', NULL, NULL),
(175, 'Central Philippines State University - Kabankalan City, Negros Occidental', NULL, NULL),
(176, 'Centre for International Education (CIE)', NULL, NULL),
(177, 'Centro Escolar University', NULL, NULL),
(178, 'Centro Escolar University Manila', NULL, NULL),
(179, 'Centro Escolar University Makati', NULL, NULL),
(180, 'Centro Escolar University Malolos', NULL, NULL),
(181, 'Centro Escolar Las PiÃ±as', NULL, NULL),
(182, 'Chiang Kai Shek College', NULL, NULL),
(183, 'Chinese General Hospital Colleges', NULL, NULL),
(184, 'Christ the King College - Calbayog City', NULL, NULL),
(185, 'Christ the King College - Gingoog City', NULL, NULL),
(186, 'Christ the King College de Maranding - Maranding Lala, Lanao del Norte', NULL, NULL),
(187, 'Christ the King Mission Seminary', NULL, NULL),
(188, 'Christian Polytechnic Institute of Catanduanes - Virac', NULL, NULL),
(189, 'Chronicles Institute of Isabela - Ilagan City, Isabela', NULL, NULL),
(190, 'CIIT (Cosmopolitan International Institute of Technology)', NULL, NULL),
(191, 'CIIT College of Arts and Technology - Tomas Morato, Quezon City', NULL, NULL),
(192, 'Citi Global College of Cabuyao (Main Campus)', NULL, NULL),
(193, 'Citi Global College of Calamba (Annex Campus)', NULL, NULL),
(194, 'City College of Calamba', NULL, NULL),
(195, 'City College of Lucena', NULL, NULL),
(196, 'City College of Naga - PeÃ±afrancia Avenue, Naga City', NULL, NULL),
(197, 'City of Malabon University', NULL, NULL),
(198, 'City Technological Institute - Tuguegarao City, Cagayan', NULL, NULL),
(199, 'COMTECH International Institute of Technologies Inc.(CIITI Colleges)-Isabela', NULL, NULL),
(200, 'Claret College of Isabela - Isabela City', NULL, NULL),
(201, 'Claret Formation Center - Quezon City', NULL, NULL),
(202, 'Colegio de Capitolio - Tagum City', NULL, NULL),
(203, 'Colegio de Dagupan', NULL, NULL),
(204, 'Colegio de Ilagan - Ilagan City, Isabela', NULL, NULL),
(205, 'Colegio de la Purisima Concepcion', NULL, NULL),
(206, 'Colegio de MedaillÃ¨ Miraculous, Inc. - Subic, Zambales', NULL, NULL),
(207, 'Colegio de Muntinlupa - Muntinlupa City', NULL, NULL),
(208, 'Colegio de San Clemente - Angono, Rizal', NULL, NULL),
(209, 'Colegio de San Gabriel - Arcangel - San Jose del Monte, Bulacan', NULL, NULL),
(210, 'Colegio de San Jose - Jaro, Iloilo City', NULL, NULL),
(211, 'Colegio de San Juan de Letran', NULL, NULL),
(212, 'Colegio de San Juan de Letran - Bataan', NULL, NULL),
(213, 'Colegio de San Juan de Letran - Calamba', NULL, NULL),
(214, 'Colegio de San Juan de Letran - Manaoag', NULL, NULL),
(215, 'Colegio de San Lorenzo', NULL, NULL),
(216, 'Colegio de San Lorenzo Ruiz de Manila - Tacloban City', NULL, NULL),
(217, 'Colegio de San Lorenzo Ruiz de Manila of Northern Samar Inc - Catarman, Northern Samar', NULL, NULL),
(218, 'Colegio de San Pascual Baylon - Obando, Bulacan', NULL, NULL),
(219, 'Colegio de Santa Catalina de Alejandria - Dumaguete City', NULL, NULL),
(220, 'Colegio de Santo Cristo de Burgos - Sariaya, Quezon', NULL, NULL),
(221, 'Colegio de Santo Tomas - Recoletos', NULL, NULL),
(222, 'Colegio de Sta. Teresa de Avila - Novaliches, Quezon City', NULL, NULL),
(223, 'Colegio del Sagrado Corazon de Jesus - Iloilo City', NULL, NULL),
(224, 'Colegio ng Lungsod ng Batangas', NULL, NULL),
(225, 'Colegio San Agustin', NULL, NULL),
(226, 'Colegio San Agustin-Bacolod', NULL, NULL),
(227, 'Colegio San Agustin-BiÃ±an', NULL, NULL),
(228, 'Colegio San Agustin-Makati', NULL, NULL),
(229, 'College of Arts & Sciences of Asia & the Pacific', NULL, NULL),
(230, 'College of Business Education Science and Technology - Cauayan City, Isabela', NULL, NULL),
(231, 'College of Divine Wisdom - Paranaque City', NULL, NULL),
(232, 'College of the Holy Spirit', NULL, NULL),
(233, 'College of the Immaculate Conception, Sumacab Este, Cabanatuan City', NULL, NULL),
(234, 'College of Mary Immaculate - Poblacion, Pandi, Bulacan', NULL, NULL),
(235, 'College of Our Lady of Mercy of Pulilan Foundation, Inc.- Longos, Pulilan, Bulacan', NULL, NULL),
(236, 'College of Mt. Carmel - Lolomboy, Bulacan', NULL, NULL),
(237, 'College of Saint Lawrence - Balagtas, Bulacan', NULL, NULL),
(238, 'College of San Benildo - Rizal', NULL, NULL),
(239, 'College of St. John-Roxas, De La Salle Supervised', NULL, NULL),
(240, 'College of Technological Sciences - Cebu City', NULL, NULL),
(241, 'Columban College - Olongapo City', NULL, NULL),
(242, 'Columbus College - Lucena City, Quezon', NULL, NULL),
(243, 'Community Colleges of the Philippines Foundation Manila', NULL, NULL),
(244, 'Computer Arts & Technological (CAT) College - Legazpi, Albay', NULL, NULL),
(245, 'Computer Communication Development Institute (CCDI) College - Naga City', NULL, NULL),
(246, 'COMTECH International Institute of Technologies Inc. (CIITI Colleges) - Zamboanga City', NULL, NULL),
(247, 'Comteq Computer and Business College - Olongapo City', NULL, NULL),
(248, 'Concordia College - Paco', NULL, NULL),
(249, 'Consolatrix College of Toledo City', NULL, NULL),
(250, 'Cor Jesu College - Digos City', NULL, NULL),
(251, 'Core Gateway College - San Jose City, Nueva Ecija', NULL, NULL),
(252, 'Cotabato Foundation College of Science and Technology', NULL, NULL),
(253, 'Cotabato Medical Foundation College Inc. - Midsayap, Cotabato City', NULL, NULL),
(254, 'Cotabato State University', NULL, NULL),
(255, 'Credo Domine College - Tuguegarao City, Cagayan', NULL, NULL),
(256, 'Dalubhasaan ng Lungsod ng San Pablo - San Pablo City, Laguna', NULL, NULL),
(257, 'Daniel B. PeÃ±a Memorial College Foundation - Tabaco City, Albay', NULL, NULL),
(258, 'Daraga Community College - Daraga, Albay', NULL, NULL),
(259, 'Data Center College of the Philippines - Baguio City Campus', NULL, NULL),
(260, 'Data Center College of the Philippines - Bangued Branch', NULL, NULL),
(261, 'Data Center College of the Philippines - Vigan City Branch', NULL, NULL),
(262, 'Datamex Institute of Computer Technology', NULL, NULL),
(263, 'Davao Central College Inc. - Davao City', NULL, NULL),
(264, 'Davao del Norte State College - Panabo City', NULL, NULL),
(265, 'Davao Doctors\' College - Davao City', NULL, NULL),
(266, 'Davao Medical School Foundation - Davao City', NULL, NULL),
(267, 'Davao Oriental State University - Mati City', NULL, NULL),
(268, 'De La Salle Andres Soriano Memorial College - Toledo City, Cebu', NULL, NULL),
(269, 'De La Salle Araneta University - Malabon', NULL, NULL),
(270, 'De La Salle-College of Saint Benilde - Manila', NULL, NULL),
(271, 'De La Salle John Bosco College - Bislig City', NULL, NULL),
(272, 'De La Salle Lipa - Lipa City', NULL, NULL),
(273, 'De La Salle Medical and Health Sciences Institute - Dasmarinas, Cavite', NULL, NULL),
(274, 'De La Salle University-DasmariÃ±as', NULL, NULL),
(275, 'De La Salle University-Manila (5 campuses and the oldest constituent of De La Salle Philippines)', NULL, NULL),
(276, 'De Ocampo Memorial College - Nagtahan, Sta. Mesa, Manila', NULL, NULL),
(277, 'Dee Hwa Liong College Foundation', NULL, NULL),
(278, 'De Los Santos College', NULL, NULL),
(279, 'De Paul College - Iloilo City', NULL, NULL),
(280, 'Diaz College - Tanjay City, Negros Oriental', NULL, NULL),
(281, 'Dipolog Medical Center College Foundation - Dipolog City', NULL, NULL),
(282, 'Divine Word College of Bangued', NULL, NULL),
(283, 'Divine Word College of Calapan', NULL, NULL),
(284, 'Divine Word College of Laoag', NULL, NULL),
(285, 'Divine Word College of Legazpi', NULL, NULL),
(286, 'Divine Word College of San Jose', NULL, NULL),
(287, 'Divine Word College of Urdaneta', NULL, NULL),
(288, 'Divine Word College of Vigan', NULL, NULL),
(289, 'Divine Word College Seminary - Tagaytay City', NULL, NULL),
(290, 'Divine Word Mission Seminary - Quezon City', NULL, NULL),
(291, 'Divine Word University of Tacloban', NULL, NULL),
(292, 'Dominican College of Iloilo', NULL, NULL),
(293, 'Dominican College of Sta. Rosa, Laguna', NULL, NULL),
(294, 'Dominican College of Tarlac', NULL, NULL),
(295, 'Don Bosco College, Canlubang', NULL, NULL),
(296, 'Don Bosco Technical College', NULL, NULL),
(297, 'Don Bosco Technical Institute', NULL, NULL),
(298, 'Don Bosco Technical Institute, Tarlac', NULL, NULL),
(299, 'Don Bosco Technical Institute, Victorias', NULL, NULL),
(300, 'Don Honorio Ventura Technological State University', NULL, NULL),
(301, 'Don Mariano Marcos Memorial State University', NULL, NULL),
(302, 'Don Mariano Marcos University', NULL, NULL),
(303, 'Dr. Carlos S. Lanting College - Quezon City', NULL, NULL),
(304, 'Dr. Emilio B. Espinosa Sr. Memorial State College of Agriculture and Technology - Mandaon, Masbate', NULL, NULL),
(305, 'Dr. Filemon C. Aguilar Memorial College of Las PiÃ±as', NULL, NULL),
(306, 'Dr. Yanga\'s Colleges Inc. - Bocaue, Bulacan', NULL, NULL),
(307, 'East Asia International System College - Cauayan City, Isabela', NULL, NULL),
(308, 'Easter College, Inc. - Baguio City', NULL, NULL),
(309, 'Eastern Luzon Colleges - Bambang, Nueva Vizcaya', NULL, NULL),
(310, 'Eastern Mindanao College of Technology (EMCOTECH) - Pagadian City', NULL, NULL),
(311, 'Eastern Mindoro Institute of Technology and Sciences (EMA Emits College Philippines)', NULL, NULL),
(312, 'Eastern Samar State University - Borongan City Main Campus', NULL, NULL),
(313, 'Eastern Samar State University - Can-Avid', NULL, NULL),
(314, 'Eastern Samar State University - Guiuan', NULL, NULL),
(315, 'Eastern Samar State University - Maydolong', NULL, NULL),
(316, 'Eastern Samar State University - Salcedo', NULL, NULL),
(317, 'Eastern Tayabas College - Lopez, Quezon', NULL, NULL),
(318, 'Eastern Visayas State University - Tacloban City Main Campus', NULL, NULL),
(319, 'Eastern Visayas State University - Burauen External Campus', NULL, NULL),
(320, 'Eastern Visayas State University - Carigara External Campus', NULL, NULL),
(321, 'Eastern Visayas State University - Dulag External Campus', NULL, NULL),
(322, 'Eastern Visayas State University - Ormoc City Satellite Campus', NULL, NULL),
(323, 'Eastern Visayas State University - Pinabacdao (External Campus in Samar Island)', NULL, NULL),
(324, 'Eastern Visayas State University - Tanauan External Campus', NULL, NULL),
(325, 'Eastwoods Professional College - Balanga, Bataan', NULL, NULL),
(326, 'Eduardo L. Joson Memorial College - Palayan City', NULL, NULL),
(327, 'Educational Systems Technological Institute (ESTI) - Boac, Marinduque', NULL, NULL),
(328, 'Emilio Aguinaldo College - Manila', NULL, NULL),
(329, 'Emmanuel College of Plaridel - Plaridel, Bulacan', NULL, NULL),
(330, 'Enderun Colleges', NULL, NULL),
(331, 'Entrepreneurs School of Asia - Quezon City', NULL, NULL),
(332, 'Escuela de Nuestra SeÃ±ora de La Salette - Dagupan City', NULL, NULL),
(333, 'Eulogio \"Amang\" Rodriguez Institute of Science and Technology (EARIST)', NULL, NULL),
(334, 'Eulogio Amang Rodrigues Institute of Science and Technology - Cavite Campus', NULL, NULL),
(335, 'Eveland Christian College - San Mateo, Isabela', NULL, NULL),
(336, 'Far East Asia Pacific Institute of Tourism Science and Technology, Inc. (Feapitsat Colleges)', NULL, NULL),
(337, 'FEAPITSAT College of Dasmarinas Inc.', NULL, NULL),
(338, 'Far Eastern University', NULL, NULL),
(339, 'Far Eastern University â€“ Institute of Technology (FEU Tech)', NULL, NULL),
(340, 'Far Eastern University â€“ FERN College (FEU Diliman)', NULL, NULL),
(341, 'Far Eastern University â€“ Nicanor Reyes Medical Foundation (FEU NRMF)', NULL, NULL),
(342, 'Far Eastern University â€“ Roosevelt College (FEU Roosevelt)', NULL, NULL),
(343, 'Far Eastern University Alabang (FEU Alabang)', NULL, NULL),
(344, 'Far Eastern College â€“ Silang (FEU Cavite)', NULL, NULL),
(345, 'Far Eastern University â€“ Makati (FEU Makati)', NULL, NULL),
(346, 'FEATI University', NULL, NULL),
(347, 'Felix O. Alfelor Sr. Foundation College - Sipocot, Camarines Sur', NULL, NULL),
(348, 'Fellowship Baptist College -Kabankalan City, Negros Occidental', NULL, NULL),
(349, 'Fernandez College of Arts and Technology - Baliuag, Bulacan', NULL, NULL),
(350, 'Filamer Christian University - Roxas Avenue, Roxas City, Capiz', NULL, NULL),
(351, 'First Asia Institute of Technology and Humanities - Tanauan, Batangas', NULL, NULL),
(352, 'First City Providential College - City of San Jose Del Monte, Bulacan', NULL, NULL),
(353, 'The Fisher Valley College - Taguig', NULL, NULL),
(354, 'Five Star Technical Institute - Tuguegarao City, Cagayan', NULL, NULL),
(355, 'Florencio L. Vargas College (Main Campus, Bagay Road Campus, and Pengue Campus) - Tuguegarao City, Cagayan', NULL, NULL),
(356, 'Forbes College - Legazpi City', NULL, NULL),
(357, 'Foundation University - Dumaguete City', NULL, NULL),
(358, 'Fr. Saturnino Urios University', NULL, NULL),
(359, 'Franciscan College of the Immaculate Conception - Baybay City, Leyte', NULL, NULL),
(360, 'Gallego Foundation Colleges - Cabanatuan City', NULL, NULL),
(361, 'Garcia College of Technology - Kalibo, Aklan', NULL, NULL),
(362, 'Gateways Institute of Science and Technology - Cogeo Campus', NULL, NULL),
(363, 'Gateways Institute of Science and Technology - Fairview Campus', NULL, NULL),
(364, 'Gateways Institute of Science and Technology - Mandaluyong Campus', NULL, NULL),
(365, 'Gateways Institute of Science and Technology - Pasig Campus', NULL, NULL),
(366, 'Gensantos Foundation College - General Santos City', NULL, NULL),
(367, 'Gen. Santos Doctors\' Medical School Foundation Inc. - General Santos City', NULL, NULL),
(368, 'General de Jesus College - San Isidro, Nueva Ecija', NULL, NULL),
(369, 'Global City Innovative College - Bonifacio Global City, Taguig', NULL, NULL),
(370, 'Global Computer INFOTEQ School, Inc. - Cainta, Rizal', NULL, NULL),
(371, 'Global IT Colleges', NULL, NULL),
(372, 'Global IT - Goa, Camarines Sur', NULL, NULL),
(373, 'Global IT - Milaor, Camarines Sur', NULL, NULL),
(374, 'Global IT - Naga City (Main Campus) - Abella St., Naga City', NULL, NULL),
(375, 'Global Reciprocal Colleges - Caloocan', NULL, NULL),
(376, 'Gordon College - Olongapo City', NULL, NULL),
(377, 'Grace Christian College - Quezon City', NULL, NULL),
(378, 'Greatways Technical Institute - Makati', NULL, NULL),
(379, 'Green Valley College Foundation, Inc., City of Koronadal', NULL, NULL),
(380, 'Greenville College - Pasig', NULL, NULL),
(381, 'Golden Gate College - Batangas City', NULL, NULL),
(382, 'Golden Link College Foundation, Inc. - Caloocan', NULL, NULL),
(383, 'Goldenstate College of General Santos City', NULL, NULL),
(384, 'Governor Andres Pascual College - Navotas', NULL, NULL),
(385, 'Governor Mariano E. Villafuerte Community Colleges - Camarines Sur', NULL, NULL),
(386, 'Governor Mariano E. Villafuerte Community College - Siruma', NULL, NULL),
(387, 'Governor Mariano E. Villafuerte Community College - Tinambac', NULL, NULL),
(388, 'Guagua National Colleges - Guagua, Pampanga', NULL, NULL),
(389, 'Guimaras State College', NULL, NULL),
(390, 'Guzman College of Science and Technology - Quiapo, Manila', NULL, NULL),
(391, 'Holy Angel University - Angeles City', NULL, NULL),
(392, 'Holy Name University - (formerly Divine Word College of Tagbilaran)', NULL, NULL),
(393, 'Holy Trinity College - Puerto Princesa City', NULL, NULL),
(394, 'Hua Siong College of Iloilo', NULL, NULL),
(395, 'Holy Cross of Davao College', NULL, NULL),
(396, 'Holy Cross College of Calinan', NULL, NULL),
(397, 'Holy Cross College - Pampanga - Santa Ana, Pampanga', NULL, NULL),
(398, 'iACADEMY - Makati', NULL, NULL),
(399, 'ICCT Colleges (formerly Institute of Creative Computer Technology)', NULL, NULL),
(400, 'ICCT Colleges - Angono', NULL, NULL),
(401, 'ICCT Colleges - Antipolo', NULL, NULL),
(402, 'ICCT Colleges - Binangonan', NULL, NULL),
(403, 'ICCT Colleges - Cainta', NULL, NULL),
(404, 'ICCT Colleges - Cogeo', NULL, NULL),
(405, 'ICCT Colleges - San Mateo', NULL, NULL),
(406, 'ICCT Colleges - Sumulong', NULL, NULL),
(407, 'ICCT Colleges - Taytay', NULL, NULL),
(408, 'Ifugao State University - Lamut, Ifugao', NULL, NULL),
(409, 'IIH College - Novaliches, Quezon City', NULL, NULL),
(410, 'Iligan Capitol College - Iligan City', NULL, NULL),
(411, 'Iligan Medical Center College - Iligan City', NULL, NULL),
(412, 'Ilocos Polytechnic State College', NULL, NULL),
(413, 'Ilocos Sur Polytechnic State College', NULL, NULL),
(414, 'Candon Campus (College of Business Administration and Tourism)', NULL, NULL),
(415, 'Cervantes Campus', NULL, NULL),
(416, 'Narvacan Campus (College of Fisheries)', NULL, NULL),
(417, 'Santiago Campus (College of Industrial Sciences)', NULL, NULL),
(418, 'Sta. Maria Campus (College of Agriculture)', NULL, NULL),
(419, 'Tagudin Campus (College of Education)', NULL, NULL),
(420, 'Iloilo Doctors\' College - Molo, Iloilo City', NULL, NULL),
(421, 'Iloilo Science and Technology University - formerly Western Visayas College of Science and Technology - Iloilo City', NULL, NULL),
(422, 'Iloilo State College of Fisheries Main Campus - Tiwi, Barotac Nuevo, Iloilo', NULL, NULL),
(423, 'Iloilo State College of Fisheries - Barotac Nuevo Campus', NULL, NULL),
(424, 'Iloilo State College of Fisheries - Dingle Campus', NULL, NULL),
(425, 'Iloilo State College of Fisheries - Dumangas Campus', NULL, NULL),
(426, 'Iloilo State College of Fisheries - San Enrique Campus', NULL, NULL),
(427, 'Immaculate Concepcion College - Balayan, Batangas', NULL, NULL),
(428, 'Immaculate Conception International', NULL, NULL),
(429, 'Cabagan Campus', NULL, NULL),
(430, 'San Mariano Campus', NULL, NULL),
(431, 'Immaculate Heart of Mary College', NULL, NULL),
(432, 'Imus Computer College (ICC) - Alabang Muntinlupa', NULL, NULL),
(433, 'Imus Computer College (ICC) - Bacoor Cavite', NULL, NULL),
(434, 'Imus Computer College (ICC) - Carmona Cavite', NULL, NULL),
(435, 'Imus Computer College (ICC) - DasmariÃ±as Cavite', NULL, NULL),
(436, 'Imus Computer College (ICC) - Gen. Mariano Alvarez (GMA) Cavite', NULL, NULL),
(437, 'Imus Computer College (ICC) - Governor\'s Drive-FCIE DasmariÃ±as Cavite', NULL, NULL),
(438, 'Imus Computer College (ICC) - Imus Cavite', NULL, NULL),
(439, 'Imus Computer College (ICC) - Las PiÃ±as', NULL, NULL),
(440, 'Imus Computer College (ICC) - Rosario Cavite', NULL, NULL),
(441, 'Imus Computer College (ICC) - Salawag, Dasmarinas', NULL, NULL),
(442, 'Imus Computer College (ICC) - Silang Cavite', NULL, NULL),
(443, 'Imus Computer College (ICC) - Trece Martires Cavite', NULL, NULL),
(444, 'Imus Institute College', NULL, NULL),
(445, 'Infant Jesus Montessori School College Department - Santiago City', NULL, NULL),
(446, 'Informatics International College (multiple campuses)', NULL, NULL),
(447, 'Information and Communications Technology Academy (iACADEMY)', NULL, NULL),
(448, 'Infotech Development Systems Colleges (IDS Colleges) - Ligao City', NULL, NULL),
(449, 'Infotech Institute of Arts and Sciences', NULL, NULL),
(450, 'Infotech Main - Marcos Highway', NULL, NULL),
(451, 'Infotech - Crossing', NULL, NULL),
(452, 'Infotech - Lagro', NULL, NULL),
(453, 'Infotech - Makati', NULL, NULL),
(454, 'Infotech - Pasig', NULL, NULL),
(455, 'Infotech - Sucat', NULL, NULL),
(456, 'Innovative College of Science in Information Technology (ICST) - Bongabong, Oriental Mindoro', NULL, NULL),
(457, 'Institute of Enterprise Solutions (IES) - Phils, San Jose City, Nueva Ecija', NULL, NULL),
(458, 'Interface Computer College - Manila', NULL, NULL),
(459, 'Interface Computer College- Cabanatuan', NULL, NULL),
(460, 'Interface Computer College - Caloocan', NULL, NULL),
(461, 'Interface Computer College - Cebu', NULL, NULL),
(462, 'Interface Computer College - Davao', NULL, NULL),
(463, 'Interface Computer College - Iloilo', NULL, NULL),
(464, 'International Academy of Film and Television (IAFT) - Lapu-Lapu City', NULL, NULL),
(465, 'International Academy of Management and Economics - Makati', NULL, NULL),
(466, 'International Baptist College (IBC) - Mandaluyong', NULL, NULL),
(467, 'International Electronics and Technical Institute Inc. (IETI) (multiple campuses)', NULL, NULL),
(468, 'International School of Asia and the Pacific - Tuguegarao City, Cagayan', NULL, NULL),
(469, 'International Technological Institute of Arts and Tourism - Ilagan City, Isabela', NULL, NULL),
(470, 'Isabela College of Arts and Technology - Cauayan City, Isabela', NULL, NULL),
(471, 'Isabela Colleges - Cauayan City, Isabela', NULL, NULL),
(472, 'Isabela Colleges of Science & Technology - Roxas, Isabela', NULL, NULL),
(473, 'Isabela State University', NULL, NULL),
(474, 'Isabela State University - Echague Main Campus', NULL, NULL),
(475, 'Isabela State University - Cauayan City Campus', NULL, NULL),
(476, 'Isabela State University - Ilagan City Campus', NULL, NULL),
(477, 'Isabela State University - Cabagan Campus', NULL, NULL),
(478, 'Isabela State University - Roxas Campus', NULL, NULL),
(479, 'Isabela State University - San Mateo Campus', NULL, NULL),
(480, 'Isabela State University - San Mariano Campus', NULL, NULL),
(481, 'Isabela State University - Angadanan Campus', NULL, NULL),
(482, 'Isabela State University - Jones Campus', NULL, NULL),
(483, 'Isabela State University - Palanan Campus', NULL, NULL),
(484, 'Isabela State University - Santiago City Extension Campus', NULL, NULL),
(485, 'J.H. Cerilles State College of Zamboanga del Sur', NULL, NULL),
(486, 'Jake Battaring University Tumauini Campus', NULL, NULL),
(487, 'Jamiatu Muslim Mindanao - Marawi City', NULL, NULL),
(488, 'JE Mondejar Computer College - Tacloban City', NULL, NULL),
(489, 'Jesus Reigns Christian College', NULL, NULL),
(490, 'John B. Lacson Colleges Foundation - Alijis, Bacolod City', NULL, NULL),
(491, 'John B. Lacson Foundation Maritime University - Arevalo, Iloilo City', NULL, NULL),
(492, 'John B. Lacson Foundation Maritime University - Molo, Iloilo City', NULL, NULL),
(493, 'John Paul College - Odiong, Roxas, Oriental Mindoro', NULL, NULL),
(494, 'John Paul College - Davao City', NULL, NULL),
(495, 'John Wesley College - Tuguegarao City, Cagayan', NULL, NULL),
(496, 'Joji Ilagan Career Center Foundation, Inc. - Davao City and General Santos City', NULL, NULL),
(497, 'Jose Abad Santos Memorial School Quezon City', NULL, NULL),
(498, 'Jose C. Feliciano College - Dau, Mabalacat, Pampanga', NULL, NULL),
(499, 'Jose Rizal Memorial State University', NULL, NULL),
(500, 'Jose Rizal Memorial State University - Dapitan City Campus', NULL, NULL),
(501, 'Jose Rizal Memorial State University - Dipolog City Campus', NULL, NULL),
(502, 'Jose Rizal Memorial State University - Katipunan Campus', NULL, NULL),
(503, 'Jose Rizal Memorial State University - Siocon Campus', NULL, NULL),
(504, 'Jose Rizal Memorial State University - Tampilisan Campus', NULL, NULL),
(505, 'Jose Rizal University - Mandaluyong', NULL, NULL),
(506, 'Jose Maria College - Davao City', NULL, NULL),
(507, 'JP Sioson General Hospital and Colleges - Quezon City', NULL, NULL),
(508, 'Kabankalan Catholic College (KCC) - Kabankalan, Negros Occidental', NULL, NULL),
(509, 'Kalayaan College - Quezon City', NULL, NULL),
(510, 'KCI Colleges - Isulan, Sultan Kudarat', NULL, NULL),
(511, 'Kolehiyo ng Subic - Subic, Zambales', NULL, NULL),
(512, 'Kolehiyo Ng Pantukan (KNP) -Pantukan, Davao de Oro', NULL, NULL),
(513, 'La Carlota City College - La Carlota, Negros Occidental', NULL, NULL),
(514, 'La Concordia College - Paco, Manila', NULL, NULL),
(515, 'La Consolacion College - 10th Avenue, Caloocan', NULL, NULL),
(516, 'La Consolacion College - Bais City, Negros Oriental', NULL, NULL),
(517, 'La Consolacion College - Bacolod', NULL, NULL),
(518, 'La Consolacion College - BiÃ±an', NULL, NULL),
(519, 'La Consolacion College - Daet, Camarines Norte', NULL, NULL),
(520, 'La Consolacion College - Iriga City', NULL, NULL),
(521, 'La Consolacion College - Liloan, Cebu', NULL, NULL),
(522, 'La Consolacion College - Mendiola, Manila', NULL, NULL),
(523, 'La Consolacion College - Novaliches, Caloocan', NULL, NULL),
(524, 'La Consolacion College - Pasig', NULL, NULL),
(525, 'La Consolacion College - Tanauan City, Batangas', NULL, NULL),
(526, 'La Consolacion College - Trento, Agusan del Sur', NULL, NULL),
(527, 'La Consolacion University Philippines (formerly University of Regina Carmeli)', NULL, NULL),
(528, 'La Fortuna College - Cabanatuan City', NULL, NULL),
(529, 'La Union Colleges of Nursing, Arts and Sciences', NULL, NULL),
(530, 'La Verdad Christian College - Apalit, Pampanga', NULL, NULL),
(531, 'La Verdad Christian College - Caloocan', NULL, NULL),
(532, 'Lacson College - Pasay', NULL, NULL),
(533, 'Laguna Business College - Sta. Rosa, Laguna', NULL, NULL),
(534, 'Laguna College - San Pablo City', NULL, NULL),
(535, 'Laguna College of Business and Arts - Calamba City', NULL, NULL),
(536, 'Laguna Northwestern College - San Pedro, Laguna', NULL, NULL),
(537, 'Laguna State Polytechnic University - Santa Cruz (Main Campus)', NULL, NULL),
(538, 'Laguna State Polytechnic University - Lopez, Quezon', NULL, NULL),
(539, 'Laguna State Polytechnic University - Los BaÃ±os', NULL, NULL),
(540, 'Laguna State Polytechnic University - San Pablo City', NULL, NULL),
(541, 'Laguna State Polytechnic University - Siniloan (Host)', NULL, NULL),
(542, 'Laguna University - Sta. Cruz, Laguna', NULL, NULL),
(543, 'Lapu-Lapu City College - Lapu-Lapu City', NULL, NULL),
(544, 'La Salle College Antipolo -Antipolo City', NULL, NULL),
(545, 'La Salle University-Ozamiz - Ozamiz City', NULL, NULL),
(546, 'Las PiÃ±as College - Pilar Village, Almanza, Las PiÃ±as', NULL, NULL),
(547, 'Lheny Ganda Santos College - Zaragoza, Nueva Ecija', NULL, NULL),
(548, 'Lemery Colleges - Lemery, Batangas', NULL, NULL),
(549, 'Leyte Institute of Technology - Tacloban City', NULL, NULL),
(550, 'Leyte Normal University - Tacloban City', NULL, NULL),
(551, 'Liceo de Cagayan University - Carmen, Cagayan de Oro City', NULL, NULL),
(552, 'Liceo de Davao - Tagum City', NULL, NULL),
(553, 'Liceo del Verbo Divino - Tacloban City (formerly Divine Word University)', NULL, NULL),
(554, 'LIEMG Language Center - Valenzuela City', NULL, NULL),
(555, 'Ligao Community College - Ligao City', NULL, NULL),
(556, 'Lipa City Colleges - Lipa City', NULL, NULL),
(557, 'Lipa City Public College', NULL, NULL),
(558, 'Loreto Academy', NULL, NULL),
(559, 'Lorma College - San Fernando, La Union', NULL, NULL),
(560, 'Lourdes College - Capistrano St. - Cagayan de Oro City', NULL, NULL),
(561, 'Loyola College of Culion - Culion, Palawan', NULL, NULL),
(562, 'Luna Goco Colleges', NULL, NULL),
(563, 'Luna Goco College - Calapan City', NULL, NULL),
(564, 'Luna Goco College - Pinamalayan, Oriental Mindoro', NULL, NULL),
(565, 'Lyceum-Northwestern University', NULL, NULL),
(566, 'Lyceum of Alabang (not affiliated with Lyceum of the Philippines University)', NULL, NULL),
(567, 'Lyceum of Aparri', NULL, NULL),
(568, 'Lyceum of Cebu - Kalunasan, Cebu City', NULL, NULL),
(569, 'Lyceum of the Philippines University System (multiple campuses)', NULL, NULL),
(570, 'Lyceum of the Philippines University - Batangas City', NULL, NULL),
(571, 'Lyceum of the Philippines University - Calamba City, Laguna', NULL, NULL),
(572, 'Lyceum of the Philippines University - General Trias, Cavite', NULL, NULL),
(573, 'Lyceum of the Philippines University - Intramuros, Manila', NULL, NULL),
(574, 'Lyceum of the Philippines University - Makati - Makati', NULL, NULL),
(575, 'Lyceum of Subic Bay - Subic Bay, Zambales', NULL, NULL),
(576, 'Lyceum of Tuao - Cagayan', NULL, NULL),
(577, 'Maasin City College - Maasin, Southern Leyte', NULL, NULL),
(578, 'Mabalacat College - Rizal St., Dolores, Mabalacat, Pampanga', NULL, NULL),
(579, 'Mach Aviatrix Airhostess Institute - Dumaguete City', NULL, NULL),
(580, 'Mach Aviatrix Flight Institute - Dumaguete City', NULL, NULL),
(581, 'Magsaysay Memorial College - San Narciso, Zambales', NULL, NULL),
(582, 'Ma\'had Kutawato College - Campo Muslim, Cotabato City', NULL, NULL),
(583, 'Maila Rosario College - Tuguegarao City, Cagayan', NULL, NULL),
(584, 'Malayan Colleges Laguna - Cabuyao City', NULL, NULL),
(585, 'Mallig Plains Colleges - Mallig, Isabela', NULL, NULL),
(586, 'Mambog Institute of Technology-Mambog - Pinabacdao, Samar', NULL, NULL),
(587, 'Mandaue City College - Mandaue City, Cebu', NULL, NULL),
(588, 'Manila Adventist Medical Center and Colleges - Pasay', NULL, NULL),
(589, 'Manila Business College - Manila', NULL, NULL),
(590, 'Manila Central University - Caloocan', NULL, NULL),
(591, 'Manila Christian Computer Institute for the Deaf College of Technology - San Mateo, Rizal', NULL, NULL),
(592, 'Manila Tytana Colleges - Pasay', NULL, NULL),
(593, 'Manuel L. Quezon University - (Manila, Quezon City and Penarrubia, Abra)', NULL, NULL),
(594, 'Manuel S. Enverga University Foundation - Lucena City, Quezon', NULL, NULL),
(595, 'Manuel S. Enverga University Foundation - Candelaria, Quezon', NULL, NULL),
(596, 'Manuel S. Enverga University Foundation - Catanauan, Quezon', NULL, NULL),
(597, 'Manuel S. Enverga University Foundation - Sampaloc, Quezon', NULL, NULL),
(598, 'Manuel S. Enverga University Foundation - San Antonio, Quezon', NULL, NULL),
(599, 'Manuel S. Enverga University Foundation College of Law - Lucena City, Quezon', NULL, NULL),
(600, 'MapÃºa University - Manila', NULL, NULL),
(601, 'Marian College - Ipil, Zamboanga Sibugay Province', NULL, NULL),
(602, 'Mariano Marcos State University', NULL, NULL),
(603, 'Marikina Polytechnic College - Marikina', NULL, NULL),
(604, 'Marinduque Midwest College - Gasan, Marinduque', NULL, NULL),
(605, 'Marinduque State University - Main Campus Tanza, Boac, Marinduque', NULL, NULL),
(606, 'Marinduque State University - Gasan, Marinduque', NULL, NULL),
(607, 'Marinduque State University - Matalaba, Sta. Cruz, Marinduque', NULL, NULL),
(608, 'Marinduque State University - Pag-asa, Sta. Cruz, Marinduque', NULL, NULL),
(609, 'Marinduque State University - Torrijos, Marinduque', NULL, NULL),
(610, 'Mariners\' Polytechnic Colleges Foundation', NULL, NULL),
(611, 'Mariners\' - Canaman Campus - Canaman, Camarines Sur', NULL, NULL),
(612, 'Mariners\' - Legazpi City (Main Campus)', NULL, NULL),
(613, 'Mariners\' - Naga Campus - Panganiban Drive, Naga City, Camarines Sur', NULL, NULL),
(614, 'Martinez Colleges, Inc. - Caloocan', NULL, NULL),
(615, 'Mary Chiles College - Manila', NULL, NULL),
(616, 'Mary Johnston College of Nursing - Manila', NULL, NULL),
(617, 'Mary the Queen College (Pampanga) - Guagua, Pampanga', NULL, NULL),
(618, 'Maryhill College - Lucena City, Quezon', NULL, NULL),
(619, 'Masbate Colleges - Masbate City', NULL, NULL),
(620, 'Masters Technological Institute of Mindanao (MTIM) - Iligan City', NULL, NULL),
(621, 'Mater Dei College - Tubigon, Bohol', NULL, NULL),
(622, 'MATS College of Technology - Davao City', NULL, NULL),
(623, 'Maxino College - Dumaguete', NULL, NULL),
(624, 'Medical Colleges of Northern Philippines - PeÃ±ablanca, Cagayan', NULL, NULL),
(625, 'Medina College Inc.', NULL, NULL),
(626, 'Medina College - Ozamiz', NULL, NULL),
(627, 'Medina College - Ipil', NULL, NULL),
(628, 'Medina College - Pagadian', NULL, NULL),
(629, 'Mendero College - Pagadian City', NULL, NULL),
(630, 'MFI Technological Institute', NULL, NULL),
(631, 'Meridian International Business, Arts & Technology College (MINT College) - (Taguig, Pasig & Quezon City)', NULL, NULL),
(632, 'Messiah College - Mandaluyong', NULL, NULL),
(633, 'Metro Business College (formerly Metro Data Computer College) - Pasay', NULL, NULL),
(634, 'Metro Dumaguete College - Dumaguete City', NULL, NULL),
(635, 'Metro Manila College - Kaligayahan, Novaliches, Quezon City', NULL, NULL),
(636, 'Metropolitan Hospital College of Nursing', NULL, NULL),
(637, 'Metropolitan School of Science and Technology - Santiago City', NULL, NULL),
(638, 'Meycauayan College - Bulacan', NULL, NULL),
(639, 'Microcity Computer College Foundation, Inc. - Balanga City', NULL, NULL),
(640, 'Microspan Software Technology, Inc. - Cotabato City', NULL, NULL),
(641, 'Mind And Integrity College - Cabuyao City', NULL, NULL),
(642, 'Mindanao Aeronautical Technical School College of Technology - Davao City', NULL, NULL),
(643, 'Mindanao Autonomous College - Lamitan City, Basilan', NULL, NULL),
(644, 'Mindanao Kokusai Daigaku (Mindanao International College) - Davao City', NULL, NULL),
(645, 'Mindanao Medical Foundation College - Davao City', NULL, NULL),
(646, 'Mindanao Polytechnic College - General Santos City', NULL, NULL),
(647, 'Mindanao Sanitarium and Hospital College - Iligan City', NULL, NULL),
(648, 'Mindanao State University', NULL, NULL),
(649, 'Mindanao State University-Buug Campus', NULL, NULL),
(650, 'Mindanao State University - General Santos', NULL, NULL),
(651, 'Mindanao State University - Iligan Institute of Technology', NULL, NULL),
(652, 'Mindanao State University - Maguindanao (Datu Odin Sinsuat, Maguindanao)', NULL, NULL),
(653, 'Mindanao State University - Marawi', NULL, NULL),
(654, 'Mindanao State University - Naawan', NULL, NULL),
(655, 'Mindanao State University - Sulu', NULL, NULL),
(656, 'Mindanao State University - Tawi-Tawi', NULL, NULL),
(657, 'Mindanao University of Science and Technology - Lapasan, Cagayan de Oro City', NULL, NULL),
(658, 'Mindoro State College of Agriculture and Technology', NULL, NULL),
(659, 'Mindoro State College of Agriculture and Technology - Bongabong, Oriental Mindoro', NULL, NULL),
(660, 'Mindoro State College of Agriculture and Technology - Calapan City', NULL, NULL),
(661, 'Mindoro State College of Agriculture and Technology - Victoria, Oriental Mindoro', NULL, NULL),
(662, 'Miriam College - (Quezon City & Calamba, Laguna)', NULL, NULL),
(663, 'Misamis Oriental State College of Agriculture and Technology - Claveria, Misamis Oriental', NULL, NULL),
(664, 'Misamis Oriental University', NULL, NULL),
(665, 'Misamis University', NULL, NULL),
(666, 'Mondriaan Aura College - Subic Bay', NULL, NULL),
(667, 'Monkayo College of Arts of Science and Technology (MONCAST)', NULL, NULL),
(668, 'Montessori Professional College International (MPCI)', NULL, NULL),
(669, 'Montessori Professional College International - Antipolo', NULL, NULL),
(670, 'Montessori Professional College International - Bacoor', NULL, NULL),
(671, 'Montessori Professional College International - Caloocan', NULL, NULL),
(672, 'Montessori Professional College International - DasmariÃ±as', NULL, NULL),
(673, 'Montessori Professional College International - Imus', NULL, NULL),
(674, 'Montessori Professional College International - Largo', NULL, NULL),
(675, 'Montessori Professional College International - Makati', NULL, NULL),
(676, 'Montessori Professional College International - Marikina', NULL, NULL),
(677, 'Montessori Professional College International - MuÃ±oz', NULL, NULL),
(678, 'Montessori Professional College International - Pasay', NULL, NULL),
(679, 'Montessori Professional College International - Pasig', NULL, NULL),
(680, 'Montessori Professional College International - Recto', NULL, NULL),
(681, 'Montessori Professional College International - Calamba', NULL, NULL),
(682, 'Mount Carmel College - Baler, Aurora', NULL, NULL),
(683, 'Mount Carmel College - Escalante City, Negros Occidental', NULL, NULL),
(684, 'Mountain Province State Polytechnic College - Bontoc, Mountain Province', NULL, NULL),
(685, 'Mountain View College - Mt. Nebo, Valencia City, Bukidnon', NULL, NULL),
(686, 'Mystical Rose College of Science and Technology - Mangatarem, Pangasinan', NULL, NULL),
(687, 'Naga College Foundation - Naga City', NULL, NULL),
(688, 'Naga View Adventist College - Naga City', NULL, NULL),
(689, 'NAMEI Polytechnic Institute - Mandaluyong', NULL, NULL),
(690, 'National Christian Life College - (multiple campuses)', NULL, NULL),
(691, 'National College of Business and Arts', NULL, NULL),
(692, 'National College of Business and Arts - Cubao, Quezon City', NULL, NULL),
(693, 'National College of Business and Arts - Fairview, Quezon City', NULL, NULL),
(694, 'National College of Business and Arts - Taytay, Rizal', NULL, NULL),
(695, 'National College of Science and Technology - DasmariÃ±as City, Cavite', NULL, NULL),
(696, 'National Police College Regional Training School - Cauayan City, Isabela', NULL, NULL),
(697, 'National Teachers College - Quiapo, Manila', NULL, NULL),
(698, 'National University', NULL, NULL),
(699, 'Naval State University', NULL, NULL),
(700, 'Naval State University - Main Campus, Naval', NULL, NULL),
(701, 'Naval State University - Biliran Campus', NULL, NULL),
(702, 'Navotas Polytechnic College', NULL, NULL),
(703, 'Nazarenus College and Hospital Foundation, Inc. - Bulacan', NULL, NULL),
(704, 'Negros College - Ayungon, Negros Oriental', NULL, NULL),
(705, 'Negros Maritime College Foundation, Inc. - Sibulan, Negros Oriental', NULL, NULL),
(706, 'Negros Navigation Oceanlink Institute - Pier 2 North Harbor, Tondo, Manila', NULL, NULL),
(707, 'Negros Oriental State University', NULL, NULL),
(708, 'Negros Oriental State University - Main Campus, Dumaguete City', NULL, NULL),
(709, 'Negros Oriental State University - Bajumpandan Campus, Dumaguete City', NULL, NULL),
(710, 'Negros Oriental State University - Bais Campuses', NULL, NULL),
(711, 'Negros Oriental State University - Bayawan-Sta. Catalina Campus', NULL, NULL),
(712, 'Negros Oriental State University - Guihulngan Campus', NULL, NULL),
(713, 'Negros Oriental State University - Mabinay Campus', NULL, NULL),
(714, 'Negros Oriental State University - Pamplona Farm', NULL, NULL),
(715, 'Negros Oriental State University - Siaton Campus', NULL, NULL),
(716, 'New Era University', NULL, NULL),
(717, 'New Era University - Batangas', NULL, NULL),
(718, 'New Era University - General Santos City', NULL, NULL),
(719, 'New Era University - Pampanga (San Fernando, Pampanga)', NULL, NULL),
(720, 'New Era University - Quezon City', NULL, NULL),
(721, 'Northeast Luzon Adventist College - Alicia, Isabela', NULL, NULL),
(722, 'Northeastern College - Santiago City', NULL, NULL),
(723, 'Northeastern Mindanao Colleges - Surigao City', NULL, NULL),
(724, 'Northlink Technological college - Panabo City', NULL, NULL),
(725, 'Northwest Samar State University', NULL, NULL),
(726, 'Northwest Samar State University - Main Campus, Calbayog City', NULL, NULL),
(727, 'Northwest Samar State University - San Jorge Campus', NULL, NULL),
(728, 'Northwestern Visayan Colleges - Kalibo, Aklan', NULL, NULL),
(729, 'Northwestern University (Philippines) - Laoag City', NULL, NULL),
(730, 'North Davao College Tagum Foundation - Tagum City', NULL, NULL),
(731, 'North Luzon Philippines State College - Candon City, Ilocos Sur', NULL, NULL),
(732, 'Northern Cagayan Colleges Foundation - Ballesteros, Cagayan', NULL, NULL),
(733, 'Northern Christian College - Laoag City', NULL, NULL),
(734, 'Northern Davao Colleges - Panabo City', NULL, NULL),
(735, 'Northern Luzon Adventist College - Sison, Pangasinan', NULL, NULL),
(736, 'Northern Negros State College of Science and Technology', NULL, NULL),
(737, 'Northern Negros State College of Science and Technology - Main Campus, Sagay City', NULL, NULL),
(738, 'Northern Negros State College of Science and Technology - Cadiz Campus', NULL, NULL),
(739, 'Northern Negros State College of Science and Technology - Calatrava Campus', NULL, NULL),
(740, 'Northern Negros State College of Science and Technology - Escalante Campus', NULL, NULL),
(741, 'Northern Philippines College for Maritime Science and Technology, Inc.', NULL, NULL),
(742, 'Northern Samar Colleges - Catarman, Northern Samar', NULL, NULL),
(743, 'Northern Zambales College - Masinloc, Zambales', NULL, NULL),
(744, 'Notre Dame of Dadiangas University - General Santos', NULL, NULL),
(745, 'Notre Dame of Isulan', NULL, NULL);
INSERT INTO `universities` (`id`, `name`, `created_at`, `updated_at`) VALUES
(746, 'Notre Dame of Jolo College - Jolo, Sulu', NULL, NULL),
(747, 'Notre Dame of Kidapawan College', NULL, NULL),
(748, 'Notre Dame of Marbel University - Koronadal', NULL, NULL),
(749, 'Notre Dame of Midsayap College - Midsayap, Cotabato', NULL, NULL),
(750, 'Notre Dame of Tacurong College', NULL, NULL),
(751, 'Notre Dame - Siena College of Polomolok', NULL, NULL),
(752, 'Notre Dame University - Cotabato City', NULL, NULL),
(753, 'Nueva Ecija University of Science and Technology', NULL, NULL),
(754, 'Nueva Vizcaya State University', NULL, NULL),
(755, 'Nueva Vizcaya State University - Main Campus, Bayombong', NULL, NULL),
(756, 'Nueva Vizcaya State University - Bambang Campus', NULL, NULL),
(757, 'Nuevo Zamboanga College - Zamboanga City', NULL, NULL),
(758, 'Oas Community College - Oas, Albay', NULL, NULL),
(759, 'Occidental Mindoro State College - San Jose, Occidental Mindoro', NULL, NULL),
(760, 'Olivarez College', NULL, NULL),
(761, 'Olivarez College - ParaÃ±aque', NULL, NULL),
(762, 'Olivarez College - Tagaytay', NULL, NULL),
(763, 'Operation Brotherhood Montessori Center (OB Montessori Center) (Short name: OBMC)', NULL, NULL),
(764, 'OBMC - Greenhills, San Juan', NULL, NULL),
(765, 'OBMC - Santa Ana, Manila', NULL, NULL),
(766, 'OBMC - Las PiÃ±as, ParaÃ±aque', NULL, NULL),
(767, 'OBMC - Angeles, Pampanga', NULL, NULL),
(768, 'OBMC - Fairview, Quezon City', NULL, NULL),
(769, 'Opol Community College - Opol, Misamis Oriental', NULL, NULL),
(770, 'OsmeÃ±a Colleges - Masbate City', NULL, NULL),
(771, 'Our Lady of Assumption College - San Pedro, Laguna (Main)', NULL, NULL),
(772, 'Our Lady of Assumption College - Santa Rosa City', NULL, NULL),
(773, 'Our Lady of Assumption College Cabuyao (Main) - Mamatid, Cabuyao City', NULL, NULL),
(774, 'Our Lady of Assumption College Cabuyao (Annex) - Mamatid, Cabuyao City', NULL, NULL),
(775, 'Our Lady of Assumption College - Tanauan, Batangas', NULL, NULL),
(776, 'Our Lady of Fatima University', NULL, NULL),
(777, 'Our Lady of Fatima University - Antipolo City, Rizal', NULL, NULL),
(778, 'Our Lady of Fatima University - City of San Fernando, Pampanga', NULL, NULL),
(779, 'Our Lady of Fatima University - Santa Rosa, Laguna', NULL, NULL),
(780, 'Our Lady of Fatima University - Quezon City', NULL, NULL),
(781, 'Our Lady of Fatima University - Valenzuela City', NULL, NULL),
(782, 'Our Lady of Fatima University - Sta. Rosa City, Laguna', NULL, NULL),
(783, 'Our Lady of Fatima University Nueva Ecija Doctors Colleges, Inc. - Cabanatuan City, Nueva Ecija', NULL, NULL),
(784, 'Our Lady of Guadalupe Colleges - Mandaluyong', NULL, NULL),
(785, 'Our Lady of Lourdes College - Valenzuela City', NULL, NULL),
(786, 'Our Lady of Manaoag College - Manaoag, Pangasinan', NULL, NULL),
(787, 'Our Lady of Mercy College - Borongan City', NULL, NULL),
(788, 'Our Lady of Perpetual Succor College - Marikina', NULL, NULL),
(789, 'Our Lady of the Pillar College - Cauayan City, Isabela', NULL, NULL),
(790, 'Our Lady of the Pillar College - San Manuel, Isabela', NULL, NULL),
(791, 'Pacific InterContinental College (PIC), Inc. - Las PiÃ±as', NULL, NULL),
(792, 'Palawan State University', NULL, NULL),
(793, 'Palompon Institute of Technology - Palompon, Leyte', NULL, NULL),
(794, 'Pamantasan ng Cabuyao - Cabuyao, Laguna', NULL, NULL),
(795, 'Pamantasan ng Lungsod ng Maynila Main Campus', NULL, NULL),
(796, 'Pamantasan ng Lungsod ng Maynila, District Colleges', NULL, NULL),
(797, 'Pamantasan ng Lungsod ng Marikina', NULL, NULL),
(798, 'Pamantasan ng Lungsod ng Marikina - H. Bautista Campus', NULL, NULL),
(799, 'Pamantasan ng Lungsod ng Marikina - J.P. Rizal Campus', NULL, NULL),
(800, 'Pamantasan ng Lungsod ng Muntinlupa', NULL, NULL),
(801, 'Pamantasan ng Lungsod ng Pasay', NULL, NULL),
(802, 'Pamantasan ng Lungsod ng Pasig', NULL, NULL),
(803, 'Pamantasan ng Lungsod ng Valenzuela', NULL, NULL),
(804, 'Pamantasan ng Montalban - Montalban, Rizal', NULL, NULL),
(805, 'Pambansa-Demokratikong Paaralan', NULL, NULL),
(806, 'Pambayang Kolehiyo ng Mauban - Mauban, Quezon', NULL, NULL),
(807, 'Pampanga Agricultural College - Magalang, Pampanga', NULL, NULL),
(808, 'Pampanga Colleges - Macabebe, Pampanga', NULL, NULL),
(809, 'Pangasinan State University', NULL, NULL),
(810, 'Pangasinan State University - Asingan', NULL, NULL),
(811, 'Pangasinan State University - Bayambang', NULL, NULL),
(812, 'Pangasinan State University - Binmaley', NULL, NULL),
(813, 'Pangasinan State University - Graduate School', NULL, NULL),
(814, 'Pangasinan State University - Infanta', NULL, NULL),
(815, 'Pangasinan State University - Lingayen', NULL, NULL),
(816, 'Pangasinan State University - San Carlos City', NULL, NULL),
(817, 'Pangasinan State University - Sta. Maria', NULL, NULL),
(818, 'Pangasinan State University - Urdaneta City', NULL, NULL),
(819, 'Panpacific University North Philippines - Tayug', NULL, NULL),
(820, 'Panpacific University - Urdaneta City', NULL, NULL),
(821, 'Panay Technological College - Kalibo, Aklan', NULL, NULL),
(822, 'Partido State University', NULL, NULL),
(823, 'Partido State University - Goa, Camarines Sur (Main Campus)', NULL, NULL),
(824, 'Partido State University - Lagonoy, Camarines Sur', NULL, NULL),
(825, 'Partido State University - San Jose, Camarines Sur', NULL, NULL),
(826, 'Partido State University - Tinambac, Camarines Sur', NULL, NULL),
(827, 'Pasig Catholic College - Pasig', NULL, NULL),
(828, 'Passi Trade School - Passi City', NULL, NULL),
(829, 'Pateros Technological College - Pateros, Metro Manila', NULL, NULL),
(830, 'Patria Sable Corpus College - Santiago City', NULL, NULL),
(831, 'PATTS College of Aeronautics', NULL, NULL),
(832, 'PeÃ±a de Francia College - Naga (condemned campus)', NULL, NULL),
(833, 'Philippine Best Training System Colleges - Binangonan, Rizal', NULL, NULL),
(834, 'Philippine Cambridge School - DasmariÃ±as, Cavite', NULL, NULL),
(835, 'Philippine Cambridge School - GMA, Cavite', NULL, NULL),
(836, 'Philippine Cambridge School - Imus, Cavite', NULL, NULL),
(837, 'Philippine Cambridge School - Noveleta, Cavite', NULL, NULL),
(838, 'Philippine Central Islands College (PCIC)', NULL, NULL),
(839, 'Philippine Christian University', NULL, NULL),
(840, 'Philippine Countryville College, Inc. (PCC) - P2B- Panadtalan, Maramag, Bukidnon', NULL, NULL),
(841, 'Philippine College of Criminology (PCCr) - Manila', NULL, NULL),
(842, 'Philippine College of Health Sciences, Inc. - Manila', NULL, NULL),
(843, 'Philippine College of Technology - Davao City', NULL, NULL),
(844, 'Philippine College of Technology - Bajada', NULL, NULL),
(845, 'Philippine College of Technology - Calinan', NULL, NULL),
(846, 'Philippine International College', NULL, NULL),
(847, 'Philippine Law Enforcement College - Tuguegarao City, Cagayan', NULL, NULL),
(848, 'Philippine Merchant Marine Academy - San Narciso, Zambales', NULL, NULL),
(849, 'Philippine Military Academy - Baguio City', NULL, NULL),
(850, 'Philippine National Police Academy - Silang, Cavite', NULL, NULL),
(851, 'Philippine Nautical Technological College Intramuros Manila - Dasmarinas Cavite', NULL, NULL),
(852, 'Philippine Nazarene College - La Trinidad, Benguet', NULL, NULL),
(853, 'Philippine Normal University', NULL, NULL),
(854, 'Philippine Normal University - Manila (Main Campus)', NULL, NULL),
(855, 'Philippine Normal University - North Luzon (Alicia, Isabela)', NULL, NULL),
(856, 'Philippine Normal University - Visayas (Cadiz, Negros Occidental)', NULL, NULL),
(857, 'Philippine Normal University - South Luzon (Lopez, Quezon)', NULL, NULL),
(858, 'Philippine Normal University - Mindanao (Prosperidad, Agusan del Sur)', NULL, NULL),
(859, 'Philippine Rehabilitation Institute - Quezon City', NULL, NULL),
(860, 'Philippine School of Business Administration - Manila (Main Campus)', NULL, NULL),
(861, 'Philippine School of Business Administration - Quezon City', NULL, NULL),
(862, 'Philippine State College of Aeronautics - Villamor Air Base, Pasay (Main Campus)', NULL, NULL),
(863, 'Philippine State College of Aeronautics - Basa Air Base, Floridablanca, Pampanga', NULL, NULL),
(864, 'Philippine State College of Aeronautics - Clark Air Base, Angeles City, Pampanga', NULL, NULL),
(865, 'Philippine State College of Aeronautics - Fernando Air Base, Lipa City, Batangas', NULL, NULL),
(866, 'Philippine State College of Aeronautics - Mactan Benito-Ebuen Air Base, Cebu', NULL, NULL),
(867, 'Philippine Technological Institute of Science Arts and Trade - Central Inc., GMA, Cavite', NULL, NULL),
(868, 'Philippine Technological Institute of Science Arts and Trade - Central Inc., Sta. Rosa, Laguna', NULL, NULL),
(869, 'Philippine Technological Institute of Science Arts and Trade - Central Inc., Tanay, Rizal', NULL, NULL),
(870, 'Philippine Women\'s University', NULL, NULL),
(871, 'Philippine Women\'s College of Davao', NULL, NULL),
(872, 'Philippine Women\'s University - CDCEC Calamba Campus', NULL, NULL),
(873, 'Philippine Women\'s University - Surigao City Campus', NULL, NULL),
(874, 'Philtech Institute of Arts and Technology Inc. - Gumaca, Quezon', NULL, NULL),
(875, 'Philtech Institute of Arts and Technology Inc. - Lucena City', NULL, NULL),
(876, 'Pilar College - Zamboanga City', NULL, NULL),
(877, 'Pilgrim University (formerly Pilgrim Christian College) - Cagayan de Oro City', NULL, NULL),
(878, 'Pinabacdao State University - Mambog, Pinabacdao, Samar', NULL, NULL),
(879, 'Pines City Colleges - Baguio City', NULL, NULL),
(880, 'PLT College Inc. - Bayombong, Nueva Vizcaya', NULL, NULL),
(881, 'PMI Colleges (Philippine Maritime Institute)', NULL, NULL),
(882, 'PMI Colleges Bohol', NULL, NULL),
(883, 'PMI Colleges Manila', NULL, NULL),
(884, 'PMI Colleges Quezon City', NULL, NULL),
(885, 'PMMS - Las PiÃ±as', NULL, NULL),
(886, 'Polangui Community College - Polangui, Albay', NULL, NULL),
(887, 'Polytechnic College of Davao Del Sur Inc. - Digos City, Davao Del Sur', NULL, NULL),
(888, 'Polytechnic State University of Bicol - Nabua, Camarines Sur', NULL, NULL),
(889, 'Polytechnic University of the Philippines System (11 branches and 11 campuses)', NULL, NULL),
(890, 'Queen of Apostles College Seminary (QACS) - Taguum City', NULL, NULL),
(891, 'Quezon City Polytechnic University', NULL, NULL),
(892, 'Quezon City Polytechnic University - Batasan Hills', NULL, NULL),
(893, 'Quezon City Polytechnic University - San Bartolome', NULL, NULL),
(894, 'Quezon City Polytechnic University - San Francisco', NULL, NULL),
(895, 'Quezon Colleges of the North - Ballesteros, Cagayan', NULL, NULL),
(896, 'Quezon Colleges of Southern Philippines - Tacurong City', NULL, NULL),
(897, 'Quezon Memorial Institute of Siquijor, Siquijor', NULL, NULL),
(898, 'Quirino State University - Cabarroguis, Quirino', NULL, NULL),
(899, 'Quirino State University - Diffun, Quirino', NULL, NULL),
(900, 'Quirino State University - Maddela, Quirino', NULL, NULL),
(901, 'Ramon Magsaysay Memorial Colleges - General Santos City', NULL, NULL),
(902, 'Ramon Magsaysay Technological University â€“ multiple campuses', NULL, NULL),
(903, 'RC Al-Khwarizmi International College - Marawi City', NULL, NULL),
(904, 'Red Aeronautics and Technological Institute Inc. - Silay City', NULL, NULL),
(905, 'Red Link Science Institute & Technology of Laguna - Bay, Laguna (Main Campus)', NULL, NULL),
(906, 'Red Link Science Institute & Technology of Calamba (Annex Campus)', NULL, NULL),
(907, 'Regis Marie College', NULL, NULL),
(908, 'Remedios T. Romualdez Memorial Schools - Makati Medical Center', NULL, NULL),
(909, 'Republic Central Colleges - Angeles City', NULL, NULL),
(910, 'Riverside College - Bacolod City', NULL, NULL),
(911, 'Rizal College', NULL, NULL),
(912, 'Rizal College of Laguna - Calamba (Main Campus)', NULL, NULL),
(913, 'Rizal College of Taal - Taal, Batangas (Annex Campus)', NULL, NULL),
(914, 'Rizal Memorial Colleges - Davao City', NULL, NULL),
(915, 'Rizal Memorial Institute - Dapitan City', NULL, NULL),
(916, 'Rizal Technological University â€“ multiple campuses', NULL, NULL),
(917, 'Rogationist College - Silang, Cavite', NULL, NULL),
(918, 'Romblon State University â€“ multiple campuses', NULL, NULL),
(919, 'Romeo Padilla University - Urdaneta City, Pangasinan', NULL, NULL),
(920, 'Roosevelt College System â€“ multiple campuses', NULL, NULL),
(921, 'Roosevelt College Marikina', NULL, NULL),
(922, 'Roosevelt College Quirino', NULL, NULL),
(923, 'Royal Christian College', NULL, NULL),
(924, 'Sacred Heart College - Lucena City, Quezon', NULL, NULL),
(925, 'Sacred Heart College - Tacloban City', NULL, NULL),
(926, 'St. Anthony College Calapan City, Inc., (formerly St. Anthony College of Science and Technology, Inc.) - Calapan City, Oriental Mindoro', NULL, NULL),
(927, 'St. Anthony College of Nursing, Inc. - Roxas City', NULL, NULL),
(928, 'St. Anthony\'s College - San Jose, Antique', NULL, NULL),
(929, 'St. Anthony\'s College - Santa Ana, Cagayan', NULL, NULL),
(930, 'Saint Bridget College - Batangas City', NULL, NULL),
(931, 'Saint Clare College - Region 2, Cauayan City, Isabela', NULL, NULL),
(932, 'Saint Columban College - Pagadian City', NULL, NULL),
(933, 'San Jose Community College - Malilipot, Albay', NULL, NULL),
(934, 'St. Dominic College of Asia - Bacoor, Cavite', NULL, NULL),
(935, 'St. Dominic College - Basco, Batanes', NULL, NULL),
(936, 'Saint Ferdinand College - Ilagan City, Isabela Main Campus', NULL, NULL),
(937, 'Saint Ferdinand College - Cabagan, Isabela', NULL, NULL),
(938, 'Saint Francis of Assisi College System - Las PiÃ±as', NULL, NULL),
(939, 'Campuses: Alabang, DasmariÃ±as, Taguig, BiÃ±an, Pamplona, Bacoor, Los BaÃ±os', NULL, NULL),
(940, 'Saint Francis Institute of Computer Studies - San Pedro, Laguna', NULL, NULL),
(941, 'Campuses: Cabagan, Isabela', NULL, NULL),
(942, 'Saint Gabriel College - Kalibo, Aklan', NULL, NULL),
(943, 'St. Ignatius Technical Institute of Business and Arts - Sta. Rosa, Laguna', NULL, NULL),
(944, 'St. James College of ParaÃ±aque - Paranaque City', NULL, NULL),
(945, 'St. James College of Quezon City', NULL, NULL),
(946, 'Saint John and Paul Colleges - Calamba City, Laguna', NULL, NULL),
(947, 'Saint John Colleges - Calamba City', NULL, NULL),
(948, 'St. Joseph College Cavite City', NULL, NULL),
(949, 'Saint Joseph College Maasin City', NULL, NULL),
(950, 'St. Joseph College-Olongapo, Inc. - Olongapo City', NULL, NULL),
(951, 'Saint Joseph\'s College - Montalban, Rizal', NULL, NULL),
(952, 'Saint Joseph\'s College - Quezon City', NULL, NULL),
(953, 'Saint Jude College - Manila', NULL, NULL),
(954, 'Saint Jude Thaddeus Institute of Technology - Surigao City', NULL, NULL),
(955, 'St. Linus University (St. Linus Online Institute) - Paniqui, Tarlac', NULL, NULL),
(956, 'Saint Louis College - San Fernando City, La Union', NULL, NULL),
(957, 'Saint Louis University, Baguio City Main Campus - Bonifacio St., Baguio City', NULL, NULL),
(958, 'Gonzaga Campus - General Luna St., Baguio City', NULL, NULL),
(959, 'Maryheights Campus - Bakakeng, Baguio City', NULL, NULL),
(960, 'Navy Base Campus - Navy Base, Baguio City', NULL, NULL),
(961, 'St. Mary\'s Angels College of Pampanga - Santa Ana, Pampanga', NULL, NULL),
(962, 'St. Mary\'s College of Meycauayan - Meycauayan City', NULL, NULL),
(963, 'Saint Mary\'s College of Quezon City', NULL, NULL),
(964, 'Saint Mary\'s University of Bayombong, Nueva Vizcaya', NULL, NULL),
(965, 'St. Mary\'s College of Baganga - Baganga, Davao Oriental', NULL, NULL),
(966, 'St. Mary\'s College of Baliuag - Bulacan', NULL, NULL),
(967, 'St. Mary\'s College of Boac - Marinduque', NULL, NULL),
(968, 'St. Mary\'s College of Borongan - Eastern, Samar', NULL, NULL),
(969, 'St. Mary\'s College of Catbalogan - Catbalogan, Samar (formerly Sacred Heart College)', NULL, NULL),
(970, 'St. Mary\'s College of Labason - Labason, Zamboanga del Norte', NULL, NULL),
(971, 'St. Mary\'s College of Tagum - Tagum City, Davao', NULL, NULL),
(972, 'St. Mary\'s College of Toledo - Toledo City, Cebu', NULL, NULL),
(973, 'Saint Mary\'s University of Cebu - Cebu City', NULL, NULL),
(974, 'St. Matthew College - San Mateo, Rizal', NULL, NULL),
(975, 'Saint Michael College of Hindang Leyte - Hindang, Leyte', NULL, NULL),
(976, 'Saint Michael College of Caraga - Nasipit, Agusan del Norte', NULL, NULL),
(977, 'Saint Michael\'s College - Cantilan, Surigao del Sur', NULL, NULL),
(978, 'Saint Michael\'s College - Guagua, Pampanga', NULL, NULL),
(979, 'St. Michael\'s College - Iligan City', NULL, NULL),
(980, 'St. Nicolas College of Business and Technology - San Fernando, Pampanga', NULL, NULL),
(981, 'St. Paul College of Ilocos Sur - Bantay, Ilocos Sur', NULL, NULL),
(982, 'St. Paul College of Makati', NULL, NULL),
(983, 'St. Paul College of Pasig', NULL, NULL),
(984, 'St. Paul College of ParaÃ±aque', NULL, NULL),
(985, 'St. Paul College of Technology - Tarlac City', NULL, NULL),
(986, 'St. Paul University System (7 campuses)', NULL, NULL),
(987, 'Saint Pedro Poveda College', NULL, NULL),
(988, 'St. Peter\'s College - Balingasag', NULL, NULL),
(989, 'St. Peter\'s College - Iligan', NULL, NULL),
(990, 'St. Peter\'s College - Ormoc', NULL, NULL),
(991, 'St. Peter\'s College - Toril (Davao City)', NULL, NULL),
(992, 'St. Peter College of Technology - Capas, Tarlac', NULL, NULL),
(993, 'St. Rita College - Manila', NULL, NULL),
(994, 'St. Rita College - ParaÃ±aque City', NULL, NULL),
(995, 'St. Rita\'s College - Balingasag', NULL, NULL),
(996, 'St. Scholastica\'s Academy - City of San Fernando, Pampanga', NULL, NULL),
(997, 'St. Scholastica\'s College Manila', NULL, NULL),
(998, 'St. Scholastica\'s College - Tacloban', NULL, NULL),
(999, 'Sta. Teresa College - Bauan, Batangas', NULL, NULL),
(1000, 'Saint Theresa\'s College of Cebu City', NULL, NULL),
(1001, 'Saint Theresa\'s College of Quezon City', NULL, NULL),
(1002, 'St. Vincent College - Dipolog City', NULL, NULL),
(1003, 'Samar Island University (formerly Samar College, Samar Junior College)', NULL, NULL),
(1004, 'San Agustin Institute of Technology', NULL, NULL),
(1005, 'San Beda University System campuses:', NULL, NULL),
(1006, 'San Beda College Alabang - Alabang Hills Village, Muntinlupa', NULL, NULL),
(1007, 'San Beda University Manila - Mendiola, Manila', NULL, NULL),
(1008, 'San Beda University Rizal - Taytay, Rizal', NULL, NULL),
(1009, 'San Carlos College - San Carlos City, Pangasinan', NULL, NULL),
(1010, 'San Isidro College - Malaybalay City, Bukidnon', NULL, NULL),
(1011, 'San Jose Christian Colleges - San Jose City, Nueva Ecija', NULL, NULL),
(1012, 'San Jose Community College - Malilipot, Albay', NULL, NULL),
(1013, 'Saint Joseph Institute of Technology - Butuan City, Agusan del Norte', NULL, NULL),
(1014, 'San Juan de Dios College - Pasay', NULL, NULL),
(1015, 'San Lorenzo College - Kalibo, Aklan', NULL, NULL),
(1016, 'San Pablo Colleges - San Pablo City', NULL, NULL),
(1017, 'San Pedro College - Davao City', NULL, NULL),
(1018, 'San Pedro College of Business Administration - San Pedro, Laguna', NULL, NULL),
(1019, 'San Sebastian College - Recoletos de Manila - (Manila)', NULL, NULL),
(1020, 'San Sebastian College - Recoletos de Cavite - (Cavite City)', NULL, NULL),
(1021, 'Sancta Maria, Mater et Regina, Seminarium - Roxas City, Capiz', NULL, NULL),
(1022, 'Sangguniang Kabataan University', NULL, NULL),
(1023, 'Santa Cruz Institute - Sta. Cruz, Marinduque', NULL, NULL),
(1024, 'Santa Isabel College Manila - Manila', NULL, NULL),
(1025, 'Santiago City Colleges - Santiago City', NULL, NULL),
(1026, 'Siargao Island Institute of Technology - Dapa, Siargao Island, Surigao del Norte', NULL, NULL),
(1027, 'Sibonga Community College - Sibonga, Cebu', NULL, NULL),
(1028, 'Siena College of Taytay', NULL, NULL),
(1029, 'Siena College of Quezon City', NULL, NULL),
(1030, 'Sierra College - Bayombong, Nueva Vizcaya', NULL, NULL),
(1031, 'Silliman University - Dumaguete City', NULL, NULL),
(1032, 'Siquijor State College (SSC) - North Poblacion, 6226 Larena, Siquijor', NULL, NULL),
(1033, 'Siquijor State College - Lazi Campus - 6228 Lazi, Siquijor', NULL, NULL),
(1034, 'SISTECH College - Santiago City', NULL, NULL),
(1035, 'Skill Power Institute - Antipolo, Rizal', NULL, NULL),
(1036, 'Sorsogon State University', NULL, NULL),
(1037, 'South Forbes City College - South Forbes Golf City, Silang, Cavite', NULL, NULL),
(1038, 'South Ilocandia College of Arts and Technology - Aringay, La Union', NULL, NULL),
(1039, 'South Philippine Adventist College - Davao City', NULL, NULL),
(1040, 'South SEED LPDH College - Las PiÃ±as', NULL, NULL),
(1041, 'Southeast Asia Interdisciplinary Development Institute - Antipolo', NULL, NULL),
(1042, 'Southeastern College of Arts and Trades - Santiago City', NULL, NULL),
(1043, 'Southern Baptist College - Mlang, Cotabato', NULL, NULL),
(1044, 'Southern Christian College - Midsayap, Cotabato', NULL, NULL),
(1045, 'Southern Isabela Colleges', NULL, NULL),
(1046, 'Southern Isabela Colleges of Arts and Trades (TESDA) - Santiago City', NULL, NULL),
(1047, 'Southern Leyte Business College - Maasin City', NULL, NULL),
(1048, 'Southern Leyte State University - Main Campus, Sogod, Southern Leyte', NULL, NULL),
(1049, 'Southern Leyte State University - Bontoc Campus, San Ramon, Bontoc, Southern Leyte', NULL, NULL),
(1050, 'Southern Leyte State University - Hinunangan Campus, Hinunangan, Southern Leyte', NULL, NULL),
(1051, 'Southern Leyte State University - San Juan Campus, San Juan, Southern Leyte', NULL, NULL),
(1052, 'Southern Leyte State University - Tomas Oppus Campus, San Isidro, Tomas Oppus, Southern Leyte', NULL, NULL),
(1053, 'Southern Luzon State University (multiple campuses)', NULL, NULL),
(1054, 'Southern Luzon Technological College Foundation Inc. - Legazpi City, Albay', NULL, NULL),
(1055, 'Southern Mindanao Colleges', NULL, NULL),
(1056, 'Southern Philippine Academy College Inc. (SPA, College Inc.) - Datu Piang, Maguindanao', NULL, NULL),
(1057, 'Southern Philippines Agri-business and Marine and Aquatic School of Technology (SPAMAST) - Digos City', NULL, NULL),
(1058, 'Southern Philippines College - Julio Pacana St., Licuan, Cagayan de Oro City', NULL, NULL),
(1059, 'Southland College - Kabankalan City, Negros Occidental', NULL, NULL),
(1060, 'Southville Foreign University - Las PiÃ±as', NULL, NULL),
(1061, 'Southville International School and Colleges - Las PiÃ±as', NULL, NULL),
(1062, 'Southway College of Technology - San Francisco, Agusan del Sur', NULL, NULL),
(1063, 'Southwestern University - Cebu City', NULL, NULL),
(1064, 'SPJ International Technology Institute Inc.', NULL, NULL),
(1065, 'SPJ - Calabanga - Calabanga, Camarines Sur', NULL, NULL),
(1066, 'SPJ - Tinambac - Tinambac, Camarines Sur', NULL, NULL),
(1067, 'STI College (multiple campuses)', NULL, NULL),
(1068, 'STI College Balagtas', NULL, NULL),
(1069, 'Sto. Rosario Sapang Palay College - San Jose Del Monte City, Bulacan', NULL, NULL),
(1070, 'Stonyhurst Southville International School - Batangas City', NULL, NULL),
(1071, 'Sultan Kudarat Polytechnic State College', NULL, NULL),
(1072, 'Sumulong College Of Arts And Sciences', NULL, NULL),
(1073, 'Superior Institute of Science and Technology of Santiago City', NULL, NULL),
(1074, 'Surigao City Adventist Learning Center - Surigao City', NULL, NULL),
(1075, 'Surigao del Sur Polytechnic State College', NULL, NULL),
(1076, 'Surigao del Sur Polytechnic State College - Surigao del Sur Institute of Technology - Cantilan', NULL, NULL),
(1077, 'Surigao Education Center - Surigao City', NULL, NULL),
(1078, 'Surigao del Norte State University - Surigao City', NULL, NULL),
(1079, 'Surigao del Norte State University - Del Carmen, Surigao del Norte Campus', NULL, NULL),
(1080, 'Surigao del Norte State University - Mainit, Surigao del Norte Campus', NULL, NULL),
(1081, 'Surigao del Norte State University- Malimono, Surigao del Norte Campus', NULL, NULL),
(1082, 'Systems Plus College Foundation', NULL, NULL),
(1083, 'Systems Plus Computer College - Caloocan', NULL, NULL),
(1084, 'Systems Plus Computer College - City of San Fernando', NULL, NULL),
(1085, 'Systems Plus Computer College - Cubao', NULL, NULL),
(1086, 'Systems Plus Computer College - Davao', NULL, NULL),
(1087, 'Systems Plus College Foundation - Miranda, Angeles City', NULL, NULL),
(1088, 'Systems Plus Computer College - Quezon City', NULL, NULL),
(1089, 'San Mateo Municipal College - San Mateo, Rizal', NULL, NULL),
(1090, 'Tabaco College - Tabaco City, Albay', NULL, NULL),
(1091, 'Tagoloan Community College - Tagoloan Misamis Oriental', NULL, NULL),
(1092, 'Taguig City University - Taguig', NULL, NULL),
(1093, 'Tagum Doctors College, Inc. - Tagum City', NULL, NULL),
(1094, 'Talisay City College - Talisay City, Cebu', NULL, NULL),
(1095, 'Tanchuling College - Legazpi City', NULL, NULL),
(1096, 'Tan Ting Bing Memorial Colleges Foundation, Inc. - San Isidro, Northern Samar', NULL, NULL),
(1097, 'Tarlac Agricultural University - Camiling, Tarlac', NULL, NULL),
(1098, 'Tarlac State University', NULL, NULL),
(1099, 'Tarlac State University - Main Campus in San Roque', NULL, NULL),
(1100, 'Tarlac State University - Lucinda Campus', NULL, NULL),
(1101, 'Tarlac State University - San Isidro Campus', NULL, NULL),
(1102, 'Tasashyass College Inc - Camarin, Caloocan', NULL, NULL),
(1103, 'Technological Institute of the Philippines', NULL, NULL),
(1104, 'Technological University of the Philippines', NULL, NULL),
(1105, 'Technological University of the Philippines - Manila (Main Campus)', NULL, NULL),
(1106, 'Technological University of the Philippines â€“ Cavite', NULL, NULL),
(1107, 'Technological University of the Philippines - Cuenca', NULL, NULL),
(1108, 'Technological University of the Philippines - Lopez', NULL, NULL),
(1109, 'Technological University of the Philippines â€“ Taguig', NULL, NULL),
(1110, 'Technological University of the Philippines â€“ Visayas', NULL, NULL),
(1111, 'Thames International/Entrepreneurs School - Quezon City', NULL, NULL),
(1112, 'The MARIAM School of Nursing, Inc. - Lamitan City, Basilan', NULL, NULL),
(1113, 'Tiwi Community College - Tiwi, Albay', NULL, NULL),
(1114, 'Tomas Claudio Memorial College - Morong, Rizal', NULL, NULL),
(1115, 'Tomas del Rosario College - Balanga, Bataan', NULL, NULL),
(1116, 'Trace College - Los BaÃ±os', NULL, NULL),
(1117, 'Trace College - Makati', NULL, NULL),
(1118, 'Trent Information First Technical Career Institute', NULL, NULL),
(1119, 'Treston International College - Bonifacio Global City, Taguig', NULL, NULL),
(1120, 'Trinitas College Pantoc Meycauayan, Bulacan', NULL, NULL),
(1121, 'Trinity University of Asia (formerly Trinity College of Quezon City)', NULL, NULL),
(1122, 'Tubod College - Tubod, Lanao del Norte', NULL, NULL),
(1123, 'Tyrone Valera University - Sindangan, Zamboanga del Norte', NULL, NULL),
(1124, 'Unciano Colleges, Inc', NULL, NULL),
(1125, 'Unciano Colleges and General Hospital - Manila', NULL, NULL),
(1126, 'Unciano Colleges and Medical Center - Antipolo', NULL, NULL),
(1127, 'Unida Christian Colleges - Anabu, Imus City, Cavite', NULL, NULL),
(1128, 'Union Christian College (Philippines) - San Fernando, La Union', NULL, NULL),
(1129, 'Union College of Laguna - Sta. Cruz, Laguna', NULL, NULL),
(1130, 'United Doctors Medical Center - Southeast Asian College - Quezon City', NULL, NULL),
(1131, 'Universal Colleges of Paranaque Inc. - Sucat Road, Paranaque City', NULL, NULL),
(1132, 'Universidad de Manila', NULL, NULL),
(1133, 'Universidad de Sta. Isabel - PeÃ±afrancia Ave., Naga City, Camarines Sur', NULL, NULL),
(1134, 'Universidad de Zamboanga', NULL, NULL),
(1135, 'University of Antique - Hamtic, Antique', NULL, NULL),
(1136, 'University of Antique - Sibalom, Antique', NULL, NULL),
(1137, 'University of Antique - Tibiao, Antique', NULL, NULL),
(1138, 'University of Asia and the Pacific - Ortigas Center, Pasig', NULL, NULL),
(1139, 'University of the Assumption - (San Fernando, Pampanga)', NULL, NULL),
(1140, 'University of Baguio', NULL, NULL),
(1141, 'University of Batangas', NULL, NULL),
(1142, 'University of Bohol - (Tagbilaran City)', NULL, NULL),
(1143, 'University of Cagayan Valley (Cagayan Colleges Tuguegarao)', NULL, NULL),
(1144, 'University of Caloocan City', NULL, NULL),
(1145, 'University of Camarines Norte (formerly Camarines Norte State College)', NULL, NULL),
(1146, 'University of Catbalogan City - Samar', NULL, NULL),
(1147, 'University of Cebu', NULL, NULL),
(1148, 'University of Cebu - Main Campus, Sanciangko St., Cebu City', NULL, NULL),
(1149, 'University of Cebu - Banilad Campus, Gov. M. Cuenco Ave., Cebu City', NULL, NULL),
(1150, 'University of Cebu - Lapu-lapu & Mandaue, A.C. Cortes Ave., Mandaue City', NULL, NULL),
(1151, 'University of Cebu - Maritime Education and Training Center, Alumnos St., Cebu City', NULL, NULL),
(1152, 'University of Cebu School of Medicine, Mandaue City', NULL, NULL),
(1153, 'University of Cebu - South Campus (defunct)', NULL, NULL),
(1154, 'University of the Cordilleras (formerly Baguio Colleges Foundation)', NULL, NULL),
(1155, 'University of the East', NULL, NULL),
(1156, 'University of the East - Caloocan', NULL, NULL),
(1157, 'University of the East - Manila', NULL, NULL),
(1158, 'UERMMMC - Quezon City', NULL, NULL),
(1159, 'University of Eastern Philippines - Catubig Campus, Northern Samar', NULL, NULL),
(1160, 'University of Frederick Alcantara - Quezon City', NULL, NULL),
(1161, 'University of Iloilo', NULL, NULL),
(1162, 'University of the Immaculate Conception - Davao City', NULL, NULL),
(1163, 'University of James Din - Quezon City', NULL, NULL),
(1164, 'University of La Salette', NULL, NULL),
(1165, 'University of La Salette - Main, Santiago City', NULL, NULL),
(1166, 'University of La Salette - Aurora, Isabela', NULL, NULL),
(1167, 'University of La Salette - Cabatuan, Isabela', NULL, NULL),
(1168, 'University of La Salette - Cordon, Isabela', NULL, NULL),
(1169, 'University of La Salette - Jones, Isabela', NULL, NULL),
(1170, 'University of La Salette - Quezon, Isabela', NULL, NULL),
(1171, 'University of La Salette - Ramon, Isabela', NULL, NULL),
(1172, 'University of La Salette - Roxas, Isabela', NULL, NULL),
(1173, 'University of La Salette - San Mateo, Isabela', NULL, NULL),
(1174, 'University of Luzon - Dagupan', NULL, NULL),
(1175, 'University of Makati', NULL, NULL),
(1176, 'University of Manila', NULL, NULL),
(1177, 'University of Mindanao', NULL, NULL),
(1178, 'University of Mindanao - Main Campus, Bolton Street, Davao City', NULL, NULL),
(1179, 'University of Mindanao - Main Campus, Matina, Davao City', NULL, NULL),
(1180, 'University of Mindanao - Bangoy Campus', NULL, NULL),
(1181, 'University of Mindanao - Bansalan Campus', NULL, NULL),
(1182, 'University of Mindanao - Cotabato Campus', NULL, NULL),
(1183, 'University of Mindanao - Digos Campus', NULL, NULL),
(1184, 'University of Mindanao - Guianga Campus', NULL, NULL),
(1185, 'University of Mindanao - Panabo Campus', NULL, NULL),
(1186, 'University of Mindanao - PeÃ±aplata Campus', NULL, NULL),
(1187, 'University of Mindanao - Tagum Campus', NULL, NULL),
(1188, 'University of Mindanao - Tibungco Campus', NULL, NULL),
(1189, 'University of Mindanao - Toril Campus', NULL, NULL),
(1190, 'University of Negros Occidental - Recoletos', NULL, NULL),
(1191, 'University of Northeastern Philippines - Iriga City', NULL, NULL),
(1192, 'University of Northeastern Philippines - Catarman, Northern Samar', NULL, NULL),
(1193, 'University of Northern Philippines - Vigan, Ilocos Sur', NULL, NULL),
(1194, 'University of Nueva Caceres', NULL, NULL),
(1195, 'University of Pangasinan - Dagupan City', NULL, NULL),
(1196, 'University of Perpetual Help System', NULL, NULL),
(1197, 'University of Perpetual Help System DALTA', NULL, NULL),
(1198, 'University of Perpetual Help System JONELTA', NULL, NULL),
(1199, 'University of the Philippines (8 campuses)', NULL, NULL),
(1200, 'University of Rizal System (multiple campuses)', NULL, NULL),
(1201, 'University of Saint Anthony - San Miguel, Iriga City', NULL, NULL),
(1202, 'University of Saint La Salle - Bacolod City', NULL, NULL),
(1203, 'University of Saint Louis Tuguegarao Tuguegarao, Cagayan', NULL, NULL),
(1204, 'University of the Samar Island Archipelago (formerly Samar State University) - Catbalogan City, Main Campus', NULL, NULL),
(1205, 'University of the Samar Island Archipelago - Basey', NULL, NULL),
(1206, 'University of the Samar Island Archipelago - Catarman, Northern Samar', NULL, NULL),
(1207, 'University of the Samar Island Archipelago - Guiuan, Eastern Samar', NULL, NULL),
(1208, 'University of the Samar Island Archipelago - Mercedes, Catbalogan City', NULL, NULL),
(1209, 'University of the Samar Island Archipelago - Paranas', NULL, NULL),
(1210, 'University of the Samar Island Archipelago - Pinabacdao (South Samar Campus)', NULL, NULL),
(1211, 'University of San Agustin - Iloilo City', NULL, NULL),
(1212, 'University of San Carlos', NULL, NULL),
(1213, 'University of San Carlos - Downtown Campus (main)', NULL, NULL),
(1214, 'University of San Carlos - North Campus (formerly Boys\' High School)', NULL, NULL),
(1215, 'University of San Carlos - South Campus (formerly Girls\' High School)', NULL, NULL),
(1216, 'University of San Carlos - Talamban Campus', NULL, NULL),
(1217, 'University of San Jose - Recoletos - Cebu City', NULL, NULL),
(1218, 'University of San Jose-Recoletos - Main Campus, Magallanes St., Cebu City', NULL, NULL),
(1219, 'University of San Jose-Recoletos - Balamban Campus, Arpili, Balamban', NULL, NULL),
(1220, 'University of San Jose-Recoletos - Basak Campus, N. Bacalso Ave., Cebu City', NULL, NULL),
(1221, 'University of Santo Tomas - Manila', NULL, NULL),
(1222, 'University of Santo Tomas - Legazpi', NULL, NULL),
(1223, 'University of Southeastern Philippines - Davao City', NULL, NULL),
(1224, 'University of Southern Mindanao - Kabacan, Cotabato', NULL, NULL),
(1225, 'University of Southern Philippines Foundation - Cebu City', NULL, NULL),
(1226, 'University of Southern Philippines Foundation - Lahug Campus (main)', NULL, NULL),
(1227, 'University of Southern Philippines Foundation - Mabini Campus', NULL, NULL),
(1228, 'University of the Visayas', NULL, NULL),
(1229, 'University of the Visayas - Main Campus, Colon St., Cebu City', NULL, NULL),
(1230, 'University of the Visayas - Mandaue Campus, D.M. Cortes St., Mandaue City', NULL, NULL),
(1231, 'University of the Visayas - Pardo Campus, Pardo, Cebu City', NULL, NULL),
(1232, 'University of the Visayas - Minglanilla Campus', NULL, NULL),
(1233, 'Urdaneta City University - Urdaneta City, Pangasinan', NULL, NULL),
(1234, 'UST Angelicum College - Quezon City', NULL, NULL),
(1235, 'Valencia Colleges - Valencia, Bukidnon', NULL, NULL),
(1236, 'Velez College - Cebu City', NULL, NULL),
(1237, 'Vineyard International Polytechnic College - A. Luna St., Cagayan de Oro', NULL, NULL),
(1238, 'Virgen Delos Remedios College - Olongapo City', NULL, NULL),
(1239, 'Virgen Milagrosa University Foundation - San Carlos, Pangasinan', NULL, NULL),
(1240, 'Visayas State University Main Campus - Baybay City, Leyte', NULL, NULL),
(1241, 'Visayas State University - Alang-alang, Leyte Campus', NULL, NULL),
(1242, 'Visayas State University - Isabel, Leyte Campus', NULL, NULL),
(1243, 'Visayas State University - Tolosa, Leyte Campus', NULL, NULL),
(1244, 'Visayas State University - Villaba, Leyte Campus', NULL, NULL),
(1245, 'Visca N Roxas College', NULL, NULL),
(1246, 'WCC Aeronautical College - 461 William Shaw St., Grace Park, Caloocan, Philippines', NULL, NULL),
(1247, 'World Citi Colleges - Antipolo, Quezon City, Guimba, Nueva Ecija', NULL, NULL),
(1248, 'Worldtech Resources Institute (WRI) Colleges', NULL, NULL),
(1249, 'WRI Metro Naga - National Highway, Concepcion Grande, Naga City, Camarines Sur', NULL, NULL),
(1250, 'WRI Partido - San Juan Evangelista St., Goa, Camarines Sur', NULL, NULL),
(1251, 'WRI Rinconada - San Miguel, Iriga City, Camarines Sur', NULL, NULL),
(1252, 'Wesleyan University-Philippines - Cabanatuan City', NULL, NULL),
(1253, 'Wesleyan University-Philippines (Aurora) - Maria Aurora, Aurora Province', NULL, NULL),
(1254, 'West Bay College - Alabang, Muntinlupa', NULL, NULL),
(1255, 'West Institute of Technology', NULL, NULL),
(1256, 'West Negros University - Bacolod City', NULL, NULL),
(1257, 'West Visayas State University - Lapaz, Iloilo City', NULL, NULL),
(1258, 'Western Institute of Technology - Lapaz, Iloilo City', NULL, NULL),
(1259, 'Western Leyte College (WLC) - Ormoc City', NULL, NULL),
(1260, 'Western Mindanao State University â€“ multiple campuses', NULL, NULL),
(1261, 'Xavier University - Ateneo de Cagayan', NULL, NULL),
(1262, 'Zamboanga Peninsula Polytechnic State University - Zamboanga City', NULL, NULL),
(1263, 'Zamboanga del Sur Maritime Institute of Technology - Pagadian City', NULL, NULL),
(1264, 'Zamboanga State College of Marine Sciences and Technology - Zamboanga City', NULL, NULL),
(1265, 'Zamora Memorial College - Bacacay, Albay', NULL, NULL);
